apiVersion: v1
kind: Secret
metadata:
  name: hermes-agent-secret
  namespace: ai
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:vabo9+0wvQgbsp991YUzdMpL7MahmznLjUg5csQJtRKPwkQpFTYVizFcNAwhFQ==,iv:3wZ2lPxTHPuwJN/IzExe48sPE3+UwV2vgd9bcSXCfVo=,tag:lOLSRTCqhawlONDSHPUFdg==,type:str]
  API_SERVER_KEY: ENC[AES256_GCM,data:+hves0CqNv8bjxQyqxJFA0kTFE/pTfKsN7WxRuQu25brRNUMbxGcwijBdZ29Xk4eOctgZMqgOKEv7Carj0W9EA==,iv:YgBZM6SOOGoBDzXmPx5HpjEcKNmLUXt6XDQ+zLOL7RY=,tag:WlsvjZlg88YvrksIxdBDRA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY2pZQ0ZNa1d2Y1hqcTBj
        cGFWc1BsZFFKbTVESGtPZTZYZmZ2OGFlU2kwClhOR2tzWHZlM1l6c1hlTDN5RXRn
        a3AzZkp0bWZWQ1lPM1B3bG9YRmI5WncKLS0tIEdtRjBmMGY3VFJsUWZpUHF1WVM3
        QXpZK01PQ3dVUVRzN1VPRFhsbXJKSXcKMojCqBWkFnbF0nzV0gf8pFAPEOoGxhc7
        nficI0aftx6QMEc8BFMlBgCZ/N6zKIDaH3x9rAed6A4NTBvw+W9QuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T07:45:24Z"
  mac: ENC[AES256_GCM,data:dOfQEwosYO075ijRmgDnATH7rS9MFka5ouw0NBhhB9N9nZQc3OEh7TypMzQXTpSgPXzHDarRmBLfm+fsPGrw89PZE3/Kf+CErJ8Xu0GL9Ayje7idpud3tZxKVNyO/4b5MvPjN3ZpD8bWTuq303OlS0R2p4Z9wPP88zv8f0bAiN4=,iv:suSLwGrUH9sdYQ/viOMz6msAQdpF568M8Mo+0QBR0FM=,tag:2AlyHwPX26nQxcf9eev1tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
