apiVersion: v1
kind: Secret
metadata:
  name: hermes-agent-secret
  namespace: ai
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:5L9sNvah6QDDsIonWtjHtN0MQ4vR/D6eM0mj8FtJNAB58oYlNoB/RzD2hvc9SQ==,iv:Do34KNejhRqL2PLs8U30N2JMWsXJYrQbYwcpXEVshuU=,tag:cI3VP6gXxZh0siOYI3nTdg==,type:str]
  API_SERVER_KEY: ENC[AES256_GCM,data:PNrXLhD81k2XZkRHLEHZDp1JC7wMgnkhSEjNQdcWHzelaM0/eJgs5BgJ01ktuXqC9VJCu0NsZWowK0z8mxyBfA==,iv:3ouFmdnaySxklbjulXG8eRJRipeajt1Eiv4eGkBDg7k=,tag:ogmD96lhM8ugrHO5rJ8gXw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdDZ1TTRKNWY3QnRsOFlB
        QVNXYlhlV3dORm9KZW1ZWFJqeWFPSTdCSlNJCmFLMFY4dzBBM0IrN3VJckpaczI5
        dStmY0RSaUE1M3htaFljSjhmWnZ4VDgKLS0tIHNiSWU3U0dIRmF2VEwwYW1vM01X
        SzJLV2pRNEpraWk1eEx1RjNUNmxWMXMK8x49ut1ruvN2Pqi6exc6CtHkU9CHenQR
        blG20aHsSON4U8rRhLfgpImw7AHV8N6v5UPgd6WaBXwlKrhmqNE+0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T07:32:38Z"
  mac: ENC[AES256_GCM,data:jhDRj4cD+bdy8FS2mq8R4SojSiAP4WjVDoK9zRXN+oaAIeaoDqsRbfOnkD8SezV0gRbLcMCdsuTEfFIPL7/S7d+4Ae9eVUluo07e2yBoC2pvhxgQzY2Yb7GBUWbE3H3F6OJju+NG3IvJdViBi/E9uwljR5VlzRNvkmBVc4pUwOM=,iv:D25mwxbYzLXX+AQ058NOAAU5wKuluGxAH9AhKz4hQW4=,tag:Fx+4oOXQ0yiS7++cojcDZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
