apiVersion: v1
kind: Service
metadata:
  name: haarfabrik
  namespace: my-software-showcase
  labels:
    app: haarfabrik
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: haarfabrik
