---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-storage
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
