apiVersion: v1
kind: Secret
metadata:
  name: anythingllm-secret
  namespace: ai
stringData:
  AUTH_TOKEN: ENC[AES256_GCM,data:lN4i3r8xyCMWt8hlofeAVdMEGM1t0h5xiR1/8YEMQRGewG1XF3q+1rgonTI=,iv:VcYp//7+Meude/a6ZUxPkyp3RjHA0YAOqOcwnAYHAqc=,tag:m8xwzubFH4hLVsUqNALDwA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:g7POwV5FiNA25dsIaUrMYBwfO7E8HKI0T1bMS5n/KyL0Mop9IzR/MDbozoNH3SYduH1q1cjDWpTMF/BupXbPlCmXaq1siCqKVO2s0ZZb2Tsr9GN2k3Icew==,iv:vZXa6whRWwrN2r21rskL8cui0hk/8V2CXPIGYSfZyLI=,tag:0tZ1NXi8RjVlJuGs3LQvPw==,type:str]
  SIG_KEY: ENC[AES256_GCM,data:lDOysa7KaQJIs5M3aMdUMGMdQT9LuA/wkdEz4ssNzBwGPD9NiZ/zfWMVcvcySTgptIYc2twao+FLhXIgZK8XiA==,iv:gzI0WBOTSR0EYbVZHffsf6kWpaOpnqTMqKoUiJXnDQQ=,tag:uEWpBAgMPXJ7w7k8QbbUWg==,type:str]
  SIG_SALT: ENC[AES256_GCM,data:/gXDmf8TSinzlzArCZqe7o6pbXQFXeFW/5t4hGNDgL8=,iv:AlAROE+bOcDX2EFRXP0okVhMlhZBAmiWK4hL+bq2kPU=,tag:IJrr5f8mvkiKrpCyvzTcPA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSytKZVFkcEhjWklWcU5O
        RzdXVlpQbVNqdUk3MU1naFZQVG5nU25HcnhnCjM1R29SbERhTWFoRFRBNjRQeWpT
        R05zTjl3c2c2Rk95NitwbGZkcGhnckUKLS0tIFpUaXVFeU55S3FKYkcxSEJOdnd4
        OVhGTVhKbHVtRVZsUnVkM2RNTUZpblkKCX0JL7KoRPSBHgFqsoHgy9pbRXG9SZ1W
        gRhbGQ96MxGCanfdwFqy+9SiU6Q92PLJS6PfFO/azr+ZLEDEtGlqRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T07:20:30Z"
  mac: ENC[AES256_GCM,data:RtX2ndVIRITL2I/AcP/lGJEgibQCRA1H36JNTdr98Q5nyTVWr2bqKnKSQzWiKPpLqFLc3dvrXe6/54tsFx6unDDMxXpVqQyDGq1j8axD2MAR9qS0FwVVkHU+tP1/prKYOUIqSIZFD2CbVPiYTXCDwuuj11tiN+O8lZMZrURIFPU=,iv:adKBMRKl/I5BSOHH83aC0Xoq89ZHQLcSLyLVGxMou9I=,tag:RbK28UoinqaJZfFnzR7dBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
