apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-software-showcase

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml

commonLabels:
  app: ibgastro
  version: "1.3.6"

commonAnnotations:
  managed-by: kustomize
  environment: production
