apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibgastro-uploads
  namespace: my-software-showcase
  labels:
    app: ibgastro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
