# PHP tier. All three PHP apps read DB_USER / DB_NAME / DB_PASS - a different
# convention again from the four used across the Rails apps. Verified against
# this app's own config, not assumed.
apiVersion: v1
kind: Secret
metadata:
  name: ibgastro-secrets
  namespace: my-software-showcase
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:u8+zKGFSMPrKcSxuZUdj7ciOnQw9CxTzsRK6L9QgUGSdx/U=,iv:SWQuziT7W2CkNZYIdMU8BUPRs/usNmEKQTf8cqquOS0=,tag:G4QrCqtqPIqogMcJiDSNBQ==,type:str]
  DB_PORT: ENC[AES256_GCM,data:vOLZ5Q==,iv:9MqriZVIV9k+yQiCMB0diKBqysdhkGwfseECS5QNvhM=,tag:lRhn7eigETwoiV+hshxtdw==,type:str]
  DB_USER: ENC[AES256_GCM,data:DPxkAHLXmbWGvOEIp9DsBosayNhhcg==,iv:rR/ezI9la8zS701dy/L1HXbu+lUuFD+c3XbJIkvAWPA=,tag:wUTGuccbUu9ekW8w6G+Qdg==,type:str]
  DB_PASS: ENC[AES256_GCM,data:JXVgahDq0ocEGyF0KVI5A7emPLgOo35y,iv:yEfaGtJDQe+pfzw9DUoJ50341yTjgi97XbvNGx+ZPRg=,tag:2mARd1f6XbCxu6ewBAzRZQ==,type:str]
  DB_NAME: ENC[AES256_GCM,data:YRCmB8G5evZY1yF6jV9bUww5VLn8WQ==,iv:V6VjWdGYIIkm+d+RXf+Wp/BOiU4opJhdsWBrlwDgfHM=,tag:1u9ECQDAA7GBwObkIkxi5w==,type:str]
  CAKEPHP_SALT: ENC[AES256_GCM,data:DR5cX3DnKawnYzrn6iKY9RmdRU7xcOB6Mk/PuqtGNW+0NvgEaiti3/GDR7e/swkvh1Cpdaicp0QR3tLN7PlvCQ==,iv:XNbwMXk9QOgGQnfagEXhDxRORozK0zpjXF3zatCA8A8=,tag:Q2vtlt57ViKVYMk7Z0yb1w==,type:str]
  CAKEPHP_CIPHER_SEED: ENC[AES256_GCM,data:pCTOWjlJFEwymOTZf+BVhbt958g=,iv:7F5I8y6Yz3ag4UVPSojQHO9i76/QhFGLmuzGnLnazoQ=,tag:QkGpfnR9fH3bbFonLE8SpA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcVlYZEQ0UTE0bXJaak0x
        bzlKRElJcHYzR1RqU2RaMnlnYjB3VkdWUlFVCmlZK21tN25BKzhMK2pQUExTMnE0
        REFDcmpkdDV6aEZkaFdVV0ZvZ0Jzc0EKLS0tIC9jbXRIdklTSm5LMGhIRWRCTkhQ
        T3YrdUR3bDNOZlJFVW11bzlkT1RPMDAKM7vlf+RBjDwG54No4oBOGKnVu0N044U1
        9iKXoCypUKWR9L9kCrvgpPytpMP9LNhlEPowSgaPtL3PPxf2ZS0VxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T12:24:19Z"
  mac: ENC[AES256_GCM,data:nVlFUlqNiQIZ0M5Ha3KMmB+beZUPRD6m13e0nAlFZtxqZ4ufwOuLAQm4/KQqRN9SSdvc7o86vK9AsLi18xQBWgf3xAz0Ox3hPDPAyNK9eobqQD63yYFCnsyBAxDTXeaM9aD2VaHAlevhUqF+kibu0AYXb0AqJPKgpj3kcqjZFCE=,iv:vZr6bqDe5x1sEkv3XhJTFxI+GM1as7I6oMpZla7zloY=,tag:5xKJC2ekcEk0jJwbWHFVvw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
