apiVersion: v1
kind: Service
metadata:
  name: ibgastro
  namespace: my-software-showcase
  labels:
    app: ibgastro
spec:
  type: ClusterIP
  selector:
    app: ibgastro
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
