apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secret
  namespace: security
type: Opaque
stringData:
  INDEXER_USERNAME: ENC[AES256_GCM,data:aBpXN00=,iv:MiHF09MY6LDdZbeomnp2vEXzhdsh0SLlgzwK0WNh3uc=,tag:eAs3cecEoGPxxV+kgNpliQ==,type:str]
  INDEXER_PASSWORD: ENC[AES256_GCM,data:IvsMkEY=,iv:XOWyFJIiCWSSXRU8Q+Srk5FuCwtmZQLIR1MZUMq+exw=,tag:/8UiqKVL08TUXJ2+K8NG7w==,type:str]
  API_USERNAME: ENC[AES256_GCM,data:hlf/EMGNotqp,iv:fDU4w6wQoLsFJBNYPxJf0WIncBc/njPLf7Vz6ZPm5aI=,tag:eWxYYBd7fP2a/RnsmCGnWw==,type:str]
  API_PASSWORD: ENC[AES256_GCM,data:RPG3My1MB562HIjn2AjZEJLZqnq1fHFizqBB7tTqoME=,iv:B1FJUQ2qQz38hdij0w+iReD9UiyxyuQOWgJbyDhsLZw=,tag:mS9ir+HNh3b7MDEbvnpEYA==,type:str]
  DASHBOARD_USERNAME: ENC[AES256_GCM,data:yedideHM7RK/kgHe,iv:+h+W3UkHxaNLA0BAaJ4tuw2mp/X5Qg4WoKUHmZiTsy0=,tag:QQXId+PV71iMU9you5eetA==,type:str]
  DASHBOARD_PASSWORD: ENC[AES256_GCM,data:ragRKG3EKqC9egzf,iv:hbc2ZzXydfRU/HmChx4i3CqWC+weVR3ZCUt1oBbGRhI=,tag:XDWYXtbFtYQp5rc97ffJhA==,type:str]
  CLUSTER_KEY: ENC[AES256_GCM,data:/KhDhmonpKCEyFS36W8QIjtlztE7GaFIhqUkbNQclCc=,iv:t34YINV6l4t0D2BLASXZLd9cFm0M0ogycc4x1q2ibPo=,tag:lISpnG0CGiSHf3ijLAjXsw==,type:str]
  opensearch_dashboards.yml: ENC[AES256_GCM,data:Vonrv4uwjhIHEvvr+/BsXcM7jeQJjOmuadc7UFs34jnO8HkN/HhlB+/7RRSCHRho/5hcABPSj6vYk7S6pRzJqOHRQjPzp+NVj4WOP5+W+8NKSqPJSHHImzcVM0Mij6Z3IZbCJggt/cnbrHq/wl4yCdCKkx2ilCYsWOSrx3Fd0CC62I8dTAa8lyFFx/YZ2DEAZG+8ZW4x7DZ69+8MeY/kTJ3QoE+5iQdUuquxgcim2V0p85D5o4UQshwTtphXkmw2B8jryj08VRIdY2QW1+1O7JwQgf6ZRorfqsAzQOOS7nbGY6rTiJ6ZYxcFsZ8cp1FuwIoTaXUGSjAZKut6DtY+0lXd1QHhmdGEfTsavmDzr0TPxhc/BsOjln1m1RuEzZGR6b3qix0Duc1vGRP96kOzWcgWIYZGDJZ/aDWO6nKbQkw5Wcu144/pmZyaLtHRGCwP6EP4XxFOY5M80oNt91yWmRz/cvRfC/FPDOsRK4ZnyDeu70DS/D9lGA+IusO57O7vekMTg5Zzw9cvJaa2OicdKpFDXgCA7G5O4BlXRC5n8zAbdlXPC/pdcwlAYAu4g02h2iUa2eB57VLaEMnA/ORDmnB4t6VaNgNSaKnwLn5TtqtGsXyRF4EvUVN3DGzIOeeYpsBDb2KiCIg0U0DBc6Gm5xmJbXdkl7jloMpwTeTeyhkoHCdPZnFU5M/TVGf5L00HVc3KcGLUt465I3FopBIcuaAU1TWeVdBEVCJUyyi1FDXdeV5cAnuBY/ladcROUn2ZYVonQSZbiXhUKNFBUvCkLdIu6n4RHQ==,iv:CVVjun9Zgk4yWhC0Q3hsDFNMmPjz2NaCP7e7JizDUy0=,tag:GP+2Ffk069S9JbHkWavuHw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWXg4MUM0MXZoUFc0TVls
        aUN1OWFSSWp5U3RkcHVJWERwU2FUUHRXanpvCmFhMCtpUFBkdDBIZmd3OC9OVzYz
        Ykg2RWFxalBMODRoUFg4b05DZmlPU00KLS0tIDJ1cmJCd0pWUThxMXRHZHBTNEtZ
        Y09qVU1nbmdSUVYwZExZNVZHemtEN00KDlCtAXHm5ub5cLpXGWO23zkUxk4jmQiB
        dNUEj5SDBossEuWKiP39O0Rnst1ThubtRquljdKws+2xhUvmwhTHBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T21:19:13Z"
  mac: ENC[AES256_GCM,data:rYx7VDHLDGpuSreLrXx4rdV78D9aoYS7APGa94l1dUd3FMWDfD9FRqCfi2FuZ6nlHWg5cwhAPBEYKKu+E48wY3FICjS1urMCHaa6t8EVWKc3v0xeImZEL5o5kZD5cPRTaDK0XsOY7RjVj87Buvbu4a38B5H+pmyWlakAXQPVA2o=,iv:4d4Eq7GRyqNdKzrsGqPYcsf2t145k4CLRCXFJpArrYo=,tag:xobw6XQSgc5QZLGuUjzL8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
