apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secret
  namespace: security
type: Opaque
stringData:
  INDEXER_USERNAME: ENC[AES256_GCM,data:H933J5o=,iv:O9VK+2q8M+2f+ram5JWHVOArWdFsGmgvauHoLKyDjwE=,tag:gWI1dm81wJ4vG2BY60Gfkg==,type:str]
  INDEXER_PASSWORD: ENC[AES256_GCM,data:Vsa68vQJg4Ao0nNAHM+4MeMJRUCFij37joiuF2dC3Ow=,iv:ymRTzHhq+uOCPkgS/hOz5Tk4Ii0kBVP4QvxEu7hoiXQ=,tag:J6bqAmMXMLnx6mYE+JM7iA==,type:str]
  API_USERNAME: ENC[AES256_GCM,data:WFi5yCkfziIv,iv:7oIpea2ihZ8JSge9WBRllRDkoXeSuN7CA+OnVlMDvk8=,tag:QiyrR6dwV2zK/2AWLRZtRA==,type:str]
  API_PASSWORD: ENC[AES256_GCM,data:fO9Xw0HDSF6vdoIKn/CPqRkq+/JdWinWPijRi+cKzI4=,iv:Ticga9Nw1Rvxl7xRWapTobwhH04fTszf/SZAXVfCB+E=,tag:mnGW5T9yUQT5HKLTN6fWKQ==,type:str]
  DASHBOARD_USERNAME: ENC[AES256_GCM,data:tt6yHWso7tajXpwX,iv:ZAgYoAdxdr2oOYgCtwdIRhgvuaJL++Fx2Lh+M5N1y34=,tag:ehwZxbuSB7oLe4YIvvb4Kg==,type:str]
  DASHBOARD_PASSWORD: ENC[AES256_GCM,data:DCzundHw33pf3YFU8jB4FGP1T4ghQaCPuJuseE+Pco4=,iv:vOxBbdKAoUsnpUwzMKDU8Fh0SYVBEJF5laqycGgJz7Y=,tag:n5yhJVFBTRQFDQKicAL4bA==,type:str]
  CLUSTER_KEY: ENC[AES256_GCM,data:Y5GczqpSICL0zEo7Ww9ZkVOdnC5hjMBfhRBQtNgOx4Y=,iv:l6vBPpMrMMCqAOPJHQyTF4hEFe63YH0DucueJ6bblfc=,tag:jjHDrtaZ+59luxs4bNNChg==,type:str]
  opensearch_dashboards.yml: ENC[AES256_GCM,data:nvuL/S8Q/0EiAOHMMQ5vwb/ULdF685yCbZ7F0b6jH6qyxGiRIJmMpzWJYsEGEp74gXmzqhYfqL21gv6sUx9dKDt8Eqp2wqMoITnnuhRMwIbMbw+kMhNDOYmH/ctehLQtKIqoGUKDxAQ6j/KSREvk9kJwZpAjlCgAX49hPeDtry0Cgph4+0+VUqQS0GuYZHlmOzJ7s93CZpvDiosFhVK3zmeyyUuT7/AaPFGdzAy9byWCEkxAdCfrCQg/cp89MECz8T3lA0bLe00NwQOVIcMSwuCeXuUyHOgneqVJKz6FcnkJwsEMulTeXiFa6NbISCXE8d2oOBJ7ATBSuNLYFgCYZOux5nfx0kptxJ7abbPDMTtYzaGApJrlpcOTPGyZjndUjVpUK+l0f1HRrXrzbJPpJmc0RlIAVOCZO7HqP7ZypNOJQTS8iNWCr9FV0HWKLK9V/jLpXZnDVLd1VfNhgf/3ObNFHZzp/g70V+5VQrPw2sZcXzN9itKXY/1CgXBM1VGF1rmgM9gWI4+cVd4DizUrJAAp1+sNdHSisc4Wwhj/Es9KTcWkGe3w1+dgnyM6Q+3s5ui/wNWOdD4kDowXhglSgCcTPXxKRSjUNcckX9+ubSUYk8AI3l+opd5V/gpxfFCP3olBlG1L+M/w30ABqKx1gki3uTAZwUybX9kiNZzYXsTp/iyJaYSjwFshCZXvnRZ1/I7pc9+sbCg/Wm+KmWqvZ1ITWtJ+b3RTXyrfWI4R5EgJolvYd24z4Ne9ctzTSRd5Q4NmQBh63UhrF4QXXvRaVhP9OBFSEXHv6QrsfYuvczRQ0Jxc5PnyfbaZB18oiFw5FXc+dBU1c0YgQRuDY+W1Y3IvGO3cNjiVRe8gIvxRspKPPF9NNBTRrlI2z3Aob+ScmoFRWKK17SLzilf7VqGOJfF0jLjRsQ5L0shi934JjtgBA3Gge55Gke9OADR9xNKO6NzsI/eA7f13oJancWUsV2Kl8bVtRn0UHlm0nfopgsvo11AeIeUb3aEkq81cAATQ,iv:/XCQpfmddirjlpoF9hUDBMfamIQDm4GS4QfxqCc8ZAE=,tag:bn5xVh6o/LPbfo1iBcTq8Q==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdlorNDRtdlY2SEJVdUZC
        amJSRnI5S21aMy9UQmRLVENFQ0FxcGNta1RvCjBnTVhqclJVbHdFSTc1dEJheEhK
        eE84WnVKaENGSG5qYVRJS2gvN3BNTGcKLS0tIEVHdElZWlZkVXJSdjZ6c1JWb1Zm
        S09NQWtBbDROWllPNWM5eExSL0xrZDgKdceqdgRQwjgC83/J1E6RCjspHdoPmclq
        VOoiCaL069ssubN++1lEAl8INOWo/3VMqDcj0xEVc2ps7XyGJzXZhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T19:34:22Z"
  mac: ENC[AES256_GCM,data:RNHSFWIiaW1Cp7Pt9G6VsVxFj0bIV2YqwkE7OogeCEMdE1MZ3hziVf2sSPd+ilZgdrw61EgwJYIa8TsyodgOikVX46vRd4hwzI85qEIaQF2PIDzDYXTw9/X8habRITAig6LmrkSJmKDqjkBiRWKX4QmAIJBbUd8fv5vKStmsuW0=,iv:p8anYGuvwy332XTkJE6u2nKzgzkyjgnF12SMCs7SeeU=,tag:o+K2AX1KnwCOGmm4IxseAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
