apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secret
  namespace: security
type: Opaque
stringData:
  INDEXER_USERNAME: ENC[AES256_GCM,data:W9rv8WI=,iv:vlaTonpVxGYgFEUMMKZ7hh1KL6c1nAAtK6T9SBULl8U=,tag:RGlw9o/mEztSRyuJcNGX3g==,type:str]
  INDEXER_PASSWORD: ENC[AES256_GCM,data:s+kcUF6IFOjZ8umI4byl/LRKIsLQe3JBBv5i5SAC6o4=,iv:a+oudCk32uOuyQGO82GHwCcr7QIGmOrY7ESPmzxC3qk=,tag:dkKJ5zMi58wzYRH+s1PsQw==,type:str]
  API_USERNAME: ENC[AES256_GCM,data:dSzo1WB+LXSe,iv:ng+9ghG5Pc3RE2I96MSMurrxC9C1sgqCw67xIGQVxdk=,tag:5bPNjxRAYVzXeNZbgiv3GQ==,type:str]
  API_PASSWORD: ENC[AES256_GCM,data:EnpfQg65GQRrrxBzKm4NT9GD4cmhiHxv1WfFmTRPCio=,iv:RaXaZgmoFsovhWzJsKVzzGoDZpWoeDLMrI17D+D6MwM=,tag:PkcCfXUfsH1f4AGRXUO8og==,type:str]
  DASHBOARD_USERNAME: ENC[AES256_GCM,data:VSzcmOREkWTSOIyZ,iv:d7J29OO8q4q/vUb/n42/932LPmUVFTKXJrhmFZibvXA=,tag:eEANxj2ynqs1wjvZG0owTQ==,type:str]
  DASHBOARD_PASSWORD: ENC[AES256_GCM,data:Rbsv7CoYwK9shSWrcw21BWkVppNq/gqbZHkAY20EHbc=,iv:iD39h2JHxB13cLGNXJoQzcxOX/qdhY4gwDd53W5onEo=,tag:gNDGwm7Ab6xGaaXHI1iX+w==,type:str]
  CLUSTER_KEY: ENC[AES256_GCM,data:bF8swGnySjPeOy4F/nNFmV8nQFOwZOfibGYJPtf9KzI=,iv:1SjljquoomfnCpja75fSv6hoY6HH2ZYqPCfyfmsCKTc=,tag:3+6HZPYAVU/J90UIbccIKA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUlIyeEZtMjU5aTJrZVl3
        OE5aenloVUtEajJHdDNkb2grZTNXUUMvZkJRCjJrbjQwYjhwZzlqZ2QzaDBHZEph
        NEFnRkVMTld1RVNQaGloaHZQVFFPOGsKLS0tIGVHMU9WeTBPREUvQkc0MkNsWEdP
        YjVJeXVmVktmUDhwbURpeFFTRmxqU3MKghZb9h+1fD9W8VUJ9HsuAYzsCYwIYGcF
        sTrfwins2iXXGVzEkl1uSs3TTxTIww5ncol4K0q0ZvnKDbpCkLwliQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T19:05:31Z"
  mac: ENC[AES256_GCM,data:WrfUUUv0o81q+7D1FA9w9l5aPqA4hdoIVA/BC905t+GCMNLsVm8XBz0P1MMOEK9fZl8IjnjJr5pD2gwzvB4jU1ezO7eLlrlHF98vXo4hY1c9Vgp0rTgQZcsVvspufdlvN6ydSWuyNhZkJeAofClP4UF6RRm/c9iJe0QvnowAT7A=,iv:4hwe3mCUpUy3Z0kpiiANM7jq8IoRHYwvPrvNg0bUQos=,tag:CEp+5ROmLzetTT2YSNwbng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
