# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-software-showcase
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:S+lYvaTkv7oLAMHGcOwLFPdgMv5sf+t51Evtd/9oJb443vWpjNZ/68yv5XbGaiiuLDNtZd2xn9PGPano1UWUKvw0uKsuWphBNwN9gpKUxK3uzCVdZUzg1jP+Ov4fRLJX0Kqx0tgqCrZ3Opnor2PLWTXcxGcANAEYQFz5G/SStgkc9dFdkdEGDQuoT5ZFaOIi5AMhYAHiQWW86sWqQeBqu1KXECHWM7pZ9qVgBAjErFaR5mjtod4kAdyDjA+CYt9QIoCjyeEHgGjUDIrNszALwuCoeLV/Lz3OgPmOtOh46KgmTBpzIoM=,iv:v10bTGC5kQ+7Ec21w6PaPR4g8bc32EFCaAXRHoDSEdU=,tag:CuwLXrVqGNJQSTTSVinG4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQTdMaWk3K29PYnJkTC9i
        bkthbU8rcWZxcmcwVFltVVZwb05Oc0xCNm1JCnFjYWFmejFmTXRSQk9pRGUwYlp3
        L2xPZnVXRjg0di90ZDN1aU9qRUV1U1UKLS0tIE1MYVpuTDAwOWpNQ2FSQll0T0tq
        dGZKdWI0bTN5UVR2a2phY1FPYVdldDQK3XsnZK/s8wwRDG/JoxHnQUUn5Guez+T4
        lrIFslOwqf4u1iqU6s9WPnpcnekon9jmRP+N43+7f0ezzXDT01nRhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T20:14:35Z"
  mac: ENC[AES256_GCM,data:3pMSmIsifFMUqeCwna3wnFu2isYiVyTattLYTVDHOoHs2JyH9X+9seCITlpZU90FoPFh112hEBQ4EDQJ6bjZOitufAPycCoRxtvmDQd0AH6Y+EvJ3geZpoepV86W4Pn7HD+jZDJNxbUfEB7pvN0KE4eBY69KfRMhnNw6PFAMkJI=,iv:t2BEO/CxotYBV8ZM4ruXg6vZCIrjEOVBUJ64LXWruUI=,tag:hc0zkJivYiFNNTAwdYkPlA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
