apiVersion: v1
kind: Secret
metadata:
  name: sweep-history
  namespace: databases
type: Opaque
stringData:
  SWEEP_WRITER_PASSWORD: ENC[AES256_GCM,data:QGQ6CZstRqrLm808Fhn5gTZ03iCWCFvZ0cZMOb1dGWNmmQ18zCi2sw==,iv:QYGR+9djtoXAFAz7NTHqJxgQhD55pmUtmlS0AxLEnb0=,tag:6EDXQtncrxgSgHirKpperg==,type:str]
  SWEEP_READER_PASSWORD: ENC[AES256_GCM,data:Xg+k1uuo5Saymr5MAyyBmuY9BTLpL9N2TvRz7hpwWizxxD0tBaZEqg==,iv:H+4805PaxOZAogyE5yeQhswSRJJAU4D/XeeZQQdY8k0=,tag:aW0E6hH1IuNMnH1wceKKrg==,type:str]
  WRITER_DSN: ENC[AES256_GCM,data:61FZw5sZJBj4/i8NXturFSlpTiY9Xqh3mExS46q00cljuziCFExN22zxsgUYTYDImkd8DBBSi2Uu04gqaiwajUiZ9btiFgDTvBIxOwEjrM0hjhy3VCLEouRqZVXAA6qGnHjXdLzU0jmJea0CevtLLqXvqDQ3PCh/6Oz/4Q==,iv:qvKTFZx72tSQW7O1io+xO6xu8ImfcrnU8I61nxUYPHs=,tag:bs7HNtbA1FPTTgXwCsCL/A==,type:str]
  READER_DSN: ENC[AES256_GCM,data:RRfuZ6j7qYsQYAR19lOzbtVX50nRKpM8Gkv3vKFbt2eocubBmLCWuKhzj655ZkU46og1w7iZv9THffYc66ldMSPOp/OZ+8z7WSxkUF+PUqOCivMwR+jrQY8MaMuVqXQp0RQ8VAPyq5rzjkZxYgxfIhD5rvLz4U1VkT+MCg==,iv:1uB2ToSMpVPn/4cDCZ4KuID6Uffgmb5n7sE8TCyTc1w=,tag:BHPrpkBE49NOItbhoGpGdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UmVidVFXS2dQWnVMbmQ1
        VTFxWFp4THBXOXZZUzVQRjYybFZibkZoUW0wCkZ4TmM4TS9sU0JoWVBZNUEyQ0tr
        a21pTlVQZmdwOEdBOEZWbm1SNzhZYWsKLS0tIHZ0eStwWjFvblZHM0VXTEdvS2hm
        S20rN2hNU0wyWThvc3hCTnRhY3Vtd1kKZ7RUKmxW1MJmdYz7EQR9JTGhw0WBQ4JO
        jOXH1dFvtMUhX64JAp4PrW/a4A2UpFcDhVGcFjQLjg+gudgHUjhEbg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T09:09:10Z"
  mac: ENC[AES256_GCM,data:IkswTiBX/D/qZj/OlHMD+jiGOAN1DjVQV3gazjsz1ULDZsBndbg3rNyZJeJXp8VqyuduAaJf6aY/PhASa4KBW8Fqdvf6++mkTln8yUnyc2vK87Uof/gLKPKGC3CO++ZJWyQw48+Pt7ugSS/Wsrrze+qYiF5MpHMa061S3DRuM8Y=,iv:A8WVu83WfqeFp/kPJrAvjTTbnIi714MEj6KlB1bOVaE=,tag:891Jp/r2s23X5NBdel0pcg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
