apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mcp-config
  namespace: office
stringData:
  NEXTCLOUD_HOST: ENC[AES256_GCM,data:Imwk7mReWJywDthNwBUYXvBVAf03vA==,iv:fHOh8xEuCAe67eo3a2nu0wEfnmm6Geptw6NS5XxGEZ4=,tag:GhW2UyCxV+jR3Ugamj2gxQ==,type:str]
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:S7PrkVgjV8l87A==,iv:2s1/1AioG1UFgPbcoEFJfibQB1a2xCEDOYI4NmP9fr8=,tag:c04xW+SURAZaxpeubWHB+w==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:Ss7PvKl6ky4qK5EWROQHH9pnr2TLoxg0M8fZqaQa4+EHGAPWu0Ah5j+pyUQFgjZqCeZNpO07yrML2L9RmA5+CH7bqRIudaXo,iv:HUnmWPPzQYvLB0OfB/qm1QZOgwINDLJ8G4C/eQTt61c=,tag:Jcx7cVVMgf7KoE8BDK8eGA==,type:str]
  MCP_DEPLOYMENT_MODE: ENC[AES256_GCM,data:7Hlb+EojXE3i4gUufxnsTZA=,iv:j/eBb+VVcCqbX+CcszrrljrCCJIRAEd+6kPlB1oCzj4=,tag:tkyjEgzFQKH/X7XPky/UnA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeGdpUUYrVVdHUFp1R0cv
        bjRFTDBjMzhBVGh5SHZXSnlHVEJsbGx6R0d3CkRkdWdGWDZGVTUrOHRhcUd1UmNJ
        SHF1amIyUm1wc3B6d0ZPMlJRZlJ6SWsKLS0tIEZ5TEVnTy9CZjJkRXJ5TUVBNjZC
        bGlRYm53TldOcWRjSVc5WHYwSXQzM1EKky3vjGuDtwh2Nc2VPP+d6Y+Uh2ZEIUGV
        M6dNgyeEI//aF/0ekCtGhs/nJWFWMUwuzPI+S+7ljtWGqX9j4UL2zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T19:33:24Z"
  mac: ENC[AES256_GCM,data:ZgBGKFXZu51UM7lO3gquNgKlxpKN4HRMu+Pgl5WnDDPBAPT2CnLCByqaAo+8+rnoLVNMuMSFW/g6dBWBbMKKbo3dLLCrzjp8b+KbyG/hFWGunRVxlsVMBY9z2ZwNsYGGOypuyiVOY8u7hjAEdt5RE4fgIrSsNgyvDXKI0TBHJYQ=,iv:PybPWkctIgPVuxgq0Pj6i3uPXH8T61u3rMqjJaqsfsA=,tag:iBU9nWek1wBLPhPUect2Pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
