apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mcp-config
  namespace: office
stringData:
  NEXTCLOUD_HOST: ENC[AES256_GCM,data:GteQLQCnFI3jlrS2vQlB4W7MgoK5JQ==,iv:UIUWSMxOXr87v/6d+yR6KwjNEqoAQ2rc6ljO8gutaNw=,tag:9ArqJ/9xKSavb6xDVl0zbQ==,type:str]
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:dcpO0ls=,iv:WMkju6yOFl1akkjsECJfrdfjsHc/lqL8+UxmPYPIXfQ=,tag:ZC/J/BAx6aGV37Wvbi+YIw==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:GZ/JHmJOYT8eYCHULDMyQbWGNr38aka5Sn5HQ//fNyETvAop8ZIeEhOVtf3gEKHCIT6kXuSsUe1GYYwQQaQmEwacy8lyZwkm,iv:Ubh9UsDAEkYZ+mESkpQLdrnjsj1+4ce2S7IvFOtNVmw=,tag:1U1Zr0fBzooHQcuEi+W6Mw==,type:str]
  MCP_DEPLOYMENT_MODE: ENC[AES256_GCM,data:Z7c1U6hjtHmViraCTgl95W4=,iv:lCVtf7n1fW0n/jrPXOTZ4KSPenHocWVa1HfTaJ4eMNc=,tag:SbNgfw36+wzbhxQLuTr/Og==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cTFTY25HekRtQUdzNnZo
        WFcyTlM1bjU3Y2RRKzJWVm5YVzg1YzJValU4CnBuSk9hTnFSUDRoanBmMk55c29v
        Q2UzVGVlUmN2U1BwVjlCSlhvOElZeG8KLS0tIHZZU1JJdEFXL2JRYUhhYzllYkxV
        OXBKbDM0cUpyWFZobFRmdG5mdk0zNlEK6zZzb6A/UsxUYryvq+gLkcu9jCbM9W87
        7876b6lqOmyPMHBn1rxpVDmNT8AbR4VWehQBAR5whp+jgIgxO/TRGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T19:25:36Z"
  mac: ENC[AES256_GCM,data:MB/x7/4GRnN+hhUOhh/Emhptv8wNHdQLUUrSVEEpMitv4+LQRRIhIlQmoiXkil6+vM8n/K+YHceD3cDqA3weYqCgvdiGFn08SZMMzv4SQ/MDqBadWiTspmz+Da5LM5tKDtKr2QlIDMnIUcZMla2YQFcj31MOctdhyAqLCpSuS1c=,iv:SacXC9c35+7Qji9RuZIRzivQldHX0LxJAF4b+uVWgP4=,tag:toJX+cH0FLhh7ewKWRzFMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
