---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: office
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
  volumeName: mealie-data
