apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
  namespace: office
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:ScggPhRh/gvO8KnIaJJxZXo7yWgqxb8wOp71LgEcxs8JRp30XWr6mQ==,iv:/Hx6a0pbtubYp37XVXDvQn1FdLy0h1yP8jrF5ls6VpE=,tag:/tgzjpzGOWNNTQZFBzwpig==,type:str]
  #ENC[AES256_GCM,data:sTtaM4ypoynSjgqq6fWsEuKElMozt3KryKqTqiE8aMGPZe3ktr9OzINk0DCLkfc4MWF/F5EFw6HCPEHosqgKlJ3hj2OhEo0=,iv:CrvPYXGd6m9U9Klt47wG7fDorrHzAUWkJbxXWHIi5Bw=,tag:fAbK0VNHhTIjUI1ehAoQiA==,type:comment]
  #ENC[AES256_GCM,data:wyP8XZHptsOaGTCLHEqKQYwEuj8b7I0gqCUqBYR3o1LPZHqy4tdU5URdx5qlXgICl0Vigva4zNu2/yTjxWNYN50PWsXwNI9n,iv:PVn4o8R+B0WXs87Vcmuhk6kvArUJprvkMFOnPuNeNgY=,tag:FpjjHlgVWOFen0w/8mGsNA==,type:comment]
  #ENC[AES256_GCM,data:S+YQfU3c+QyuUiaIwgei7cauAjmluK1+4QS16KEBYbcOm+1OhmGwPjJQlc44MuuJM1mt/c06XPHPhC2WcexIsIcF7Fo=,iv:buf3RRBZ09N87RSLKeRbhtkC30gnF1sqZOPKqITWjvg=,tag:hUxm0qAYewOKcYqJQNL9jQ==,type:comment]
  #ENC[AES256_GCM,data:Q3khHCjmsQK481KX4NviqpCctR9kkyFI+S2V0dfxmbIKZJQ9dQVSps8iaSa9rhWRFbj2LWRlVgqUlh1fUyY=,iv:dz5MCjF1sLfY4SvlKgxZ2hQbleeuIOLhboD2Q3a6hSY=,tag:Dz2dqHQZMDlv2F6Q85IC0Q==,type:comment]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:N0i4H3jPK/7waG6MgDBw5ov/z4Odxi9K4Krz1kVXoxU8/Ph5x5Ot63tAcg==,iv:ZZ0vJ9dJIvGtc77wowuNGQu11LEucWJCqO+JqmdrUAA=,tag:GcuneldsgaOP8kdbU4LjWw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:g2JCQI9/padR3v3wwO+eqt3oHcdjvVuXONpNo2fOm/wDgAswEddH+/piy7WvNS+ER/cwQGCpmQ39bOf+c/G+ezlpH7kWINwf1ZMKbG8qFsdZk1SnZBSj6oB+dpxnVGM8qss0itfuzzLDrk9jsGFz5cbwZe7K3X6ObORHfgBRZjc=,iv:z7oqPLnWtl4u+6M2EYcegW3NGMYGjJFa9TFiksD6C1A=,tag:ASBMY8bjwM+DVNUTtbF/aQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArR01PYldQN1B3RXlwdngr
        Mmh1dnl1OGZrRy9hRUtaSzh3blk5bWpJTHdvCmpKeXpyeDlDU3h6b2NSemFQcmJC
        VHhoN0F0WlJJQ1FGcW11NTlEcmNQOEkKLS0tIENtWHFGeCtEQWJoSUhUMnkzK2xX
        ZFZ2T01uTWdoSktSWUtBSy9NaUhyczQKshEHoT61I7KCaK2v38/wZ7E0JcX/QRWl
        +feL8ieEg7SNOYnnpvMo4uG/g3LIBuboXuxxjN/SGIhPoKXGJjUWuw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T08:34:47Z"
  mac: ENC[AES256_GCM,data:pDe6A0RaxtLprNOKX76viURybJpJ5pxfdu6/R5vGIAIAskus0pald7IDuZR1fzjgBQp3zDCPMqetCkUBIy8J88aG01ttdH5OrfZSAx/GPOAcYFIolRCHXb95rDCJ/k0AQ6ZpSrq7d6Jtr4lz0eY94N6ctk8QkK0gD3syoBwO7r0=,iv:CqwkEPWh5Vek0x22LmNaoyYfIrabEC6Qtqwqr/UCCBY=,tag:yZNuQI/jkE9POXlkDwBuSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
