apiVersion: v1
kind: Secret
metadata:
  name: mealie-shopping-sync
  namespace: office
type: Opaque
stringData:
  MEALIE_TOKEN: ENC[AES256_GCM,data:5aG6ed99wGohENEBW1VGlhdpJ0raA6l74UUUy0M4vMm1SvXJOcJxgfCHcC8VUwBe8CLEnL0uqjDvBGrFjEm8JeTb2zPCc+3xnpEBO8qjWi5yi2Es8xCuOUTSGJ2P0sF5b3vy6qVNVm36ZM1CnN6EylrcYBwvkZlWgiTXf9AhoMQUpC5lWgsjb4Qx3AZWhDT7Gq8zuIWTPS7YmpLXI6AqjGC6kqFNfaWGXLr1POCNOzMfzwxgSdGdkHiOnl5WU6oKumAzFFHXcI+pIt+tXbyc6B6FeUVV09UdVS2sDaO5wAYTDLzP5hE4mc0GiYZYjsAwwoXRWoJzxDfytC0dgphAYH1YKw==,iv:uKdIDKdyVqTYPI5qkliwM+YZBsE/awPta3JKyRBC1Ao=,tag:AC7/iQ/nPPKK9zhXDiejXA==,type:str]
  HA_TOKEN: ENC[AES256_GCM,data:p/SB+4ys5ZRKGIVBuhmxEeSOuHoj/uoRcxLHTdAgIJmHNwG4QwdoMyOMY3+4fuQQpEtqYttRQriwswAgH3q1ykLZYO3ikIIeXEsOmlfMRg5hX739euDD+pqC0JYSC6ofh7QLgjcHQv3ybQmJxMT5vnwyVr/z5T3ZBH2u6D1kGXyrnwVc7ze/lOWD9LKpkGE//vptJnxCrdbUnw9+gH8WpAbwA/8cMTqS3ZBBm1Qhrfpfhi/+eo3p,iv:uu7jBXi0Dh9D2z9h9H2yh+qzKgJSeQK0e+T35rmMo7w=,tag:nHmJ3WTa7ICFgijvgANqBA==,type:str]
  HA_TODO_ENTITY: ENC[AES256_GCM,data:VTfRHIYucGwxLL7srIN36i3XSxBUXU757wEcoIMf,iv:8VzmpwxG/5dmV04cf9RPjWkoXOTBaHqNazi/xuyScrg=,tag:NiYphZc+MOPJCkMAMgAH4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWTlrSUNKbzFZTCtCSTgv
        ZGFabWNVOEpkTFZYQ2wxaURESWY2Rkt2QmdrClpVeE1LekRxKzRtRnptOFI3c1NF
        dWxIbEVqb0ErbEpPaXFSVVRNNEtEeDgKLS0tIGwwcitpN3kvZndCZDJuWmFESXBB
        Y3dyREVkM0hpMStzVk9BQnlXRXR6TTAKIJz3y5YvyMvB5QFw5rsHMIzXMh9VUKcL
        oR5LPpAY4fcZj/+/n4EzyJk3KViRnnFdjyg74KKU+aJUf+fhOH7mIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T10:46:31Z"
  mac: ENC[AES256_GCM,data:yklm8VRWwLzDFUwsAxIkAVOayG0OetNXK3L9lqKSa3c+GB/MbWbCU2CJFpaP+PkB/aghPHPpvsulXogyA0BaQxXhwAJyfAZo+aPQxbDzxBGV3R4VLvpq+y5EA5Q73vpZc9c+ziPiHQHFfFSQUNEPAfI0R2hR+PVvhKZ4ArkVDBE=,iv:Q5Dj1Vwzv4DGpQ13JIMvO4EAF26xB4+L3rXVk9qqHJ4=,tag:jRINIdndz/mHGEYMxCKQZQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
