#!/usr/bin/env python3
"""Render the operator's sweep board — deterministically, from the DB.

The board is the OUTPUT CONTRACT of the operation sweep: the exact list the
operator defined, in a fixed order, generated by a script rather than by an
LLM synthesizing at the end of a run. Why that matters was proven on
2026-08-16: the orchestrator's prose synthesis sat blocked on a planner
child while every finding was already in Postgres — the operator asked
"when do I get the full board?" and the honest answer was one SQL query.
A deterministic renderer always answers immediately, and a section that
did not report shows as an explicit GAP instead of silently missing.

Sections, in order (the operator's definition):
  1. TIER BOARD    — contextual security tiers (critical/high/medium/low)
                     critical = external-unauth + KEV-exploited + real vuln
                     = the ONLY thing that pages.
  2. CRITICALS     — the genuine-critical list (normally empty).
  3. HIGH          — the operator's reading list (external, not exploited).
  4. SECTIONS      — non-security sections: new vs carried counts + gaps.
  5. SLO/SLI       — latest snapshot per SLO: compliance, burn, budget.
  6. WINDOWS       — next maintenance window + queue warnings.

Usage:
  python3 runbooks/render-board.py                 # newest cycle with findings
  python3 runbooks/render-board.py --cycle <id>    # a specific cycle
  python3 runbooks/render-board.py --json          # machine-readable

DSN comes from SWEEP_PG_DSN (sweep-run.py sets it up); falls back to the
same secret-derived port-forward helper sweep-run uses.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

EXPECTED_SECTIONS = ["health", "security", "version", "doc", "media", "slo"]


def _dsn() -> str | None:
    dsn = os.environ.get("SWEEP_PG_DSN")
    if dsn:
        return dsn
    # Fall back to deriving it the way sweep-run does (needs a port-forward
    # to already exist, or an in-cluster DNS-reachable DSN).
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "sweeprun", REPO / "runbooks" / "sweep-run.py")
        m = importlib.util.module_from_spec(spec)
        sys.modules["sweeprun"] = m
        spec.loader.exec_module(m)
        return m._kubectl_secret_dsn()
    except Exception:
        return None



def _desc(title: str, limit: int = 96) -> str:
    """A short description from a raw finding title: keep the identifier and
    the first clause, drop trailing CVE enumerations and remediation prose."""
    t = re.sub(r"\s+", " ", title.strip())
    # cut at the em-dash remediation tail or a CVE list, whichever comes first
    for sep in (" — CVE-", "; CVE-", " - CVE-"):
        i = t.find(sep)
        if i > 0:
            t = t[:i]
            break
    i = t.find(" — ")
    if i > 40:          # keep short titles whole; trim long remediation tails
        head, tail = t[:i], t[i + 3:]
        t = head + " — " + tail.split(".")[0].split(";")[0]
    return (t[: limit - 1] + "…") if len(t) > limit else t


# An UNBUMPABLE-CVE ESCALATION (F-80128ae8). security-check.py's magnitude rule
# emits a CRITICAL row when no newer upstream tag can fix an image and the
# count is too large to absorb: the remaining options are a variant/base
# switch, a replacement, or a compensating control — a HUMAN DECISION, which
# is the one thing "no action now" must never say. But AR-029's substring
# then tags the row `[AR-029]`/accepted, and the high-tier collapse below
# folded it into "N AR-accepted item(s), awaiting an upstream release — resurface at
# their AR review dates, no action now". Measured 2026-09-22: one row.
#
# The emitter does not (yet) stamp `metadata.escalation`, so the row is
# recognised by BOTH: the marker when present (it wins), and the title shape
# the magnitude branch has carried since 2026-07-31 ("no bump can fix this …
# Decide: …"). Keying on the shape is deliberate and stated here: when
# security-check.py gains the marker, the shape keeps working meanwhile.
ESCALATION_TITLE_MARKS = ("no bump can fix this", "Decide:")


def is_escalation(row: dict) -> bool:
    """True for a row that is a decision request, whatever its tier or
    severity — see the block above for the two keys."""
    meta = row.get("meta") or {}
    if str(meta.get("escalation", "")).strip().lower() in ("true", "1", "yes"):
        return True
    title = str(row.get("title") or "")
    return all(mark in title for mark in ESCALATION_TITLE_MARKS)


def planned_findings(cur=None) -> dict:
    """finding_id -> (plan_id, window) for every ACTIVE maintenance plan that
    carries a `security_ref`. Operator rule (2026-08-17): a finding already
    planned into a window is handled by the window pipeline — the sweep
    re-listing it is noise. Only an EXACT security_ref match hides an item;
    component-name guessing would hide things the plans don't actually cover.
    Executed/superseded plans don't count — their ref must resurface.

    A plan file's `security_ref` is frozen at authoring time, but `finding_id`
    is derived from the fingerprint and is re-derived whenever the identity
    function changes (2026-08-18 renamed 179 of them). An exact-match-only
    lookup therefore stops hiding a planned finding the moment it is renamed,
    and the item resurfaces as un-planned noise — the exact failure the
    operator rule above exists to prevent. When a cursor is available we also
    register each ref under the id that currently owns it, resolved through
    `metadata.prior_finding_ids`.
    """
    out = {}
    try:
        import yaml
        for p in (REPO / "runbooks" / "maintenance" / "plans").glob("*.md"):
            if p.name == "README.md":
                continue
            try:
                fm = yaml.safe_load(p.read_text().split("---", 2)[1]) or {}
            except Exception:
                continue
            if fm.get("status") in ("executed", "superseded"):
                continue
            ref = fm.get("security_ref")
            if ref and str(ref).startswith("F-"):
                out[str(ref)] = (fm.get("plan_id") or p.stem,
                                 fm.get("window") or "unscheduled")
    except Exception:
        pass  # board must render regardless; no plans-index -> nothing hidden

    if cur is not None and out:
        # Additive only: the frozen ref keeps its entry, so a ref that was
        # never renamed behaves exactly as before.
        #
        # The SAVEPOINT is not optional. By the time this runs, collect() has
        # already issued queries on a non-autocommit connection, so a
        # transaction is open — and in psycopg3 a failed statement poisons it.
        # A bare try/except would swallow the original error and then every
        # later cur.execute() in collect() would raise InFailedSqlTransaction,
        # turning a best-effort lookup into a total board failure: the exact
        # opposite of "never block the board". (The plan-file guard above is
        # genuinely safe bare, because it predates any DB work.)
        try:
            with cur.connection.transaction():
                cur.execute(
                    "SELECT finding_id, metadata->'prior_finding_ids' AS priors "
                    "  FROM sweep_findings "
                    " WHERE metadata->'prior_finding_ids' ?| %s "
                    # Only LIVE rows may inherit a plan's ref. Nothing enforces
                    # alias uniqueness, so without this one plan ref could hide
                    # several findings — and on a board whose whole job is
                    # surfacing unhandled work, over-hiding is the dangerous
                    # direction and it fails silently.
                    "   AND resolved_at IS NULL",
                    (list(out),),
                )
                rows = cur.fetchall()
            claimed: dict[str, str] = {}
            for row in rows:
                cur_id = row[0] if not isinstance(row, dict) else row["finding_id"]
                priors = row[1] if not isinstance(row, dict) else row["priors"]
                if not isinstance(priors, list):
                    continue  # a scalar/object metadata value is not an alias list
                for old_id in priors:
                    if old_id not in out or cur_id in out:
                        continue
                    if old_id in claimed:
                        print(f"warning: plan ref {old_id} is claimed by two live "
                              f"findings ({claimed[old_id]}, {cur_id}) — not hiding "
                              f"either; check for a duplicate finding",
                              file=sys.stderr)
                        out.pop(claimed[old_id], None)
                        continue
                    claimed[old_id] = cur_id
                    out[cur_id] = out[old_id]
        except Exception as e:  # noqa: BLE001
            print(f"warning: plan-ref alias lookup failed ({type(e).__name__}); "
                  f"renamed findings may show as un-planned", file=sys.stderr)
    return out

def section_evidence(d: dict, s: str) -> str | None:
    """Which durable artifact says section `s` reported this cycle, or None.

    Checked in evidence order — rows, the writer's own completion record, SLO
    snapshots, the reconcile's declaration — so the board can say WHY a
    clean section counts as reported. "No findings" and "no report" are
    different answers (F-bfb9ec80), and only the last one is a gap.
    """
    if d.get("sections", {}).get(s) is not None:
        return "rows"
    if s in (d.get("completed") or {}):
        return "completed"
    if s == "slo" and (d.get("slo_snapshots_in_cycle") or 0) > 0:
        return "snapshots"
    if s in (d.get("ran") or set()):
        return "declared"
    return None


def section_reported(d: dict, s: str) -> bool:
    return section_evidence(d, s) is not None


def section_line(d: dict, s: str) -> str:
    ev = section_evidence(d, s)
    inc = (d.get("incomplete") or {}).get(s)
    suffix = f" — coverage INCOMPLETE ({inc})" if inc else ""
    if ev == "rows":
        info = d["sections"][s]
        return f"{info['new']} new, {info['open']} open{suffix}"
    if ev == "completed":
        c = d["completed"][s] or {}
        at = str(c.get("at") or "")[:16]
        return (f"ran clean — 0 findings (section closed with verdict "
                f"{c.get('verdict') or '?'}{' at ' + at if at else ''}){suffix}")
    if ev == "snapshots":
        return (f"ran clean — 0 findings ({d['slo_snapshots_in_cycle']} SLO "
                f"snapshot(s) written this cycle){suffix}")
    if ev == "declared":
        return f"ran clean — 0 new (run declared at reconcile){suffix}"
    return "**DID NOT REPORT** — gap, not a pass"


def collect(cur, cycle_id: str | None) -> dict:
    if not cycle_id:
        cur.execute(
            """SELECT c.cycle_id FROM sweep_cycles c
               JOIN sweep_findings f ON f.cycle_id = c.cycle_id
               GROUP BY c.cycle_id, c.started_at
               ORDER BY c.started_at DESC LIMIT 1""")
        row = cur.fetchone()
        if not row:
            raise SystemExit("no cycle with findings found")
        cycle_id = row[0]

    cur.execute(
        "SELECT started_at, finished_at, verdict FROM sweep_cycles WHERE cycle_id = %s",
        (cycle_id,))
    started, finished, verdict = cur.fetchone()

    out = {"cycle_id": str(cycle_id), "started_at": str(started),
           "finished": bool(finished), "db_verdict": verdict}

    # Three per-section run records live on the cycle row's notes JSON, and
    # "did this section report?" is answered from ALL of them (F-bfb9ec80):
    #   completed[section] — written by the section's OWN FindingsWriter at
    #                        close(verdict=…): the section finished, whatever
    #                        it emitted. The durable artifact for a clean run.
    #   ran                — declared by the orchestrator at reconcile from
    #                        what it believes ran; authoritative for auto-close
    #                        scope, but a belief, and on 2026-09-17 it left out
    #                        two sections that had in fact run.
    #   incomplete[section]— the section ran but vetoed auto-close (coverage
    #                        gap); rendered as a suffix, never as a gap.
    # Row-count alone cannot answer the question: a clean section writes no
    # rows, and an agent section files its rows under `plan` by rule.
    cur.execute("SELECT notes FROM sweep_cycles WHERE cycle_id = %s", (cycle_id,))
    row = cur.fetchone()
    notes: dict = {}
    if row and row[0]:
        try:
            parsed = json.loads(row[0])
            notes = parsed if isinstance(parsed, dict) else {}
        except (ValueError, TypeError):
            notes = {}
    ran: set[str] = set(notes.get("ran") or []) if isinstance(notes.get("ran"), list) else set()
    out["ran"] = ran
    out["completed"] = notes["completed"] if isinstance(notes.get("completed"), dict) else {}
    out["incomplete"] = notes["incomplete"] if isinstance(notes.get("incomplete"), dict) else {}
    # Resolved here, not in render(), because this is where the cursor is —
    # the plan refs need a DB lookup to follow renamed finding ids.
    out["planned"] = planned_findings(cur)

    # 1+2+3 — contextual tiers over OPEN findings of this cycle
    cur.execute(
        """SELECT COALESCE(metadata->>'risk_tier','untiered') AS tier, count(*)
           FROM sweep_findings WHERE cycle_id=%s AND status != 'resolved'
           GROUP BY 1""", (cycle_id,))
    out["tiers"] = dict(cur.fetchall())

    cur.execute(
        """SELECT finding_id, title FROM sweep_findings
           WHERE cycle_id=%s AND status!='resolved'
             AND metadata->>'risk_tier'='critical' ORDER BY finding_id""",
        (cycle_id,))
    out["criticals"] = [{"id": f, "title": t} for f, t in cur.fetchall()]

    # Escalations (F-80128ae8) — tier-independent. The SQL is a cheap SUPERSET
    # (marker present, or the first title mark); is_escalation() is the
    # authority, so the split is decided in one place and is testable.
    cur.execute(
        """SELECT finding_id, title,
                  COALESCE(metadata->>'risk_tier','untiered') AS tier,
                  severity, metadata->>'escalation' AS esc,
                  COALESCE(metadata->>'subsection','') AS sub
           FROM sweep_findings
           WHERE cycle_id=%s AND status!='resolved'
             AND (COALESCE(metadata->>'escalation','') <> ''
                  OR title LIKE '%%no bump can fix this%%')
           ORDER BY finding_id""",
        (cycle_id,))
    cand = [{"id": f, "title": t, "tier": tier, "severity": sev, "sub": sub,
             "meta": {"escalation": esc}}
            for f, t, tier, sev, esc, sub in cur.fetchall()]
    out["escalations"] = [r for r in cand if is_escalation(r)]
    esc_ids = {r["id"] for r in out["escalations"]}
    # rendered ONCE, as a decision request — never also as a bare critical
    out["criticals"] = [c for c in out["criticals"] if c["id"] not in esc_ids]

    cur.execute(
        """SELECT finding_id, title, metadata->>'exposure' AS exposure,
                  COALESCE(metadata->>'subsection','') AS sub, severity
           FROM sweep_findings
           WHERE cycle_id=%s AND status!='resolved'
             AND metadata->>'risk_tier'='high' ORDER BY title""",
        (cycle_id,))
    rows = [{"id": f, "title": t, "exposure": e, "sub": sub, "severity": sev}
            for f, t, e, sub, sev in cur.fetchall()]
    # An escalation is a decision request, not an accepted risk — it must
    # never fold into the AR count line below, whatever severity the AR
    # suppression stamped on it.
    rows = [r for r in rows if r["id"] not in esc_ids]
    # Operator rule (2026-08-17): an ACCEPTED-risk finding is by definition
    # acknowledged — "I don't need to see the accepted AR if there is no
    # upstream fix yet." They collapse to one count line instead of individual
    # entries; the AR's own review date is what resurfaces them.
    out["high"] = [r for r in rows
                   if r["severity"] != "accepted"
                   and not r["title"].lstrip().startswith("[AR-")]
    out["high_accepted"] = len(rows) - len(out["high"])

    # 3b — the numbered action list needs: new findings outside security,
    # and the medium tier grouped by subsection so 144 rows become a few lines.
    # severity filter: `clean` rows are pass confirmations, `accepted` rows
    # are operator-acknowledged ARs — neither is an action item (the 44
    # "SOP … compliant" doc rows of cycle b2410887 rendered as 44 MEDIUMs).
    # cycle_id alone UNDER-COUNTS a cycle's findings, and silently. Findings a
    # specialist hand-authors via `policy-cli.py finding add` — which is what the
    # P4.1.6 contract REQUIRES for any recommendation implying a state change —
    # are pinned by _policy_cli_cycle() to a sentinel 'policy-cli' cycle row on
    # purpose ("a real sweep cycle would be a lie about provenance"). Both
    # designs are defensible; their intersection was the bug. Keying the action
    # list on cycle_id therefore dropped EVERY agent-written row: measured on
    # cycle 0e37c7d3 (2026-09-11), 17 of 17 findings authored by that cycle's
    # own six specialists rendered nowhere, while the board still looked
    # complete — worse than the 2026-08-16 block, which at least announced
    # itself by producing no board at all.
    #
    # So scope by AUTHORSHIP WINDOW as well as cycle_id: a row first seen
    # between this cycle's start and its end (now, if still running) was
    # authored by this cycle whichever row it hangs off. Provenance is left
    # alone — metadata.authored_by still distinguishes hand-authored from
    # script-emitted.
    cur.execute(
        """SELECT finding_id, section, title, severity FROM sweep_findings
           WHERE status='new' AND section != 'security'
             AND severity NOT IN ('clean', 'accepted')
             AND (
                   cycle_id = %(cid)s
                OR first_seen >= (SELECT started_at FROM sweep_cycles WHERE cycle_id = %(cid)s)
             )
             AND first_seen < COALESCE(
                   -- Bound by the NEXT cycle's start, not this cycle's
                   -- finished_at: the reconcile stamps finished_at mid-run, so a
                   -- row authored after it (a late hand-authored finding, a
                   -- follow-up fix) still belongs to THIS cycle. Using
                   -- finished_at dropped such rows with no signal — it happened
                   -- to pass on 0e37c7d3 by a 55-second margin.
                   (SELECT MIN(started_at) FROM sweep_cycles
                     WHERE started_at > (SELECT started_at FROM sweep_cycles
                                          WHERE cycle_id = %(cid)s)),
                   'infinity'::timestamptz)
           ORDER BY section, finding_id""", {"cid": cycle_id})
    out["new_other"] = [{"id": f, "section": sec, "title": t, "severity": sev}
                        for f, sec, t, sev in cur.fetchall()]
    cur.execute(
        """SELECT COALESCE(metadata->>'subsection', 'other') AS grp, count(*)
           FROM sweep_findings
           WHERE cycle_id=%s AND status!='resolved'
             AND metadata->>'risk_tier'='medium'
           GROUP BY 1 ORDER BY 2 DESC""", (cycle_id,))
    groups = [(g, n) for g, n in cur.fetchall()]
    # an escalation at medium tier is already rendered as a decision request;
    # take it out of its subsection's count so it is not also "1 internal
    # finding — maintenance-window queue"
    for r in out["escalations"]:
        if r.get("tier") == "medium":
            grp = r.get("sub") or "other"
            groups = [(g, n - 1 if g == grp else n) for g, n in groups]
    out["medium_groups"] = [(g, n) for g, n in groups if n > 0]

    # 4 — per-section counts + explicit gaps
    cur.execute(
        """SELECT section,
                  count(*) FILTER (WHERE status='new')       AS new,
                  count(*) FILTER (WHERE status!='resolved') AS open
           FROM sweep_findings WHERE cycle_id=%s GROUP BY section""",
        (cycle_id,))
    sect = {s: {"new": n, "open": o} for s, n, o in cur.fetchall()}
    out["sections"] = sect
    # slo writes snapshots, not findings, when clean — count the snapshots in
    # the cycle's own window before calling it a gap (the auto-close lesson).
    # Same bounds as the action-list query above: from this cycle's start to
    # the NEXT cycle's start. finished_at is stamped by the reconcile mid-run
    # and is not a ceiling anything else in this file trusts.
    cur.execute(
        """SELECT count(*) FROM slo_snapshots s
           WHERE s.taken_at >= (SELECT started_at FROM sweep_cycles WHERE cycle_id = %(cid)s)
             AND s.taken_at < COALESCE(
                   (SELECT MIN(started_at) FROM sweep_cycles
                     WHERE started_at > (SELECT started_at FROM sweep_cycles
                                          WHERE cycle_id = %(cid)s)),
                   'infinity'::timestamptz)""", {"cid": cycle_id})
    row = cur.fetchone()
    out["slo_snapshots_in_cycle"] = int(row[0]) if row and row[0] is not None else 0
    out["gaps"] = [s for s in EXPECTED_SECTIONS if not section_reported(out, s)]

    # 5 — latest snapshot per SLO
    cur.execute(
        """SELECT DISTINCT ON (slo_name) slo_name, compliance_pct, target_pct,
                  burn_rate_1h, budget_remaining_pct, taken_at
           FROM slo_snapshots ORDER BY slo_name, taken_at DESC""")
    out["slos"] = [
        {"name": n, "compliance": float(cp) if cp is not None else None,
         "target": float(tp) if tp is not None else None,
         "burn_1h": float(b1) if b1 is not None else None,
         "budget_pct": float(bu) if bu is not None else None,
         "taken_at": str(ta)}
        for n, cp, tp, b1, bu, ta in cur.fetchall()]

    return out


def windows() -> dict:
    """Next window + warnings via the reconciler (source of truth)."""
    try:
        r = subprocess.run(
            [sys.executable, str(REPO / "runbooks" / "maintenance-plan.py"), "--json"],
            capture_output=True, text=True, timeout=120)
        d = json.loads(r.stdout)
        nxt = (d.get("next_windows") or [None])[0]
        if isinstance(nxt, dict):
            nxt = nxt.get("slot") or nxt
        return {"next": nxt, "warnings": d.get("warnings", []),
                "status_counts": d.get("plan_status")}
    except Exception as e:  # noqa: BLE001 — the board must render regardless
        return {"error": f"reconciler unavailable: {e}"}


def render(d: dict, w: dict) -> str:
    L: list[str] = []
    tiers = d["tiers"]
    crit = tiers.get("critical", 0)
    L.append(f"# Sweep board — cycle {d['cycle_id'][:8]} · {d['started_at'][:16]}")
    L.append("")
    L.append("## 1 · Tier board (security, contextual)")
    L.append("")
    L.append(f"    critical  {crit:>4}   <- pages operator (external + exploited + vuln)")
    L.append(f"    high      {tiers.get('high', 0):>4}   <- briefing / reading list")
    L.append(f"    medium    {tiers.get('medium', 0):>4}   <- maintenance-window queue")
    L.append(f"    low       {tiers.get('low', 0):>4}   <- weekly batch (policy/hygiene)")
    L.append("")
    L.append("## 2 · Action list (numbered, by importance)")
    L.append("")
    n = 0
    def item(rating, category, desc):
        nonlocal n
        n += 1
        L.append(f"{n:>3}. **[{rating}]** `{category}` — {desc}")

    planned = d.get("planned") or planned_findings()
    # Operational criticals from non-security sections (health, version, ...).
    # They carry no `risk_tier` -- that contextual model is security-only -- so
    # before this they fell into the hardcoded MEDIUM bucket below, and a
    # cluster component actively degrading NOW ranked beneath a grouped doc
    # line. Stored severity is the authority for non-security sections.
    ops_criticals = [f_ for f_ in d.get("new_other", [])
                     if f_.get("severity") == "critical"]
    escalations = d.get("escalations") or []
    if not d["criticals"] and not ops_criticals:
        starts = "DECISION" if escalations else "HIGH"
        L.append(f"*(no CRITICAL items — nothing pages; list starts at {starts})*")
        L.append("")
    for c in d["criticals"]:
        # criticals are NEVER hidden — they page; a plan is annotated, not a veil
        note = ""
        if c["id"] in planned:
            pid, win = planned[c["id"]]
            note = f"  *(planned: {pid} @ {win})*"
        item("CRITICAL", "security/exposed+exploited", _desc(c["title"]) + note)
    for f_ in ops_criticals:
        # never collapsed -- same contract as the security criticals above
        item("CRITICAL", f"{f_['section']}/critical", _desc(f_["title"]))
    # Decision requests (F-80128ae8): an unbumpable-CVE escalation is rendered
    # as exactly that — one numbered line each, never collapsed, never folded
    # into the AR-accepted "no action now" count, whatever tier or severity
    # the suppression left on it. The decision named here is the emitter's:
    # variant/base switch, replacement, or a compensating control.
    for e in escalations:
        note = ""
        if e["id"] in planned:
            pid, win = planned[e["id"]]
            note = f"  *(planned: {pid} @ {win})*"
        item("DECISION", f"security/escalation/{e.get('tier') or 'untiered'}",
             _desc(e["title"]) + " — DECISION REQUESTED: variant/base switch, "
             "replacement, or a compensating control; not an accepted risk" + note)
    high_planned = [h for h in d["high"] if h["id"] in planned]
    for h in [h for h in d["high"] if h["id"] not in planned]:
        # category: real exposure when recorded; else derive from subsection
        # (git-history findings are repo-exposure, not a served endpoint) —
        # never default to a specific-sounding label the data doesn't support.
        exp = h.get("exposure")
        sub = (h.get("sub") or "").replace("s3_git_history", "git-history") \
                                  .replace("s4_cve_check", "cve")
        cat = "security/" + (exp or sub or "untagged")
        item("HIGH", cat, _desc(h["title"]))
    if high_planned:
        wins = sorted(planned[h["id"]][1] for h in high_planned)
        item("HIGH", "security/planned",
             f"{len(high_planned)} item(s) already planned into maintenance "
             f"windows (earliest {wins[0]}) — handled by the window pipeline")
    if d.get("high_accepted"):
        item("HIGH", "security/accepted",
             f"{d['high_accepted']} AR-accepted item(s), no upstream fix yet — "
             "resurface at their AR review dates, no action now")
    # Non-security new findings: individually while a section's list is
    # readable, but collapse to one grouped line beyond that — same contract
    # as the security medium groups below (medium-queue items are groupable;
    # 44 individual `doc/new` rows on the 2026-08-18 board proved the bypass).
    _by_sec: dict[str, list] = {}
    for f_ in d.get("new_other", []):
        if f_.get("severity") == "critical":
            continue      # already emitted individually as CRITICAL above
        _by_sec.setdefault(f_["section"], []).append(f_)
    for sec in sorted(_by_sec):
        items_ = _by_sec[sec]
        if len(items_) > 5:
            item("MEDIUM", f"{sec}/new",
                 f"{len(items_)} new finding(s) — grouped; see the {sec} "
                 f"section report for the list")
        else:
            for f_ in items_:
                item("MEDIUM", f"{sec}/new", _desc(f_["title"]))
    for grp, cnt in d.get("medium_groups", []):
        item("MEDIUM", f"security/{grp}",
             f"{cnt} internal finding(s) — maintenance-window queue")
    low = d["tiers"].get("low", 0)
    if low:
        item("LOW", "policy/hygiene",
             f"{low} policy finding(s) (floating tags, drift, stale charts) — weekly batch")
    L.append("")
    L.append("## 3 · Sections")
    L.append("")
    for s in EXPECTED_SECTIONS:
        L.append(f"- `{s}`: {section_line(d, s)}")
    L.append("")
    L.append("## 4 · SLO / SLI")
    L.append("")
    if d["slos"]:
        L.append("| SLO | compliance | target | burn 1h | budget left | as of |")
        L.append("|---|---|---|---|---|---|")
        for s in d["slos"]:
            comp = "?" if s["compliance"] is None else f"{s['compliance']:.3f}%"
            burn = "?" if s["burn_1h"] is None else f"{s['burn_1h']:.2f}"
            bud = "?" if s["budget_pct"] is None else f"{s['budget_pct']:.1f}%"
            mark = " ⚠" if (s["burn_1h"] or 0) > 1 else ""
            L.append(f"| {s['name']} | {comp}{mark} | {s['target']}% | {burn} "
                     f"| {bud} | {s['taken_at'][:16]} |")
    else:
        L.append("no snapshots — SLO section did not run (gap, not a pass)")
    L.append("")
    L.append("## 5 · Maintenance windows")
    L.append("")
    if "error" in w:
        L.append(f"- {w['error']}")
    else:
        L.append(f"- next: {w.get('next')}")
        for warn in (w.get("warnings") or []):
            L.append(f"- ⚠ {warn}")
        if not (w.get("warnings") or []):
            L.append("- reconciler: 0 warnings")
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cycle", default=None)
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    dsn = _dsn()
    if not dsn:
        print("no DSN (set SWEEP_PG_DSN or run under sweep-run)", file=sys.stderr)
        return 2
    import psycopg
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:
        data = collect(cur, args.cycle)
    w = windows()
    if args.json:
        print(json.dumps({"board": data, "windows": w}, indent=2, default=str))
    else:
        print(render(data, w))
    return 0


if __name__ == "__main__":
    sys.exit(main())
