#!/usr/bin/env python3
"""Render the operator's sweep board — deterministically, from the DB.

The board is the OUTPUT CONTRACT of the operation sweep: the exact list the
operator defined, in a fixed order, generated by a script rather than by an
LLM synthesizing at the end of a run. Why that matters was proven on
2026-08-16: the orchestrator's prose synthesis sat blocked on a planner
child while every finding was already in Postgres — the operator asked
"when do I get the full board?" and the honest answer was one SQL query.
A deterministic renderer always answers immediately, and a section that
did not report shows as an explicit GAP instead of silently missing.

Sections, in order (the operator's definition):
  1. TIER BOARD    — contextual security tiers (critical/high/medium/low)
                     critical = external-unauth + KEV-exploited + real vuln
                     = the ONLY thing that pages.
  2. CRITICALS     — the genuine-critical list (normally empty).
  3. HIGH          — the operator's reading list (external, not exploited).
  4. SECTIONS      — non-security sections: new vs carried counts + gaps.
  5. SLO/SLI       — latest snapshot per SLO: compliance, burn, budget.
  6. WINDOWS       — next maintenance window + queue warnings.

Usage:
  python3 runbooks/render-board.py                 # newest cycle with findings
  python3 runbooks/render-board.py --cycle <id>    # a specific cycle
  python3 runbooks/render-board.py --json          # machine-readable

DSN comes from SWEEP_PG_DSN (sweep-run.py sets it up); falls back to the
same secret-derived port-forward helper sweep-run uses.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

EXPECTED_SECTIONS = ["health", "security", "version", "doc", "media", "slo"]


def _dsn() -> str | None:
    dsn = os.environ.get("SWEEP_PG_DSN")
    if dsn:
        return dsn
    # Fall back to deriving it the way sweep-run does (needs a port-forward
    # to already exist, or an in-cluster DNS-reachable DSN).
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "sweeprun", REPO / "runbooks" / "sweep-run.py")
        m = importlib.util.module_from_spec(spec)
        sys.modules["sweeprun"] = m
        spec.loader.exec_module(m)
        return m._kubectl_secret_dsn()
    except Exception:
        return None



def _desc(title: str, limit: int = 96) -> str:
    """A short description from a raw finding title: keep the identifier and
    the first clause, drop trailing CVE enumerations and remediation prose."""
    t = title.strip()
    # cut at the em-dash remediation tail or a CVE list, whichever comes first
    for sep in (" — CVE-", "; CVE-", " - CVE-"):
        i = t.find(sep)
        if i > 0:
            t = t[:i]
            break
    i = t.find(" — ")
    if i > 40:          # keep short titles whole; trim long remediation tails
        head, tail = t[:i], t[i + 3:]
        t = head + " — " + tail.split(".")[0].split(";")[0]
    return (t[: limit - 1] + "…") if len(t) > limit else t

def collect(cur, cycle_id: str | None) -> dict:
    if not cycle_id:
        cur.execute(
            """SELECT c.cycle_id FROM sweep_cycles c
               JOIN sweep_findings f ON f.cycle_id = c.cycle_id
               GROUP BY c.cycle_id, c.started_at
               ORDER BY c.started_at DESC LIMIT 1""")
        row = cur.fetchone()
        if not row:
            raise SystemExit("no cycle with findings found")
        cycle_id = row[0]

    cur.execute(
        "SELECT started_at, finished_at, verdict FROM sweep_cycles WHERE cycle_id = %s",
        (cycle_id,))
    started, finished, verdict = cur.fetchone()

    out = {"cycle_id": str(cycle_id), "started_at": str(started),
           "finished": bool(finished), "db_verdict": verdict}

    # 1+2+3 — contextual tiers over OPEN findings of this cycle
    cur.execute(
        """SELECT COALESCE(metadata->>'risk_tier','untiered') AS tier, count(*)
           FROM sweep_findings WHERE cycle_id=%s AND status != 'resolved'
           GROUP BY 1""", (cycle_id,))
    out["tiers"] = dict(cur.fetchall())

    cur.execute(
        """SELECT finding_id, title FROM sweep_findings
           WHERE cycle_id=%s AND status!='resolved'
             AND metadata->>'risk_tier'='critical' ORDER BY finding_id""",
        (cycle_id,))
    out["criticals"] = [{"id": f, "title": t} for f, t in cur.fetchall()]

    cur.execute(
        """SELECT finding_id, title, metadata->>'exposure' AS exposure,
                  COALESCE(metadata->>'subsection','') AS sub
           FROM sweep_findings
           WHERE cycle_id=%s AND status!='resolved'
             AND metadata->>'risk_tier'='high' ORDER BY title""",
        (cycle_id,))
    out["high"] = [{"id": f, "title": t, "exposure": e, "sub": sub}
                   for f, t, e, sub in cur.fetchall()]

    # 3b — the numbered action list needs: new findings outside security,
    # and the medium tier grouped by subsection so 144 rows become a few lines.
    cur.execute(
        """SELECT finding_id, section, title FROM sweep_findings
           WHERE cycle_id=%s AND status='new' AND section != 'security'
           ORDER BY section, finding_id""", (cycle_id,))
    out["new_other"] = [{"id": f, "section": sec, "title": t}
                        for f, sec, t in cur.fetchall()]
    cur.execute(
        """SELECT COALESCE(metadata->>'subsection', 'other') AS grp, count(*)
           FROM sweep_findings
           WHERE cycle_id=%s AND status!='resolved'
             AND metadata->>'risk_tier'='medium'
           GROUP BY 1 ORDER BY 2 DESC""", (cycle_id,))
    out["medium_groups"] = [(g, n) for g, n in cur.fetchall()]

    # 4 — per-section counts + explicit gaps
    cur.execute(
        """SELECT section,
                  count(*) FILTER (WHERE status='new')       AS new,
                  count(*) FILTER (WHERE status!='resolved') AS open
           FROM sweep_findings WHERE cycle_id=%s GROUP BY section""",
        (cycle_id,))
    sect = {s: {"new": n, "open": o} for s, n, o in cur.fetchall()}
    out["sections"] = sect
    out["gaps"] = [s for s in EXPECTED_SECTIONS if s not in sect]
    # slo writes snapshots, not findings, when clean — check snapshots in the
    # cycle's own time window before calling it a gap (the auto-close lesson).
    if "slo" in out["gaps"]:
        cur.execute(
            """SELECT 1 FROM slo_snapshots s, sweep_cycles c
               WHERE c.cycle_id=%s AND s.taken_at >= c.started_at
                 AND s.taken_at <= COALESCE(c.finished_at, now()) LIMIT 1""",
            (cycle_id,))
        if cur.fetchone():
            out["gaps"].remove("slo")
            sect["slo"] = {"new": 0, "open": 0}

    # 5 — latest snapshot per SLO
    cur.execute(
        """SELECT DISTINCT ON (slo_name) slo_name, compliance_pct, target_pct,
                  burn_rate_1h, budget_remaining_pct, taken_at
           FROM slo_snapshots ORDER BY slo_name, taken_at DESC""")
    out["slos"] = [
        {"name": n, "compliance": float(cp) if cp is not None else None,
         "target": float(tp) if tp is not None else None,
         "burn_1h": float(b1) if b1 is not None else None,
         "budget_pct": float(bu) if bu is not None else None,
         "taken_at": str(ta)}
        for n, cp, tp, b1, bu, ta in cur.fetchall()]

    return out


def windows() -> dict:
    """Next window + warnings via the reconciler (source of truth)."""
    try:
        r = subprocess.run(
            [sys.executable, str(REPO / "runbooks" / "maintenance-plan.py"), "--json"],
            capture_output=True, text=True, timeout=120)
        d = json.loads(r.stdout)
        nxt = (d.get("next_windows") or [None])[0]
        if isinstance(nxt, dict):
            nxt = nxt.get("slot") or nxt
        return {"next": nxt, "warnings": d.get("warnings", []),
                "status_counts": d.get("plan_status")}
    except Exception as e:  # noqa: BLE001 — the board must render regardless
        return {"error": f"reconciler unavailable: {e}"}


def render(d: dict, w: dict) -> str:
    L: list[str] = []
    tiers = d["tiers"]
    crit = tiers.get("critical", 0)
    L.append(f"# Sweep board — cycle {d['cycle_id'][:8]} · {d['started_at'][:16]}")
    L.append("")
    L.append("## 1 · Tier board (security, contextual)")
    L.append("")
    L.append(f"    critical  {crit:>4}   <- pages operator (external + exploited + vuln)")
    L.append(f"    high      {tiers.get('high', 0):>4}   <- briefing / reading list")
    L.append(f"    medium    {tiers.get('medium', 0):>4}   <- maintenance-window queue")
    L.append(f"    low       {tiers.get('low', 0):>4}   <- weekly batch (policy/hygiene)")
    L.append("")
    L.append("## 2 · Action list (numbered, by importance)")
    L.append("")
    n = 0
    def item(rating, category, desc):
        nonlocal n
        n += 1
        L.append(f"{n:>3}. **[{rating}]** `{category}` — {desc}")

    if not d["criticals"]:
        L.append("*(no CRITICAL items — nothing pages; list starts at HIGH)*")
        L.append("")
    for c in d["criticals"]:
        item("CRITICAL", "security/exposed+exploited", _desc(c["title"]))
    for h in d["high"]:
        # category: real exposure when recorded; else derive from subsection
        # (git-history findings are repo-exposure, not a served endpoint) —
        # never default to a specific-sounding label the data doesn't support.
        exp = h.get("exposure")
        sub = (h.get("sub") or "").replace("s3_git_history", "git-history") \
                                  .replace("s4_cve_check", "cve")
        cat = "security/" + (exp or sub or "untagged")
        item("HIGH", cat, _desc(h["title"]))
    for f_ in d.get("new_other", []):
        item("MEDIUM", f_["section"] + "/new", _desc(f_["title"]))
    for grp, cnt in d.get("medium_groups", []):
        item("MEDIUM", f"security/{grp}",
             f"{cnt} internal finding(s) — maintenance-window queue")
    low = d["tiers"].get("low", 0)
    if low:
        item("LOW", "policy/hygiene",
             f"{low} policy finding(s) (floating tags, drift, stale charts) — weekly batch")
    L.append("")
    L.append("## 3 · Sections")
    L.append("")
    for s in EXPECTED_SECTIONS:
        info = d["sections"].get(s)
        if info is None:
            L.append(f"- `{s}`: **DID NOT REPORT** — gap, not a pass")
        else:
            L.append(f"- `{s}`: {info['new']} new, {info['open']} open")
    L.append("")
    L.append("## 4 · SLO / SLI")
    L.append("")
    if d["slos"]:
        L.append("| SLO | compliance | target | burn 1h | budget left | as of |")
        L.append("|---|---|---|---|---|---|")
        for s in d["slos"]:
            comp = "?" if s["compliance"] is None else f"{s['compliance']:.3f}%"
            burn = "?" if s["burn_1h"] is None else f"{s['burn_1h']:.2f}"
            bud = "?" if s["budget_pct"] is None else f"{s['budget_pct']:.1f}%"
            mark = " ⚠" if (s["burn_1h"] or 0) > 1 else ""
            L.append(f"| {s['name']} | {comp}{mark} | {s['target']}% | {burn} "
                     f"| {bud} | {s['taken_at'][:16]} |")
    else:
        L.append("no snapshots — SLO section did not run (gap, not a pass)")
    L.append("")
    L.append("## 5 · Maintenance windows")
    L.append("")
    if "error" in w:
        L.append(f"- {w['error']}")
    else:
        L.append(f"- next: {w.get('next')}")
        for warn in (w.get("warnings") or []):
            L.append(f"- ⚠ {warn}")
        if not (w.get("warnings") or []):
            L.append("- reconciler: 0 warnings")
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cycle", default=None)
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    dsn = _dsn()
    if not dsn:
        print("no DSN (set SWEEP_PG_DSN or run under sweep-run)", file=sys.stderr)
        return 2
    import psycopg
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:
        data = collect(cur, args.cycle)
    w = windows()
    if args.json:
        print(json.dumps({"board": data, "windows": w}, indent=2, default=str))
    else:
        print(render(data, w))
    return 0


if __name__ == "__main__":
    sys.exit(main())
