apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: holm
  namespace: my-software-showcase
spec:
  image: ghcr.io/ibdigital/my-software-showcase-holm
  interval: 5m
  secretRef:
    name: holm-image-pull
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: holm
  namespace: my-software-showcase
spec:
  imageRepositoryRef:
    name: holm
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: holm
  namespace: my-software-showcase
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: my-software-showcase-k8s
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: holm@showcase.local
        name: Holm Image Automation
  update:
    path: ./holm/deployment.yaml
    strategy: Setters
  sourceRef:
    kind: GitRepository
    name: my-software-showcase-k8s
