apiVersion: v1
kind: Secret
metadata:
  name: holm-secrets
  namespace: my-software-showcase
type: Opaque
stringData:
  db-host: "mysql.my-software-showcase.svc.cluster.local"
  db-port: "3306"
  db-name: "showcase_holm_dev"
  db-user: "holm_user"
  db-password: "changeme-holm"
  secret-key-base: "changeme-secret-key-base-generate-with-rails-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: holm-image-pull
  namespace: my-software-showcase
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJnaHRici5pbyI6eyJhdXRoIjoiIn19
