---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-config
  namespace: office
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-storage
  namespace: office
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-27866fc8-77df-4fe6-8397-e69f3fa0fa7d
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: affine-pg-data
    namespace: office
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      fsType: ext4
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
    volumeHandle: pvc-27866fc8-77df-4fe6-8397-e69f3fa0fa7d
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-pg-data
  namespace: office
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-static
  volumeName: pvc-27866fc8-77df-4fe6-8397-e69f3fa0fa7d
