apiVersion: v1
kind: Secret
metadata:
  name: affine-secret
  namespace: office
type: Opaque
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:nqP9lIlT,iv:qg5Ys245F46c0U1saByWYsoASUgZXxFusHHRAIv5994=,tag:a/p9Omtyvfb7Eozd9SblWg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:vVVw/EU12pZ5TowgjTKtKrUWw0nJp5YERw7W2Qlw+EnrQ/sshHwY1L7R/IxTPLPMyAMFnMwSI3tG1aR6avmtfQ==,iv:vO9XejG+ndgYBscsqULowpOriMuIPb4JOTEKHZSBK2E=,tag:bXnBW+3AymzyJX5EKDKjcQ==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:9x5P+zCP,iv:wU1L4IwmYpWjbfFdN8C2OSqETHooKvuOI5vn5foU3JU=,tag:mzyc79o82GKrDjN/ZC/sgA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:k/ohSZh1SSlatmQ4eCzoaL4+6jjZgFWdsKKCv1lyeYGXtxn/bEUkxEuf6YNcob+8TCK20eaHGFi64Vyao4GGBSq3lGPxAlnEE4JEP8vrl5Jri4BfN5eN+XBzZF/z3bH0ELyj0lRQSF36tg==,iv:fyGAS/8+GNm7MSUvlgaH4VjqT/GSTQ/yl/pZP8TkDjM=,tag:ysFoa3T83Ht8L+NSr9sKsQ==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV1I0TzlRYlZBTTRKY3ht
        TnZzZUgwZ3VTVnVSaSsrdmwxQ05tUHdXbUJZCnViMUYxaTZocTBieVE4eGwrY0Vu
        Z012dDJBZTlBSVB6WFg4UmRub1p2MUkKLS0tIDU3Y2FQNW1iMEJaTFhRZFlyczlN
        L3ZDenVEc2puRW53eExtdHRyN25Wd2MK0/z23I+I7AcXfEZXNeszBUEW2T9fKfTL
        MwnUxT6/CMUEwoVIamzJI/rjkWM6unLpfOZUhp3i6Iqh3L+Wt4/jjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T21:18:05Z"
  mac: ENC[AES256_GCM,data:MMQLD98zXxvaSDOhyDEfUfL9WrTCgVbDIl64uGBNlwBt8eg0tLqQnWjxBvlyyg9wbNfndQc/QlT+Kv7wS7fpLI94TJUUy2EfFQ6MFpSMyhyjeanU7vA2M8Az98luRIaDj8QnJ3YgG4OVxZ8OxCtO8gD80aExyGlm0NEEEajWD3Y=,iv:xCl+seVpPjGWuFpj2hN7MMCeHQDdAo85+zsowheVJiM=,tag:f1reho+neUfSGP3BmMTilA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
