apiVersion: v1
kind: Secret
metadata:
  name: affine-secret
  namespace: office
type: Opaque
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:GXnNOpEx,iv:lFz/4HHRrOuNsaUrmbRJGkwFedgggI4fN3y/ORAlHpA=,tag:KDsn5bWLpVLkoUbHv9cL0A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:/VCn6/Ti8b8i7qxk33Z2I36PdKyDTDx1JO5X8zGK7uSHlJGOPlq2ryV22RMWHSyUfh/gNXKbza1JXS3bDOuZ5w==,iv:4r5Ukwnz5GvwB8LBZtiiXYKgmyRFw/hsuv+vk0d5v0s=,tag:H+2Dfw2yiTDP/l0UN+knfg==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:kTbekzTC,iv:lqjaOUXfrCLEApmWP76RoWDtmeIJ4ouTlzTQLKorqZc=,tag:Hw+ALYrYJiSR+UbMAk6wRA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:O57x7TrrL8T8ru8RxBwE6vvYbbqrl6a0FiFEPHyh/eOY8S4Dl7pyZlZKgqApbYnwAP9Cr/rKT4bcAmpEP6cJfk/En7OOwHF6fOe8/eyw79G7H2UMDLr4M0yC7+Vd2klQCR3KjeJIxTzkz5GVqNEtFg==,iv:KMRSu8fVxxpBTJVZ/qtsDW/3CLggCgCEMpZIZylBRts=,tag:NE2GqrFwSTsmYA1rOunRgQ==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaWhWZWNHZU0vQkRmNmJo
        OXJJZ2NTTzZaclZVK3dNWHZoeFQxTXVMUjFjCkh1ek1hWXdWQkhtTWVHUnh6dUho
        YWZRWWRLd2M2by9pU1R4ZjYrR2F0YWsKLS0tIGxtS3YrMFM2TERYeC9qSEwvcHNq
        YWllNEtaOVloSjluclIwcE5NaXZjVDQKEw6Y6sPS3atpVfw55fASXqlTH9bTBETO
        fp1HCW3lQBNsq/OO/ss8wdRsHnT78rgl+6ZRIyxJaOjTDUogp+WwBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T21:05:39Z"
  mac: ENC[AES256_GCM,data:qOHkFlxW6M1aL96X/ZmuMmuA1HQe8/kdfertCNmwc2Lc7qKGCC37e+bf5gasU/hbIAB+7TQg1QR6AFCudor7ByT6wlLJGomUM/Cgd24vCTnqok1YpKGRTfPaUEXOh0Zs4hAyQ6+vhBlJERAljlWTzK0Nk57nH+FJYjR6jMC7lGI=,iv:dOTLlHdstXKP8Wm93VRI1wydP/CaCRrLoyDODXay7TE=,tag:d9IipY0t0wTDYczw8+Pnfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
