apiVersion: v1
kind: Secret
metadata:
  name: splitfairy
  namespace: my-software-production
type: Opaque
stringData:
  #ENC[AES256_GCM,data:sbpVpE2f3vwPaJhE3EN/os//2PrVTeWdj+sAgLLtjyvRAFIGVNue11GsVxC7NG3GZxYJweQTOELZYo9kMdEbeLozeA3nz1SLoGOjMIYoEzdKOodoIDXelGW28stvfYIuZZIPCdR+mg==,iv:U5r9U27Mij56Zt4WsN2OySNNuu9fnxq0OAbhr8g14PQ=,tag:PDoouXdqj/UfUquGzBPQwA==,type:comment]
  ADMIN_EMAIL: ENC[AES256_GCM,data:XfjacTvHU16sIdIngaHAW0Y=,iv:uKDamOv3rVE5nIQ6Z5BhobpkJnBEPmOMPKeToUFre6I=,tag:MZdegg1/Mih3BWhh/LfsaQ==,type:str]
  #ENC[AES256_GCM,data:SZAidHxmYWBlUYMv3eqwaFxsn7nYBUgfaLqm1sZv3NL9gI25mfMZSN5SDAtxrbC1wauFOvZhLRQ1Wmr4Xkr37xHVW6LE+FneG5O/C0yc+7d9tw==,iv:fg2RnH9Ea+ihk6KHFhyIKq6hLnNwG++jKZIQSi2QNFg=,tag:qSkISo/azcz9GDyMSLomGA==,type:comment]
  AUTH_SECRET: ENC[AES256_GCM,data:xEn6N2abie0mwBTkzR0Q1LDbJ/wK7gx0NNT6FvR/UqVtM/qPhwJz6Tx3pyBQevOLqwYyWeu9eetoNniX7dUe3Q==,iv:TTTPj4mD7hVZn8HzGSCKw9rvE4reLS7p2s79Wgzh6/0=,tag:ib/m24r52693v0YLXFDBlg==,type:str]
  #ENC[AES256_GCM,data:mW2obdJQIIlF+VI39EJWjhtGJpy9VLe/pL87aiBqyqt3URT69kyf/PNalBBnpKGTn6YBb73zNc5xgaptaZdI19RC7GdnRp2njg==,iv:eIuzj5KXuCJCyDMG5oVedUNqtlgskhYaRHTX/Tk9384=,tag:Qy/MfEF64ftoJk8P1Zj7rA==,type:comment]
  #ENC[AES256_GCM,data:WeA+PLTzUInVlE9SswKbooFylO0f5oTw9KGTdHROwMAPusG838iKH/IT1HsXIv4VtV33ObgXO3QTNQKiKeDYxAuZQZ11vKkRKizTh4sp,iv:N4+UkyBedYbeNb/G2qtZRQVvSOWrDzdO72YcOGwjHuQ=,tag:zmsh1BbeqTvzKstN9Lx8VQ==,type:comment]
  #ENC[AES256_GCM,data:87LSo1p279aZSO5J98Cz8s9bS9bp3wp0O8+vcRe38OGMiiuHHPpvnkJbb29aRpwGcMpOH8kDNaP1NxHEI/u/L0zRnwYQNSlQCjF6box8Vg==,iv:lGGAvRpUqtPQaooPTtCHcEC7hvuqEDITclpNlxDtB0k=,tag:IFLdiP0N5i5K/U41qvYCoQ==,type:comment]
  #ENC[AES256_GCM,data:dByBmhCeUdoQCB5UUh+0Y5YvLjzYFGeZ+eIngZRE2pIWrSPJs7D5NTQUqmfX5EZXYeZWusu9ZGjJ3V/v697aNDM=,iv:idUGukIv8R2nBsF5jHC4Kgm/3bvbkMZn0tH5GrXAuNo=,tag:TWhuAe8vw7H+74pdAQwF8g==,type:comment]
  SMTP_HOST: ENC[AES256_GCM,data:LoD6VrV87sBJEQdG,iv:ZC9PL2XCTGjhazSAKDrsZucuQe36KnmHgxe9Rpf1brw=,tag:a/A8jgE91rZvgm6m8UqpqA==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:EXh0,iv:alapaPNRN0B8gqPC+BdBAum0U0hThj2LPjEtwxx7Jg8=,tag:1M2dbyMwNBMuGFLZd72I0Q==,type:str]
  SMTP_SECURE: ENC[AES256_GCM,data:hKo6IBY=,iv:0UJkJ9E2aQ/b6wuALf3UAnkVVNlUYAJcobzWcbvh1Ys=,tag:wp22PnLgzVEKdgn/x2svAw==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:SQhXDrLPrRwRLURElUd6cDOqQIv2,iv:zSgJ0C11Bx4pChAE4HAwvN+t4b4nxY6PV2JG7aCc0Ko=,tag:5JBvLXGOlXOj/8mGWb2zVQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:HJkVEKE6oEY+0lQTobSNQGWLRudJfeUhML6gng==,iv:f/cg1CTUa8JL8SUNubxQXLHGzrvhBjKAGfS9W2rFRDQ=,tag:Kn2+/MO0EwDXmXqqy9xCEQ==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:2j+9eBTGVfzSLHRJxIfC7ZF+umC3lGS3fHuMM9WMoSdcgA==,iv:Fj33WAMnGGT10Faq4CQqnxDu7AEaDflSdPVIrG9k7/c=,tag:NhsfxutpmGuNexcGz8V00w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaVhlRjUvdFJrYlBwV1Fo
        YXp3RThmMFc3SEJQek9VZERrazJpUGV2OFVZClBvNGFzU250N1NaalBUVG4wZTJm
        T0lOMUlHZVdaMk1SMHhFc0Q1Z0hlUjAKLS0tIDMyOUxndXhQVkpaaWxOS2dETWxu
        UXZwMzFTdXN0RlA1cHBQenFDc3Z4ZVEKRYNiPuD39ayJAyCRjY9nUMZUvFa5FjHI
        KLVx5BaLRaNAkkSXu/JZ+AQNfeu1sRlHLoVFpyCdLWJA40ADXv8Ucw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T08:54:06Z"
  mac: ENC[AES256_GCM,data:pDKuMKM4b6d2QMY85LJi/+63+7NRjqyQBmpVEeOoyH0zIRLe+n8LdysnoFHQyD9Q7Ne6k/+APgrZ3oQu/uZM1+v0tdn2HAONcfVGpassTHl88XAFYcJW7jSjWPkgNLK7FZ3u/7tGqwXR+ba38ue0GV7JskIqNhtjiX9/dmGeGmA=,iv:Ejykv0Fvg19/Owi+Z7i/Sq268032TCtJ0UOR0MvqBfQ=,tag:78Qq5xtQxZG35dpfq/XQDA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
