apiVersion: v1
kind: Secret
metadata:
  name: splitfairy
  namespace: my-software-production
type: Opaque
stringData:
  #ENC[AES256_GCM,data:nliJgjcnEDJzzeQctjRx8Virvo6yG6AmcM3gGHvWubHG5HbEefFI516EK7WxwaUHOFYGm8oQyQHSW7COAUUS,iv:w08RcJpgfHeKwci9IiO2g5REL8HaSkFoKAKSR/b6UF4=,tag:QTc1FMOPVqomHL9NbwxOMg==,type:comment]
  ADMIN_EMAIL: ENC[AES256_GCM,data:1Gc89EgXoZUwNnUpiPlkG3poqAEbjQ==,iv:BYsH2Xqhlonjri9JvWGqP6CTJIgzc41Ik+sOq5CqyAg=,tag:PwIhwCLh5mJXrU0PoSytnw==,type:str]
  #ENC[AES256_GCM,data:SZAidHxmYWBlUYMv3eqwaFxsn7nYBUgfaLqm1sZv3NL9gI25mfMZSN5SDAtxrbC1wauFOvZhLRQ1Wmr4Xkr37xHVW6LE+FneG5O/C0yc+7d9tw==,iv:fg2RnH9Ea+ihk6KHFhyIKq6hLnNwG++jKZIQSi2QNFg=,tag:qSkISo/azcz9GDyMSLomGA==,type:comment]
  AUTH_SECRET: ENC[AES256_GCM,data:xEn6N2abie0mwBTkzR0Q1LDbJ/wK7gx0NNT6FvR/UqVtM/qPhwJz6Tx3pyBQevOLqwYyWeu9eetoNniX7dUe3Q==,iv:TTTPj4mD7hVZn8HzGSCKw9rvE4reLS7p2s79Wgzh6/0=,tag:ib/m24r52693v0YLXFDBlg==,type:str]
  #ENC[AES256_GCM,data:mW2obdJQIIlF+VI39EJWjhtGJpy9VLe/pL87aiBqyqt3URT69kyf/PNalBBnpKGTn6YBb73zNc5xgaptaZdI19RC7GdnRp2njg==,iv:eIuzj5KXuCJCyDMG5oVedUNqtlgskhYaRHTX/Tk9384=,tag:Qy/MfEF64ftoJk8P1Zj7rA==,type:comment]
  #ENC[AES256_GCM,data:WeA+PLTzUInVlE9SswKbooFylO0f5oTw9KGTdHROwMAPusG838iKH/IT1HsXIv4VtV33ObgXO3QTNQKiKeDYxAuZQZ11vKkRKizTh4sp,iv:N4+UkyBedYbeNb/G2qtZRQVvSOWrDzdO72YcOGwjHuQ=,tag:zmsh1BbeqTvzKstN9Lx8VQ==,type:comment]
  #ENC[AES256_GCM,data:87LSo1p279aZSO5J98Cz8s9bS9bp3wp0O8+vcRe38OGMiiuHHPpvnkJbb29aRpwGcMpOH8kDNaP1NxHEI/u/L0zRnwYQNSlQCjF6box8Vg==,iv:lGGAvRpUqtPQaooPTtCHcEC7hvuqEDITclpNlxDtB0k=,tag:IFLdiP0N5i5K/U41qvYCoQ==,type:comment]
  #ENC[AES256_GCM,data:dByBmhCeUdoQCB5UUh+0Y5YvLjzYFGeZ+eIngZRE2pIWrSPJs7D5NTQUqmfX5EZXYeZWusu9ZGjJ3V/v697aNDM=,iv:idUGukIv8R2nBsF5jHC4Kgm/3bvbkMZn0tH5GrXAuNo=,tag:TWhuAe8vw7H+74pdAQwF8g==,type:comment]
  SMTP_HOST: ENC[AES256_GCM,data:LoD6VrV87sBJEQdG,iv:ZC9PL2XCTGjhazSAKDrsZucuQe36KnmHgxe9Rpf1brw=,tag:a/A8jgE91rZvgm6m8UqpqA==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:EXh0,iv:alapaPNRN0B8gqPC+BdBAum0U0hThj2LPjEtwxx7Jg8=,tag:1M2dbyMwNBMuGFLZd72I0Q==,type:str]
  SMTP_SECURE: ENC[AES256_GCM,data:hKo6IBY=,iv:0UJkJ9E2aQ/b6wuALf3UAnkVVNlUYAJcobzWcbvh1Ys=,tag:wp22PnLgzVEKdgn/x2svAw==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:kreee1qBlYckqrE3lvNGcjtBFew=,iv:Nq6T09s988nU3HtnASSeZA4HpAuIb7nUnG+2Yso2dlQ=,tag:HLHjkqU22HD5jlU7YlUnDg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:/ksPLYZnQEBGXJoDvDXZ6ObcswREu7fW,iv:/pOf3568VEMmoDLxvtdAksWGeRB4rwfJpRtxp8ecw4w=,tag:ogYF1xBAFUiu4y38L6KvnA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:c35gEn7k/fn4dXok2/qtU7Gnfeg=,iv:xih3c0LRwVWh8Dsj0J9dfQnitegPNKKBRR8demaegjI=,tag:k4dyL4CHL8GUX+oMxyds4w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaVhlRjUvdFJrYlBwV1Fo
        YXp3RThmMFc3SEJQek9VZERrazJpUGV2OFVZClBvNGFzU250N1NaalBUVG4wZTJm
        T0lOMUlHZVdaMk1SMHhFc0Q1Z0hlUjAKLS0tIDMyOUxndXhQVkpaaWxOS2dETWxu
        UXZwMzFTdXN0RlA1cHBQenFDc3Z4ZVEKRYNiPuD39ayJAyCRjY9nUMZUvFa5FjHI
        KLVx5BaLRaNAkkSXu/JZ+AQNfeu1sRlHLoVFpyCdLWJA40ADXv8Ucw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T06:34:45Z"
  mac: ENC[AES256_GCM,data:Hw6ZYASV5oCOsRx8ArvFv01qqlC/GB2TzpAuvlDBm917LgRgi7Grh8qoe0FB/q2ah2W3Kq1EiPI5FlxXPxzCLo8ZgBfk9c7sLoIxSolbc0YCjkkS3llLkHW0yXz0DOv4R22ahG54WZ+jjchDupNc3AD+DvBi2fel8vXf2dwBxBA=,iv:RbfxVS8yKqQdfOOE/y5jfL9/wH9+uh3+8lCeYhJxP5Q=,tag:MSrkQVEN8MH4AcYpJ3d57w==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
