apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uzeit-de
  namespace: my-software-showcase
  labels:
    app: uzeit-de
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - uzeit-de.showcase.local
      secretName: uzeit-de-tls
  rules:
    - host: uzeit-de.showcase.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uzeit-de
                port:
                  number: 80
