# PHP tier. All three PHP apps read DB_USER / DB_NAME / DB_PASS - a different
# convention again from the four used across the Rails apps. Verified against
# this app's own config, not assumed.
apiVersion: v1
kind: Secret
metadata:
  name: uzeit-de-secrets
  namespace: my-software-showcase
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:0cF+DeieFOh8r/N2aqfKNpi7HJrmDNz3gm5Qv3rQ1nKze98=,iv:i+cVJ0vO/68Ou0/VjYuSP+JrMlWlEFKEXCm0psu4Erg=,tag:/RGkwyCwkdwd+LR9xeCgAA==,type:str]
  DB_PORT: ENC[AES256_GCM,data:jco2TQ==,iv:rb9ODHpvZe52xXffKQ3Z+0CkK6NQ7u48aIvKm9fxm7c=,tag:PfWuJhdw7IAzjGNOmM05RQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:pDfmpHJhl6yk3wJzRiswWQ6KowuOIQ==,iv:Rqy0I0Lyn2A5sh+6b+MJRsA8o0K9SZXklVM2tt2veYM=,tag:FfeP+n+d7lWUabkcKvDwuQ==,type:str]
  DB_PASS: ENC[AES256_GCM,data:vp24Epp3GF97GDhF1hWK5yhHNfCIMkP+,iv:O3Bhj3IFzcv/AIEEVUEn79s2AUCrgyT4ybQDPJP+QI8=,tag:o1sVhQXDloPHxvpsvdel7w==,type:str]
  DB_NAME: ENC[AES256_GCM,data:Y0vLywSCtFOFLbc1DEPIxhahHTphwQ==,iv:gyORzRc/FMald3S4dLSH1zEF9imVNBg/6ZqzUjMUz/I=,tag:mBlkl9TQl3lgM1R68xF7sg==,type:str]
  TYPO3_ADMIN_USER: ENC[AES256_GCM,data:RiNYjN4=,iv:stZCWJ/EK0Vdb7j662e6qwY0dWpPapGRLzqxNn78bN4=,tag:776iASQemXYvpPbaqwOdgw==,type:str]
  TYPO3_ADMIN_PASS: ENC[AES256_GCM,data:+ejDv9+jugUcWo7+o9GVRJWPwpP1LOt6,iv:It0DyE9rjpb+ZASahpz9vpWsdp5VNdr5zY4tQU/V/Jo=,tag:hliyWWQOlHL/iZTTFPUuTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbzJqRHl0MDNDVldFK0dZ
        M1VkTjdvaVAxaHdWUEVZbFQ1MndmNkE4alVFCmcrR1lxREV5azlkY3NoOW4ycklR
        Uy9KRFZrSDVaSGZScHFVNWJ0UnFDcXMKLS0tIDgrUWRWTFNlQnVQdkVSeXU4MVpH
        blFzUkZLMXlDZlFSN1h3QWc5OExNNXMK9pHSTgi5u/+B49LeFQW21v9XcGFKy+Wl
        G+RHsFhPHXq47ud8jZw9ovX85hptUa1C5t3iwcgCKwffVwnMSWCgIg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T12:24:19Z"
  mac: ENC[AES256_GCM,data:aERjSPw2v08CmlYVUP1+ltyIFQO9CAIwY5i19Y8mljTcJ9ABV0khgoGlEeCXYFqKc5eRvBilu56dkUpEJVn5ii1NfN16DlzBTe9IodDjFCp5HCHimLDT9aA/gXHugMzOKZuZ7NykZJPKw8h+LpjPsxQlmdIH4oy8Uqy+zJgK9/A=,iv:INzGWLKuinbyC1snIh8IuI6c/B+4WsECjdL6ksx++3s=,tag:2jceNUg9pNc0BnEEcESIqw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
