apiVersion: v1
kind: Secret
metadata:
  name: the-ninth-banner-arc-github
  namespace: ci-runner
type: Opaque
stringData:
  github_token: ENC[AES256_GCM,data:P4nFlP+1ICyoNNrJg3l8N/nXaqdGe8qKA7lCzYY=,iv:1bjkjmAodo+Zf/rxz721NP8tirzoz8OddiUeCvmjPyI=,tag:J+cibtNAsBpr+TAwHuyoWQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WEZYUHU5OUZJZWRSSE5E
        QWdmeHI3b0pZckg0V2NtS1R6amdPVWxWUlc0Ck0ySm5NcEtPSzFLbmVCcXlvK1ha
        L09tSGZaa25JdWpmaWxYZWpNTTQwTTAKLS0tIHZ5dXB4UGUvMXBYS21ROVc5bTFv
        UGNuYjQ5M25samVydjJKbS9xMThZMDgKZvanUYG/PN/w3L+b6CRFSx6aNwjwBDIj
        8zljMzDgLFaOhQD0P72k8vsHh2ueoCCXygDIdtR5WkCSz7obc1GEmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T13:24:57Z"
  mac: ENC[AES256_GCM,data:s5DaVGdgy99ihImPJRUQQ7E2/1lXQwf+gJo1Sko5bdg9hD5mnCertKNODRVej5cyWhLDhaNCG+aTryq97ivz9R4Ffa+65fbasZRqFmQmvcTV0INrqt1P7jwuxZlck9Bgv53AyspqyLLhoF4AVr+CCA1wT+cmUS5aHjnLYobjzRs=,iv:BFyN4EAEx9yD4NfIvaU3HeoNr8Un6/YiivodQcNizok=,tag:9mc7Xe7CbaZHUzbghtFo3A==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
