apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-password: ENC[AES256_GCM,data:x/biUxIvjOr2Cyy4uPqkQ+P+AMNzIdmiWvkUl9hTlFQ=,iv:WqxQWj1C+i+Gl5ySh6LkUSIA1Ys2pK7Ppz+2iyOcg24=,tag:dGPw0ATzarYNaqjR/NmLyQ==,type:str]
  admin-user: ENC[AES256_GCM,data:MDfXAH0=,iv:4SBvva9zZ6itzI2DHfg8CxxVAJuhS0lHHzlS+n5c2g4=,tag:6V/luQx2UMCcVkyl6tzFAw==,type:str]
  oidcClientId: ENC[AES256_GCM,data:d7jDkLkpQH3+IjOp/1CUPMpxYX9IqB2EiuRyLvZ2802cF9UEXUfhow==,iv:t3CsQC9EYM3EWXKNPeirRf+mRcohDfoORG6fEZ2cgJc=,tag:Bd8OspzUS7Prt+y7/ZHlug==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:r1O/MzwCl96RF3sY8/8WMM9T0k3SQMM7i3tQTiDgnHFp8KmkgMdejHEsckJKVv3pmliYegh9W2+cmNEbNalo3Azft4/jYjxKBw6AW4ASaNLfhowI8duW3X90U/0M7mqSNRrFZc53cCVvFM8YpNY3fjo8mguYiTtGvvdcJjdLdvY=,iv:XuuMxpAeMUdPpvXDdFWAevkLfdAPl52J/3JFIVOhalY=,tag:f1udfGW8uXfwae0d2nPjSg==,type:str]
  #ENC[AES256_GCM,data:LlMtiiXJS81pUR1IJdsJOfyyb5o4Z6JfR7MNu1fCn/bBUgUtgx5R8nAi2nlAtkpjc5Fhy56Eag==,iv:CFBR5acY0AF72LfbrXQOdmSQEQvD2Cb+fLHyrXnKp4c=,tag:jmed5Pt4fQtq8oXRtcFjsg==,type:comment]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:qPmsIMcbVE9jjltX8Ys2GnJ7FR95JakPFZsT4WbyoDpmanHLJ6sSbQ==,iv:Xp9eQ0zcN9S9CT5OudNqpktj4Jf1FPNE6oP5p5uUspo=,tag:RQMAOePaze1/2D6IurY8ng==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:oAWPJbYIAF+PqItpb5zR0s3R9vZs2LJG11gsKbV7MCKxuCoRqCEAtzdAjntXgjUYyOPsjbUsHOri26qnoISYdPB0ghqlhFo6iqLoUXOH8bvsR4zNTaYyWyYLmqsYKc8I8JHEGuKqTHTXFYBQHXnDJrG9IMhms9OVpzEFi+VwfQc=,iv:/V2jKXw3F3gJ4XfX8j9AI/drIlkYGjJMg6TmZ4r3xmc=,tag:0CZRnHEqq/+rF17IY5tv8Q==,type:str]
  #ENC[AES256_GCM,data:tyf0qJgrmLe8YYc6Je85A4udkoxaesQWqetHzgc2xdfH1LqnZGqAQzw=,iv:DylY/Wvnt9+zM3IxUGosqqyUaH1PVRdRizDII4fOBI4=,tag:0Z47hPGr+taSfFHM0YHWtg==,type:comment]
  TESLAMATE_DB_PASSWORD: ENC[AES256_GCM,data:B1GPPBJtC4U0YU21EzAWVALLDru8V+WOEFVEwpCh+U4=,iv:5OrkzyP/xmW8VaIrEPIM74/NWqz7OE/rFGzblD625fk=,tag:om6ky7vWRc23UYJLwPipRg==,type:str]
  #ENC[AES256_GCM,data:dYdPbgMHiqpnYLnMknytOsx6mhqGMzpksGzwQjnZNLTkvrvg4iNMHnG8MFg=,iv:J5oFeafivMgt5KjZMJud0/+ErVw6Qowos0MPVVwluZs=,tag:0FYCw8lLw/+tubV8ax3VMA==,type:comment]
  INFLUXDB_TOKEN: ENC[AES256_GCM,data:A3JvyPYgY2LPqrQa7E0jP0im9tUxZL5qZQYxmX/9JmbmgMR5e8G+dB3B+Prt0VKX2qbPeOWKu0/vx+YOjcpr/m20DoJhmKcZXmyKIsaohivt2ulR34SeHA==,iv:uolM+RsMYNkjuYcfvDFbd+W5WX8x+yZ/WHvi7Vvl0/A=,tag:h6kntiZ/6MBzQ6sWTVc+0Q==,type:str]
  INFLUXDB_ORG: ENC[AES256_GCM,data:JtMHoQCB4+hr0A==,iv:HCNHdJ/ek8/S7ug7otVUaMv7NuY/J0fj7JJylwRMu9w=,tag:MQ9G5A2kDHICYWEmR3I4rA==,type:str]
  INFLUXDB_BUCKET: ENC[AES256_GCM,data:BllUw992VQ==,iv:wkIf5eVaeN/mOBpLQ9nG8MVoqIkP4vog9c5RXsymzNU=,tag:3D7bHDb4GOQkL7/kRCu91w==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc0lRZk9uMEZ1QllTS0xr
        c0hXNVgwakZpV1dqL2IxQmVmUFBxOTdPaVJjCnF0dElGNC9SVnoxUDN3OGVkanRs
        OEZseVNzMWE2NTBFd3JtazhYTXptNVEKLS0tIEJRQ3FoajZ0VkxjTDIza3dxRnFi
        Mk54aU9DSGRzaDBNbSs3RHBzVEZncjQKI/tdr7+ljC0k/22dDbB1kJSKokpKbWcz
        Mm5UV+KKGCtiylYdfU8yDwRVV0zuBy3AO9eeZKrjygZqMESYrtN0rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T22:12:43Z"
  mac: ENC[AES256_GCM,data:Qwcg3qztvkC1A9lQwaq6ziyRcOT9tH8TLhlId2leAFOpb4MDaDcr0sj5fJxTlKIb2mb4SnKqwqVFCJNqjhOY14AVlwgiLyMUBoEyyAB8PBPMeQZu2itpnDMtCYDpaE7bHuyL/tKF9/zoJox54rmhn7nuMsMZHz/j58M1aMQ+TeI=,iv:hLUSbUldIXc4Hrtwj8n86eIm8fGW4euJFea4YqFLj4M=,tag:UIq7zYBKk7dpcu7ae7qSvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
