apiVersion: v1
kind: Secret
metadata:
  name: unpoller-credentials
  namespace: monitoring
stringData:
  upConfig: ENC[AES256_GCM,data:D9bcVvrCuz/qvNMS3STv292j3mFLnuJirbvTfYnpVfTFTcv85Wf1XK6XcC2U1eNsl4IhOrYHnln/crdYVk+huGOyjZpRIFjhto28K5ipnVT9ZsPk0qhfu0Ek1wXb6RnHlrAUxqrs1pu6UpDq4PMlcl2IpInFAnPW5LQ37qSa7vX1nO7CnPae1MdTZ/eDHdXKaI6qWg5a3uZbUBAL+y74kJmOTlp1VM/2/Cw73kqE8FzirIlCxw9pFwCHRXtgHXQoXryGY3AeTvToj9qfIV4qr5KrWm5UZcdbTCZFQbi2F6J4LjjrIszHb9SJFkg0AcpcAGjvPqp54lqkX6F+Y6EAt6TC74Gcgpg0yI9J15GJd/i5nseoiiizt94r/Jo16xXvULI9vJyCJrlrUld6cccARLDF9BTN7fFL6D8BiPKo0ldQVEufrbfNVg2wZBLVIZ58y37MQdTdmurGHohqQHWLXkaUrdEHsq3Uk8g/4DX5Oa0vikLzfxxcRn3PlgJYsp9LM/4BgiUBw3lNgdk3pja8ORWZlNP/ljmiMHDfG54nnD4eMofhBf2gHp9pUjtU1vViCmAeawINIXY1qCizkrvcoJxb9QEtmP4m5ojHExnclXYxcpJ5GfQPYWUg3Iz5b8ryfrmzVKa083pk2zdHz1J7q9GS8vhgDqjHjbgS3+QLj3R3S698g21FKose3OtgQwRuOM4cLDeBxXC7wk8wZGkjueS5/b0v8pXQj5SjKqzr+uFHR1/cP1uPQ5Hxm0sMBK2CNOvlBsqPDnnPeHOdAdqEsc6+cUsFNhOmcBXGC7Xz+mAAUvS8VnGAZKY3c2XuWZCFLfzvP2le+lPg3zR4H5F4,iv:PLSLLBYhfPMR8viHti21/4cVmMmXkjQDOETClzNx4fQ=,tag:oDeq6aG/t2dLuxCkyyi2/w==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb01nY3I4L1Nnb3lkTEVB
        WVRZVjR3K2hpYWczTzFydmg0WUJpUUpuazE0CmhETnhsL09hV2xiditEQ1g2R2VB
        L1ZuNkUrbDdYUTg2TFdHeHZheEE1NHcKLS0tIEZheTQzWmxqbUhmOFhrT3ptRGNi
        WGs3aStaTnhvMWYzVlV4aGpKWFFJNmcK2urqfgbZaplPGoe1l/3T9WwFOpVO9CID
        NUDsLNKJTQtMBr9G8AUCsrLbB2fl5vhJ/DzeNoXeoqkZjSswoDfm9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T22:55:49Z"
  mac: ENC[AES256_GCM,data:W1TYai3LlaPzXFJPWRe8ReyzzI5ILhtQb0+EHXuEPrkQQdEhaO9xatQGPqUZG5OytL+QtI11OLcSgtqYg1a2iAlyDujnLNsvGHEHbXEoGAgAxUbuWg1FFi9WUGuF6JY0cnh+9aZGHaEqjmLoLB9qT6/6qGDk/7UwSF3NXdMTB20=,iv:ugZ6ofxMRgKK1a+j24BT93Szg7m2yOo6wqKZSDr7nGA=,tag:9SKOHGIPnSVNDflBk7ikog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
