apiVersion: v1
kind: Secret
metadata:
  name: unpoller-credentials
  namespace: monitoring
stringData:
  upConfig: ENC[AES256_GCM,data:vKlr7WAqw03ofQWViNpU5zs+jH9XWIHCvbVKkCNCNNInY4+XG8S4+MfOJ5gVM7p3YiQTNOb/nGxaz6+kew0NBulRSY8pcwCxQZVYItFlX7b+qVBS8dW2GY3iiHihQnXCMJ/g1wsUUsCezYg4gXmnOIT7O1q+2/NAOFPDASVtnowC9+IZZd17xe8tt7tAlxDKtNNkS0jrCVatsy5MozrSaSqe3Vkulru8AyQjVBkREy9AsG1g20Y0FAX8Az1TNLELQTZbh1/i9OoXHVAnlp1b8hrh/w4VupCu3+XqTdnLW7V8c7jUzltr7gt0khY3x7sThxLRwYKiHiwBZGQu1IQBJNJtSDHsqdvC9FGp+e7L3/Yl9CGD/RKfEpVDqDLaAI1UQlfN2MgQ11ng84dx0OASV2WhswPzT65SlaHUyrMym6RMy3cylmSX0fVtbvDFPQGtadjRcXFcUUhXyE6RmCAkcEgPT2OF0CwHvj265Vs43HFWJp3RdYGKXAWzCcDFLH+vLp+/WeBmAdWpIAbqD2GIZ4Psz3vnp0L6DWbc4qy0zbhYqrzaTVqmInGYRNJsHOT/0DnHPD+lOj/oJ/AX7B6V+WMmdFxJXQle5sOFG8sWxtbOnrW7OkXb8NV4Bzp42YNEpxHiC8vGroPvJ9duIrW09b3ftEyXZhId81WKoF0SM1w5RS0EbF/tzKSpmVigeZ+aIETiU0Xb/BUewOoxx2Wm9SfQd0iV14ZaBBa9PK7S7HV4YxRRLmrOA+pPbW0+IbgQXIaX5c48CRj0IQ4AUMBq5beQXHCTyfM2mW+Hr285IsUe4h2ysa26TAykMLf3jJ7xBySxFvo1c0tuMexH/6vRvfY=,iv:aoNwSLSubexooI1+SfsN8eiv2otnJlPa4k46xUH1BFk=,tag:Ak1NdYoOOm6FkRKNlCqsOg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU2ptSFh0S0VKUjh4ZlM3
        eW5xVGNuNjI0ai8wcFhMOWYyNS9YNjJBOFZZCng0MEtweWVkVHI5Z3dRMDJKaTFs
        OVNnS3VBNkgxUlUvc2xIekRoTUxkM0EKLS0tIHpWYTB1RjJlSU1RU1orY1ZlUTVj
        ZXhaWUNBV3ZTVUQzY3FndzBsd1lyaE0KTcHBg+KmZ4+KpSD0fl/5rZ3O+AFGWLTJ
        1/OS19N1bd8fE9Xb70we6SXkiMN44J145J3d4+Lo+FPQ64idYgHxcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T08:01:27Z"
  mac: ENC[AES256_GCM,data:Aa/vUX+RKM1L21oQZBKnN0MCC9Ly7Ic2subeMMhYx8HmnWBwiov06JS3id0oLtAfsvgkFc0KjZ3L17BgfKmxg7mPLxaqH6UKZ2jjo4T/+k32CMkMtwb3nVOYtxoAhUf4V8ICSL2MAXiL6x6OL0BJArbbOsr/rZRf+ag4quTa7Hc=,iv:Y+KCuRbQNk3oCRbgBxnOt9xTfVKgrMDNQOV2bqQ1vUs=,tag:GCjr+XfCt6CYr8h85FP2dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
