apiVersion: v1
kind: Secret
metadata:
  name: unpoller-credentials
  namespace: monitoring
stringData:
  upConfig: ENC[AES256_GCM,data:hQvedRNrQ3KW1tjL+kJB2xwhyGxyfrTXxRAqkqt3sf/vd00JHG8jgnw2tbBxdAhhzn0Ux+QteIhxbVDk7YkWkLNAbNttUajsblvl0Wg1+/BwV26OiJNeXoOi8mQlippLJebN1VGEco5yvnMW9hPRdzIGBgsjPkFnjsVlCSRq0A3JbG3XC0i3E8Gql1EJcsEKl4drU6ZC1okre1D8JKklxJyslfoWgTXWyGx72FQT1C/CASUeyumbJEbc7BZ8lXt+KRzCXiUpmiFI3K36nxEaHhR0s6mX87jymB2PVopolFrIuWkZwwILMktOk5bEir25DsRFdptfAaNtG/Qm2Rtx6JGHmV0x0yRMySFDLcL6hUrTvfpN6/Ltb73PQOxxgH6oN0AJ1pc5hNKEgmiis3Sryg58o0cuPohfeImO8VOgMfyZegWCuzWAUozhR8AqE9KMVJ7p2ZFyKVGJ/KI0GiB/fo/ekzmt1unOAxbj4Hu4nUqej404/7gN3Lmzoexlc4jnhJ9krtRR89Uj6wIpCL0ULIGVSmwILA77LjGQcLlwzN5esOBz5KBvPSDQiXJ4tBrqNlHYO7x33nNSPAbgbYI8ZWnfjmnzmxW+hHsKLovpAO83y29xGd39K1URcN+l8QWSlf/vzxOkKAPpLQ+b8ZA3rh2PccK+QtWbd3V9JFOraWHLmMwLqVKVrwxh2ZEnxwQhSlGeM+zKP7Nd3m37N8mPgE3k7YQK/sp/MspGqT257LLhmJoko8183Tlul06CQ/Y3j1OJ6cRu5GsvajhBYYeudcN6FELCWotNbOQXI5tqn4njNODsjeHV1QR0SrXLfCBHxRguZlzF2KfS3+OzgXuB6MKi,iv:g13IqKnw9NkqJJpEwgnBnHSOwhS7xj5gQZzWvEaZgAI=,tag:L9L4xMwa55v5t4h/Fu2r9g==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OXZzWGdvTGRHSTFmbXEy
        VXV4aHJlVzdUejBHOXlHckw3dnR3c3FCYkRrCk9SOUZRODJ5OTBjbUMxWGlaYzlC
        RUNIUVJ3N0tiMEtybVlHTTFxRlJTY3MKLS0tIHpKSzV6ZWg0U01oRmFxN2QwKzlt
        QUx0QldKQU16ak1NdFBRQ3FqWFBvb2cKyOIDDiST9PCZn521kKb90zwZqTQK+shx
        3JkpzHRf6IFiM9X6n5Tp3r5KhKhdlmux0+PgFlNqPSILY4Om3G0bRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T10:14:34Z"
  mac: ENC[AES256_GCM,data:LxZsF8/KHT73OtQsDMLd5rQ9vNQRtwMnuhzJJanEMb3TjbmmgbQRDfoOYAfp/Lll62w/zFyOsHjRzO24zdzFNWWfkm1/dFxU21Gn7YA19wSKXRxZ98+eL/6XsW5+NJBpgxYi1VPphc5UeXm+Ad35kUazUr2x4J1Vm/iCdWMqyzA=,iv:8/b1Yb3nR022rqWngxuseahK6XM0IxB1qS046Dref6w=,tag:GR97uqx+k7ur3qf7v14WyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
