apiVersion: v1
kind: Secret
metadata:
  name: arag-web-ghcr-pull
  namespace: office
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:V3NbQ5s+/JSqtpg2Xo8dkKwQjxNQGoKWnvUcZwKwJSJLgJora/MomyxK3FTPU0Tf3X0eT3KQiE762p8CPxnBPuCQJzpFPgcrOYGuha3cC6xaJcbVm2jLIMEliAF02SVilauiiyQLqsA2iY/tHZlXQSUIwISXHSpoxh2meDy5nOqnKx4I7fKzDhjJq/spEqS4SnJG9BV3tYAKA7pBM3PK19x6pyq16/xiQG15BRXCBTQ5Wa8uBijjHhnPLlHlR3wDrpUNnVmQbiNlnHNM+/pGCWyhUFDTVXcUnuJddbg0i93aOjmE2lWPjraPkFfSTmFCCZwTQVFYrzZVpJqnZl5RlF5IvoQ=,iv:1djIYP++DvZTskqw4j4U5C0cCNEbixH+YMDnPrBkNVQ=,tag:xhNYFFzdEMruFQreDv+rqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWEt4SVNnN1Fkc1ZTbkR3
        RG80Rm8zcU5TdEdPRjV4QVMxYW9XVVE5L2xnCm1aZWtKQzJTUzMwUVNwWEZIaWZt
        VDU4cEhlcjFrcnE5dXpxck9SNld3TDQKLS0tIEJiejROYnV4bjBBTUYwaUcrM3VM
        d0trM0s5V3p4WFQ3bTVxMGY0aFpsSWsK4JEnwjWPfRdMJpzuYphQDJd1inHMudGS
        w3aznS7rtL9b17/fYCPgVrrvzT4lJNbfNaIKtWA3BJ77EbBaY8arIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T19:06:43Z"
  mac: ENC[AES256_GCM,data:MVbdV6KbNchIw2r/yHF0OywARZ39ieOyxSshdPAeNrGYCy4pOtlldjAFEkmmxrob8aMJv40jN9r4kPzME7tONN1eNzpjc9x60QPvqVsuaF+xAcVC14hrZo/4J+7Tjl/b3T2ygKggHQMEhEeLTYI7TLfjDbhAdi5dTZhY5dWHKl8=,iv:ZLQ/szT25H13DmX0UV9EtUzAr68SCCtlMnQqdf4ut0c=,tag:PVsakEIpeh+c/+xVcLhSEw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
