apiVersion: v1
kind: Secret
metadata:
  name: arag-web-ghcr-pull
  namespace: office
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:eFNJR3cpx9h1asFYR6ny3bK2xgWdqGKyqDKdM2vGcFxmIuNIJVfV11yZb35fMArzEJlGq72q5PlytRveIcrpqr85W8nLW+oSX1aEPuZA60iUSwlbEsc3ODWv6sTUpx2IZ+/yNUgYnhGUJLtUMGRLd9BV3sNUdE+8fbno8z5/LS5Z6fw3h1tC8HKlskDczrKdTiYhhV8oS5yz5ikb44a81RpB2nU3s/yR1zdpgDltSGuJRBlI8I+yt4bgsQyZg+Q9nwYn7iXbwh4znFheOXT/3w==,iv:0WSydV11xmlOf5AD1SoN+PoMk0eYvaLGE9tHES59P9c=,tag:3wdwEy97jmZ1emvfo64v8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUkgyNGZqQVRWbWo2Szdm
        cFpRUmpzOWlyTEFOK1ZsaUJua0ljL0pRYkU4CnJoYzVjM2RLajdKOG9xYzVlaUN2
        dHQ5Ym9CSVVidlRmdFpabEZmY0dVWmcKLS0tIDk3MktpczFpUkkxREVlRnJTMnl5
        UnQyeCtsMXNyeTBkckkxeTFhZThxWXcKqkzSD1G+9fCnq2c3JNS/LXtnRfWJWKek
        yzhxentnzinH1gf5fwp/mTCAABgZ4hdi5qQSXf9XQ/SiJnmmgvri4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T17:28:59Z"
  mac: ENC[AES256_GCM,data:GI9D/dufpThfAYMaKbIrZOB1foC77n6vMeNMK8bUcnvwzi2DPMJVQI2WA/aQ0PN/AEgnK1KwH52QaSqIv8qfks8PsjOmMYKGmsvH4j+gLYGgv65a2vn9GZ+MxoOkQM9spDhyuW1HF7LNDN6bZl0qF7F/CKlbM3QH65vg6o63ypI=,iv:IqtC7oxzFadXyebDy0gvrqxiZc30NLqiEkId8yG8xlc=,tag:7WC4+HXHvdmMWD+ExHNEkQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
