apiVersion: v1
kind: Secret
metadata:
  name: arag-web-secret
  namespace: office
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:KTXmsgwQBrtPKpelyEM7yj1UrE/X0tg5ZB7JVMO1HtRaH14A94YjTdtc/6n9y/lYfCAvNJ4G9mc3tkTeCwWoPldrbVH02oC5E0c2Q5jg10coqwOk5dS9sixsC/N6GQ34Co22e05tKrh66lLlNKSB3q6TTX9zMid9kvdOwhYu4MM=,iv:pfb/zHunhEZwEcNiOEX/u5V2X3ZI7a/VRJPNt5ofjew=,tag:PLuUs8balaHv1Kq86i6GSQ==,type:str]
  ARAG_SYNC_TOKEN: ENC[AES256_GCM,data:iDkSpSFiJs6xhLlYojce64kAcRDpI4HpVWFD6XruSkY=,iv:+u6AeWZSvGHrUlmJk6Zy3An2WCS+6migQNJq7D1s4zs=,tag:wGVDekAcP7ESKTyBAwsjBA==,type:str]
  PAPERLESS_API_URL: ENC[AES256_GCM,data:p4Q64YuQGDkmzIVm+TMDWYTEeI5aBG/MZchNhk1qyrS4WF6PFyQbhv5tsEabPZIufltu9q9Q,iv:3Ztv0DhDMV3Wo/85wDSuniW/60ZXLUJCsRPqrWX4DJY=,tag:VVNJlpWNCfGXTunbUyQkmQ==,type:str]
  PAPERLESS_API_KEY: ENC[AES256_GCM,data:HW+Oys10/qXPp1v1Q/jY+SEmfOJ+W4UaG5tdjm7ajgakAiwcvMgJyA==,iv:a3ObyT/VXlwHJTGHT+hDj+phGy3GEoL4p4Ne35fkxGY=,tag:ZT6ifoSqOfGdBtz64rCQHQ==,type:str]
  SURE_API_URL: ENC[AES256_GCM,data:atoFOvnV3vrcvynGScZLopslJb9DHqu+N1+PfTTFRWGXC+yBQDX2HI0NFw==,iv:OZzpqQEPOvY9kleEEw4wI2JlwHA+8fqRlmjR8vNY28s=,tag:5tIGnlrCyMpQj28KwPFWKw==,type:str]
  SURE_API_KEY: ENC[AES256_GCM,data:USmtI8y6cslibh1pjM8JNpBoicX1KoJ0OAFAKcEwoRz8D/xp+uQSpDEBvUMC1kjJTZn/nJ+ZF4aMsX5PIpXTog==,iv:wj2NQRZk6LPSC6h5uQrpBu2NP2h00Egsf67/LN6H5Sw=,tag:BMtwGLDTisQiHrD1aRmyQg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Wk1Na05ob0VIN244L0pk
        ZUd5OWRxWGRRdko3Y293Qit1eDJtMEs3TXdvCmtLLzZ4RVlmTjVZYUNhSFMzZElB
        VUJlT3VYWlc3MytCd1ZQMUorNDhrMFEKLS0tIDFpbGNtU3BYYmtqVTBPZWI1WUgx
        WndVVnR3enFhdVRObklLeU9oYmdIZTQKbKpf0h9E3ciQhy/7u3Hmw461lod2vd9I
        F6S9j1BhydLVGo10F+CxU/0FEqaK6NZb8N7/xpjVWkXVjlRb5c9CNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T06:42:29Z"
  mac: ENC[AES256_GCM,data:Fmiah5CIqFwHM3dFHsYMu7IcK0Lq5zid7l1+ol5qjFxB12kaBczdE8xN6VNKa9ALFwdIZ4HEc7C0BKCa7oDbNfaMd6bZOpJLXvTojpZkGBV+pvYN71on0yCLvbefyJsMs8N6Y9Y6dbY303kkCJ0MXBUVff1YwqBe2xEkKWjXgBE=,iv:eEHbTUoDEBewzcqqcigZazYWUUkYh1ocwejv7cVg8Wc=,tag:p2Q1nuYCFviOTB7oX2NIgA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
