apiVersion: v1
kind: Secret
metadata:
  name: arag-web-secret
  namespace: office
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:KTXmsgwQBrtPKpelyEM7yj1UrE/X0tg5ZB7JVMO1HtRaH14A94YjTdtc/6n9y/lYfCAvNJ4G9mc3tkTeCwWoPldrbVH02oC5E0c2Q5jg10coqwOk5dS9sixsC/N6GQ34Co22e05tKrh66lLlNKSB3q6TTX9zMid9kvdOwhYu4MM=,iv:pfb/zHunhEZwEcNiOEX/u5V2X3ZI7a/VRJPNt5ofjew=,tag:PLuUs8balaHv1Kq86i6GSQ==,type:str]
  ARAG_SYNC_TOKEN: ENC[AES256_GCM,data:iDkSpSFiJs6xhLlYojce64kAcRDpI4HpVWFD6XruSkY=,iv:+u6AeWZSvGHrUlmJk6Zy3An2WCS+6migQNJq7D1s4zs=,tag:wGVDekAcP7ESKTyBAwsjBA==,type:str]
  PAPERLESS_API_URL: ENC[AES256_GCM,data:WkuWopG+yaeCclpEmgQ6a2TTwe3YAIsO4Pl0zquZvg4ngIc88qz8K9ErO2al7RdTvlQ9,iv:ULBZ+7l+mbKijmRHfhRqbWJCd6dskzolu7LbBjN734I=,tag:DLaeWLIumx6QmoXlOUZ52A==,type:str]
  PAPERLESS_API_KEY: ENC[AES256_GCM,data:aDIGct1B/U6kUrKqTU3HKt8x2Y6L1G2KUiv1G2G5RfnjzTQm4a9sUg==,iv:w2E0Ka85zJXPiZlb39cPAaj60wr285scYL3Jyh4Sev8=,tag:/OBisdQULFrFp60lI0k8vw==,type:str]
  SURE_API_URL: ENC[AES256_GCM,data:atoFOvnV3vrcvynGScZLopslJb9DHqu+N1+PfTTFRWGXC+yBQDX2HI0NFw==,iv:OZzpqQEPOvY9kleEEw4wI2JlwHA+8fqRlmjR8vNY28s=,tag:5tIGnlrCyMpQj28KwPFWKw==,type:str]
  SURE_API_KEY: ENC[AES256_GCM,data:oRFYx07mfBt80HTDoTgRGhPYkD3CH6KNkF6gxlL3U1XDSTUJll/DPFuzfVdKLZYYUcpc4wMaeLo3eSA652eGSw==,iv:gKgCUR8r4TpERViCaYAkwh5Po/FBaykILncXJ0PtLJE=,tag:fQe99SLeG4B0s7zENX/psg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Wk1Na05ob0VIN244L0pk
        ZUd5OWRxWGRRdko3Y293Qit1eDJtMEs3TXdvCmtLLzZ4RVlmTjVZYUNhSFMzZElB
        VUJlT3VYWlc3MytCd1ZQMUorNDhrMFEKLS0tIDFpbGNtU3BYYmtqVTBPZWI1WUgx
        WndVVnR3enFhdVRObklLeU9oYmdIZTQKbKpf0h9E3ciQhy/7u3Hmw461lod2vd9I
        F6S9j1BhydLVGo10F+CxU/0FEqaK6NZb8N7/xpjVWkXVjlRb5c9CNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-16T05:44:15Z"
  mac: ENC[AES256_GCM,data:RqTpFBWt/mzsxwGHz4Nn+cfHFjLsrLXv60vvHu9hSTzZEla4RE44Nj/RYtsqspn2pWd1yPGosAkWPAAWTMcOvrBRIJ33xfXFrUdWPwnZ+lmIHdqiejAsJeKm4FLXdqkCUvMi/Yn49dx4kD5YM/oXjooSuq0sLh/IIgchzg/Ax5o=,iv:aIdR6VOP89ZzqhcY5wSZUSmuzVshqF0SlWOYTF2pY80=,tag:MyICS7SbQH63vK9Qf+8Tsg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
