apiVersion: v1
kind: Secret
metadata:
  name: arag-web-secret
  namespace: office
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:1Clea2XMjiaPESChYV0dGtQRuA/Q0rAo8/ugynkgUZwVkR8BpDRr5iptdtK1sjpxVhU/o2SHJZ8PX4Ykp1bQcdu8wSjTwbGAbSDZSkzjpdD5jCNWbGJtHznWxtQ8Xq9C21aVayNLNw0EExlJJU562cy/onS1rrZOxYAa4rXNhJw=,iv:60BaQUaPnnd5D31+PnZTacPlPC4wAUbj45L3Ee4hxjw=,tag:PTy5w3GfNTD6SmglQGadHA==,type:str]
  ARAG_SYNC_TOKEN: ENC[AES256_GCM,data:4QEyDps5lxeUZf9bWNfvpJoo6HFgMXn4rFNsEVvDruQ=,iv:JYAHPMdwIX0m4JKRir5WWDiSmI/Q33QkCorkOQvKcJ8=,tag:x+/NkaY4wbXfeQhRrjRafA==,type:str]
  PAPERLESS_API_URL: ENC[AES256_GCM,data:wtG3rZY5/cVDM/cdavXVPuwScQcxej/Oqk36ZX1zbR1z7KClYR2+n7YRbvZx,iv:DrIh1N6yYe4vAy8bcPs9L4UOGaFoXaWhUndKQmCEd6g=,tag:7ouHj9wy3MOdMjKXSG+U0Q==,type:str]
  PAPERLESS_API_KEY: ENC[AES256_GCM,data:zjUZOpSRtx7svhk5dinMm3bEY550z7/hdA6M4jZtCFnXpLMS8LC3mmzVnw==,iv:iQnWEQuPFgzB1bKuQQ2dTrR/kAayKj1Gsd6+NSopCgE=,tag:uzsFL4D4Sbk9wCy3EWcN/g==,type:str]
  SURE_API_URL: ENC[AES256_GCM,data:YMJOk4ZTtpB3hDZck+ZoujcXMjTn+Oqb32FGx71UWn6ZO32EOCt/rAdoJw==,iv:40monkt4bnyxMdem4tWUfxqydJUafdBiHkLQUEQFWfI=,tag:Xh1+Q09slvYV8mgGookAwg==,type:str]
  SURE_API_KEY: ENC[AES256_GCM,data:JP7Qd4avf+Wmh2f1SuRyrk/uIQdGWnI6fbegICQsyxHf05rSt1o=,iv:CSfp6VIQA573ZZ5SEuNBQ8N3swvPxzy0YptpXTxV3No=,tag:WSwbBET9r1llo60G+fkk+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRGEyc2JnekZtb0VnaThZ
        bDlPYi9xd1N6bTdjcmtDZ0ZOQ2p4cDh4L3hRCmZZZ3RkVjlUZ0NJcHhpNXlRMEpP
        dEcwZmlQZXFJd0tCZUxPMGsyODY5S28KLS0tIDlpNGdFVjNCNmpLNjVVM2NreXpP
        djl4V1VWUVdpaURhWWl6RnRadktrMHcKy6vOTIjkVZasA3q39yZIy3omJyZWp8hG
        Z8MyS+eLEzsGvJ1x/UAMH5mDY6T6E/eF8Sfu1EMFbIZSZB7j2ubtjg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T17:27:56Z"
  mac: ENC[AES256_GCM,data:XF5Iso+79Lyyek3NYIAR7Qphmo+lGA8fMA9yYs1I8H5HKPXpdfy5VpaKb/O5oQMRWV5vlx/1dfELwY67nKTOI9x0ljZt4wjp1IvRiBBHDDOTN1gDBnB8IXC2o5BBx7WmuSqfwO7cLRn2bHyom/Fomip68PeFSw5NDvlYrPFJvzQ=,iv:TbkLdV3O2ijh3uNjtm1fPEeY1qsttRJOQODHLN737os=,tag:IYjC6cAFlKUxuezWWoyqkQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
