apiVersion: v1
kind: Service
metadata:
  name: max-jung
  namespace: my-software-showcase
  labels:
    app: max-jung
    component: web
spec:
  type: ClusterIP
  selector:
    app: max-jung
    component: web
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
