apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: globalmobility-group-gmbh-globaldispo-fileadmin
  namespace: my-software-showcase
  labels:
    app: globalmobility-group-gmbh-globaldispo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: globalmobility-group-gmbh-globaldispo-uploads
  namespace: my-software-showcase
  labels:
    app: globalmobility-group-gmbh-globaldispo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
