# PHP tier. All three PHP apps read DB_USER / DB_NAME / DB_PASS - a different
# convention again from the four used across the Rails apps. Verified against
# this app's own config, not assumed.
apiVersion: v1
kind: Secret
metadata:
  name: globalmobility-secrets
  namespace: my-software-showcase
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:CwPUeIEc+0tSrfA61ZuSzxeX+31nhg/oezPG9kIVPzoBmHw=,iv:EwpP95yh61lGZqrZK8oc1/EMilEa3MzLZg4lGSY9YiE=,tag:L8KnUn+eJLnV2YMn7B9FPA==,type:str]
  DB_PORT: ENC[AES256_GCM,data:fjsY8A==,iv:hm3s0Dvqw1cciPSFIIifkGF/F90FE9yA/2M2iteF2rY=,tag:b2RLVlBVvWx5GCJHpZCsfw==,type:str]
  DB_USER: ENC[AES256_GCM,data:KNUzpMGqPBpQeDsRmWrJPTOAER4VmzijhMf+4g==,iv:ikq7u8MmEDOGyFvS7LyKZred8Jpvy5wEY0TzjrJ9yhM=,tag:St1DW4jBIMgS7m0f8IGDBg==,type:str]
  DB_PASS: ENC[AES256_GCM,data:Asi9qaVce7BQDhmseQkbvFw8kS3LDhfS,iv:QW1TXjF8gFtW+sYsNLJnl1c9yLomejuMs0VwGSUPc84=,tag:3iDuKauHvS3dhLmJiMUOLQ==,type:str]
  DB_NAME: ENC[AES256_GCM,data:vBIB1NjyrUi3xcP5dHFOKVFZOlJ4MPrsMTatew==,iv:qhcTfu3NXs3FXN1UxZsLrZAOF/55cuc2x2xIoZYk5x8=,tag:zta3rpYDYWaXk2piqm2U0Q==,type:str]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:rUM/YXhctslKhxgmKWpinEcnJP1nbxxGpAEgZzfQZBlKzOglM6Vm3Tx3XgAwaJjbEyPwT5oXVYtn8fJjoYMJcA==,iv:NBlYWb9hHmG251G8vs2fUGAtOuxcXUmeeX7RK6bqX1w=,tag:8Y0DRQmqcfP3OULQKIdSww==,type:str]
  TYPO3_SITENAME: ENC[AES256_GCM,data:bqSZieWActqgp4oUrpcU,iv:BQ+P3cHn7F0iFH+fVULFTSgJbTyc26HS8y0osxNaKqU=,tag:nVbkQxJ228xReP9zvSyG5w==,type:str]
  TYPO3_WARNING_EMAIL: ENC[AES256_GCM,data:ieeUfNRZo7R5adT8CRxfMInlnnw2,iv:wqIyUKRIY2CJp01g22eFI3eaSp9VlgVJfQq2nANEFGg=,tag:a6pAU2rj//Gifj4KYAsgEw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscXhKOGJaQjlqV0JpYkpz
        RmJqQTg2VzJrcEN1M25MTHZncVp3cHk1REZRCkpZZ0g3Y2pKNUpWOWZ4a1FidFMx
        OU5aTWkzVXdKc0lxSDZGaEJFSHQ5L3MKLS0tIGQrcFBGRVowZjBzK244U0pDYk5X
        akhYSDA5TjQxbG1hK1UwNXdQbGswVHcKFE7ZHuStZr2cwrwYyxcK/q/7HOguuOpF
        d/2MoIVewt7ODG7ziDY0tIPue+Ooc0hYsOYHMSo+ynY2wGxKCVzvwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T12:24:19Z"
  mac: ENC[AES256_GCM,data:c/mGg5QrkZHAS8ttTk1LQ4rqlPkJSfpJJJ/izx5k2aVrlmyW5wBazaPhl76JSam9UeW09+quBQnsAbdI/XyXJ4OlO2qnTGSVWw8SYHP+6ZIVefqkPiL1qJmKHr3WUVDa+WdLct6nQML5fyqToA1HbOT2nEGR69hHCAXSdosTbd8=,iv:DiwNBkegBTgCnJGTS43ueSOng99j2ndAO8huaiKCeek=,tag:fqZ/WJXGnnAcyPJ69CkQ8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
