apiVersion: v1
kind: Secret
metadata:
  name: globalmobility-group-gmbh-globaldispo-secrets
  namespace: my-software-showcase
  labels:
    app: globalmobility-group-gmbh-globaldispo
type: Opaque
stringData:
  db_user: "globalmobility"
  db_pass: "CHANGE_ME_IN_SEALED_SECRETS"
  encryption_key: "CHANGE_ME_IN_SEALED_SECRETS"
  install_tool_password: "CHANGE_ME_IN_SEALED_SECRETS"
