apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:8fz9vB3Mnl91cqLCW/l61Vg+CjhSLMO27UanAZEif+cEhCwcjuBO1ONrQjHYX+0mofe4Edk/jn8VLdHDxM5oFmE96w0OqkOcMDIx3L+SsiLCFxpWJJbTBsD3pHcupMaelelTIFp7ei6/r/djZIjMWlTJySV2nFFXGuDnAFNtOPHfmED6OCazMh1pekcretOxqNRmJfP4/Gy6l3ipu2yCbM0mdTwF1Hnc/51YBARhK3PZfaFNZ2q9KX6JfdtV0QasT/RzMM7KTSIAIiDQCNxwH4t5Np6ZEpsctuqfCmUmAtugjQ4v7hmel9j9B96wYrsFGWSU8S4DhEY07Z5uB03J91GR3o7YTQB+9JK/49qw5oqNetdXWgameRy1fSRGSdDPNz0e/Eh1U3US+EYG1w6IY7jV9CdNqFU2OufaAAlgEk8mHTaraL3vc1LpWh6YZQUNqPTBJyNLXsvYK99rnSGb9o+267u7G62urcXd88yCmk1gbIWaxsK4l4vZxEIfDS0ZYWRXYPcWpzFMqvTF5LFoEu4lopiDiHCmIjV+kLa58Mw=,iv:D6rsusieIFnsy9fQugf7WUAoy7tspn54TCZYrNy+U6g=,tag:QF8s4cn5K+etsGt20wJXIA==,type:str]
kind: Secret
metadata:
  name: ghcr-pellet-pull
  namespace: home-automation
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSHQ3cDNGYzFGNGpEM2RP
        dy9rRzI4RHBsbnl4bnRFTGZ6Vkl1RXdDdFd3CkQ1VFM5L0RLRDlsZTFIa2kwaDA2
        cWxyeEtBNVlxdDV0YlU3WHUwVmU0WmsKLS0tIGRySHJmY0cyRkdGNnZlZmlRZHZk
        aDhNNHNQeWZ3UlE1OHQ0dml6RW1KN1EKibL0w5Y5rFLoJTTwk0GWhr4pYl00cVTd
        0NBhFr5TMeOaku42dJL2GIIkFqdTdDssOWZPbS7TwxPC6ZjOzFNj9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T18:30:55Z"
  mac: ENC[AES256_GCM,data:Hji/25bsffgLgHiOE0wF+AScan7ISlXj5UgXEwhDX2DpFb200yy38OsiBzd4oT1vkfcICpk8em/trjFKRmIoAjX3uLVNYhuqkHDpCAX7BP/0l/WLfEUkihUdH9YQElds0DOYAKuN+hDez/shZduf5X+ZIXVoF64n3OIse4uGxZ0=,iv:/VNcBhlLyLpH4So8B9mQipRFR6xjCoBIcmITLJAkh64=,tag:v8Wl/4y7A3XGnTn5CCUWOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
