apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:ne9zQir+e5QjL/MrfK8+rUWjkG72nLt0NvSMPzW2m1HOqyde7xVvIpefTKGREo836qpACfH53irSyAlXyLzbyccia/Cz4m8Z+Ri7NDl6AQkhw5ONd4UCcn9HWFuqs87FeIIJDusf19PJCWmQWE/a5yE2UaTVV1maUsr8ZSCxJPBs4KH5wgxRB7bH16ZSyi27JAPQNZqiaGlWBycF0KYl2EitOKIsgRgRvI5Jmdrec8FLfyVLv7VbiQPuGf9QKejukmQyjJhLo1xItKDuCqrmDWigP5EwR+UaGeLjYDonoZiquYAv4mdq/i6jIft9ml2o40nMpdKE9J0=,iv:NEF+4u12SOi0KX0Ql43YGgsMSxk71ivVoSUJCqHG510=,tag:lmJSObGDMa1w6pyE7FvZYw==,type:str]
kind: Secret
metadata:
  name: ghcr-pellet-pull
  namespace: home-automation
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWDE5Z1J3NXJBRkEwZ0cx
        aUp5TmhoNzNGWEFBakhCSlZaZWd3QW5ITzBzCndxeEVZUDZUbmxjbzRGcGQ2STJJ
        Uyt3ZXQ1a3JWS2xIRFgyUHRQSHZsdDgKLS0tIHVHNm5UMjgrMTlxdGxZRFFKbkdS
        RWI1czJtSmxwT2VnaEEwZHlLVlVKalkKqoCzzrg4NzRvQXHKHSUFeH+Fo8CG+Bsv
        k+oaikZMz0yHI7Dlb/+NwTEEvF1SYaIsmDwe+Vk7DM9xrKN+Yqga5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T18:39:02Z"
  mac: ENC[AES256_GCM,data:iDFihij+OQYckrt+HkE+fbRBPah26trXY5Pu6huxlvKQPC07e+5hw1e078jHd1H/nO0DAkzqPW4I8TIerYLKN9E7fwBr2A6q7QejD9sGmr/bqbqJSiQ8cIMqudywZfEzbpWaTep800xUCiiMpQlKWYqy4WunWWF3x58E08BdevU=,iv:mT2P7G0mQ89EwwlAUYFPu2vMMQ4w4dbpPTQtuxGoB84=,tag:01BGU+V0GHldQ1vwN6G8+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
