---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./imagepullsecret.sops.yaml
  - ./helmrelease.yaml
  - ./grafana-dashboard.yaml

configMapGenerator:
  - name: pallet-price-monitor-config
    files:
      - sources.yaml=./config/sources.yaml
      - signal.yaml=./config/signal.yaml

generatorOptions:
  disableNameSuffixHash: true
