apiVersion: v1
kind: Secret
metadata:
    name: pallet-price-monitor-secret
    namespace: home-automation
type: Opaque
stringData:
    PG_PASSWORD: ENC[AES256_GCM,data:xrE9YKZfyinNhaNlz86gQa2fGw6/jDDNCxIy7yg=,iv:pVIHfbCvku6VhVZP1cTJ2Xb3kj3U/t1JR2zVzBbzN2o=,tag:wOGiXjOxU5YS+sMFenp4KA==,type:str]
    ANTHROPIC_API_KEY: ""
    DESTATIS_API_TOKEN: ENC[AES256_GCM,data:JIFPlbZ+R9IxzVpBEYvucL9sD3lppvYaq7x/PHMBVJ8=,iv:bTqEEoZeiUB+tQbmENrC8jmfWf0qkntOrR10oCxQyYs=,tag:R3/KrUwLtyAlJXapTJ+48Q==,type:str]
sops:
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQnJoVXJKYTZyZ0hpZUha
            TExSeDY5cnk0VFYzYjc5U1ZCVXlXZTA4T2g0CmV0SyswWEFLVzBiQkc2dVpYQUFP
            ekU5SHIreURwSXlxakNleSs5SUdibmsKLS0tIFJYdjhLSkNrVDlyYXgvUlE1OW9O
            VXZiYjBBVGVGcml0QzBOd1F2dzFOeEUKBN4DRm7PU9itWSRzssKE9Ix6mTN57oDf
            XP2mgURYjCanV6xIJisRg5/gBArdZ0Z4pdTt7Bgve4O4BbiMpFxxoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T07:13:56Z"
    mac: ENC[AES256_GCM,data:ohfwhPcTV57/+NC6WjqR9xvhCUBVUDbfyB747/LeRP07J/dpMAfswdOKybHW7O6epiH0IaoJRX9QJRfvHvGeQJZTBj+4NZTG9xOrDqpf8EPb+oCDN2BvtbcuZWC27/nT6ZXyoSoJCyIb0Lc++1lr97QIoQPCNOX2z8dSIWjQ21o=,iv:w8z/JJU9Nm/L3S+ZEEIBgoApzXrWvjcyqpLcqULEBE8=,tag:UEayYIBrP50ys/YcyKQ2hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
