apiVersion: v1
kind: Secret
metadata:
  name: librechat-mongodb-auth
  namespace: ai
stringData:
  #ENC[AES256_GCM,data:jmQYdV5blQu/As0U3SKs9d1zI6/5Nr7IkPiHQIMmTfPbTMwWi9jQKZvrRmelhpttRLABLhFoRw==,iv:NovI+Ws81xoYNQmbWE/GCVgrAiCeoKp/2gKuGJkdMg0=,tag:ospRcRl6nnwEEl1VZBkEdA==,type:comment]
  #ENC[AES256_GCM,data:+Y59eVwGnvrk0VHyMvYFbzcsAC1v9ZdN1d4x7P0CO3ygXTESQXyHtXDli1X3mTRt9bWiapCmcd2vnJFlmjSOk3Q=,iv:jYUJ6SRyP86PGaFRFGSeHpJVAdnVG+gMEv6AdqruUxk=,tag:RwXdVvCjP8Xf0YjdCNIuPQ==,type:comment]
  #ENC[AES256_GCM,data:F0Ynp+9cJ8rsYOSVHfCZ4cNX3+CrjEqX6OMzVfMQASvkTPAG4sJZ7mZ5xti97y5Kb5N6c5DQgDGpNkWnsnxiOPnh/UU=,iv:6Zzp/35It0D5UPEhn8i3prLmNGeTtywZI/6p90JeIvM=,tag:dKD5DyFHmf/FFpE1/XH+7w==,type:comment]
  #ENC[AES256_GCM,data:0frK4Hf7Oc2Mc66XwIcSObVJj7UrkxfsbvJdy+VvGIup+tYYsa6eUXdewDTlHH296OEApNIYf8vmt11zNr/WuBM=,iv:nSUar/LOrJMeAs47jOZC8HxlhYPgbaaXQAT7MixU7Zw=,tag:dL5r1GpAXNRCw+r9HunhKA==,type:comment]
  #ENC[AES256_GCM,data:0ykAq2xMb9t/fNdL7T0rMqR5wmTCUVLiSlQUztFi5fGSFInmLQMlm6oMwLZAqV8dkGJfBsycGGUX8Jia/nUa,iv:q6Vfkn4AD8Zyp0QnnGoJfPux/Z3sp7ZSL5433Jfgz/s=,tag:d03F8c6xYdYFVzaUea/8mQ==,type:comment]
  mongodb-root-password: ENC[AES256_GCM,data:XwM4z5tlKjbpvloBxC72O1aPR3V7NFAczXC7bm2CFwN8+vAMswWHpA==,iv:7LwYyEJZKxE7MPdt5DslQgm/ECVkBPtX+wCXmFP7Eiw=,tag:KnMkE1OzNA/W/FV8Sv/eLw==,type:str]
  mongodb-passwords: ENC[AES256_GCM,data:rKTkgszRgKaJi4fxwAx5f7As80zD9eYRyS8LJWH7+7pXY3yAA7I/Rg==,iv:hFLsJyoWNLhYgEmObQvGfmgF7Ia7noyK+3aTB0DGt9A=,tag:id3AislycSI4PXBkDb7UDg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eWYwV2JQU3JRVnY0eGhC
        TlBqYVlLVTNRTmd1VGVqUUNSRWJIaC9UK0ZjCmdqTWt3K1NJSVZZYWtubXlnT2ZW
        aHFORUhCOVdUYnRNeFprWlNSQkdQTm8KLS0tIHhKMSt5SytPSEdDTmNXVGtKTE5s
        d2FhdlJVN1c2WXE3eTFuSlROK0VEUFUKwGVnIvXysfogvXvpNfIyOSsDfyr2RE+A
        C4tp1vp9UJAfwHoVLQFILM8RTMtPp6sXvzXM+7bfhCTGszvvkjJ99A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T07:11:36Z"
  mac: ENC[AES256_GCM,data:gyLPjGHNNubUVNdORVl+emDF1299RNtZwJHQfo/5t/vjuGZzBMne4hX+ybJMBsfHXpKqSKlAl17HLJy0BWnzlTC1XV86zXS8WX/nyVYetZa0eGBsoalJYSRdYm7rAaJ0N2qnpb8eNg82c8CrAkwe4r1Qt1GEJqANtGBG8ciGXkM=,iv:mbtwyFM/WOry12X/3ihspiGn8Z219wN0WgnGVGXVIt4=,tag:GOSsrgayrejPvIxs1lGYzw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
