apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: ai
stringData:
  CREDS_KEY: ENC[AES256_GCM,data:9x4O+Oybcx+Xo7EfAATfo/+ikdwDhyB2gUCaLL3pYBy54q34CZANcvHgVKFoDFXY8Pg7PhArcLcbyRmNxTFypg==,iv:/j4y7J6wyKeInC5hGpvpfsJsShrQGrR7wN2uVYshMTs=,tag:Z7OL6YwfpiDu8riucdIjLA==,type:str]
  CREDS_IV: ENC[AES256_GCM,data:0tlqWEWkUDKukur14WVe2gPW2GJCgaJyEh00ZYycB2o=,iv:Z5RUG2Xs5AVF4qg3em9Q60PG3gOyiJdruUM1W52ObuY=,tag:t7u/TRB176ZxmUH1CZAMbg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:gsMCLJoNvXT1WQ7aDkiFB1zUxhfqY4fabL76cLzHnXhqRb+OdpuQf1y6yB0=,iv:9Pf3xEpurO0ZgI1X+L1G9O3+QNE/Exlertu9t1XGlzE=,tag:VofYsVps1a+3RjL+sYJi0g==,type:str]
  JWT_REFRESH_SECRET: ENC[AES256_GCM,data:O4BcD2iCo7FsAbjVemd612tXvCTLp+eHOVqlFLxMh49HBPK5pfgaTkD4lD4=,iv:YSYBbg5N2uK7Xmt1+4N6LR7RS5ZlabsCZ0oKjxNvuO8=,tag:QVNSoI6tTL79ugP6lRqlXg==,type:str]
  MEILI_MASTER_KEY: ENC[AES256_GCM,data:yYZByLBOvOlBpHJic2Vfb9i2PnIIWQndtVvvoXJ+YGMzlBd0xiKi8N7G+o4=,iv:L4nvox3O7cqwH+t9ks0buHRTBcrWQSjSxz7O6rdcOgA=,tag:q3bkJ2m+LRlcVnWblqv77w==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:Prcm6ze8wow=,iv:xuQOa57Oc+bs4MtyfXxpTrsuTz9OlHiqtcqO+pEz4jk=,tag:rnIJzlTnmw7a8hwzNwxSLA==,type:str]
  MONGO_URI: ENC[AES256_GCM,data:mCBF63H8/4nzPYTvhNGvsgTxNucJwx2avdbW/qcF4kbb8zQTJA3yRuWyvTWVjz7Lp10gd8BpzagvFFpAYV7NMXzhWUgCoPRFVvvjVUz/LPj4IE10nM4fKLcibaGj2BbMuJ7Xci083LgxFWvIRbS6sMzguQ==,iv:y5x4KhiTHjYTTsLn3K2Y4wHsqIqaRkK5BR1sGTJ3lQs=,tag:rZ6ijZGxiEwrGgiFaKX48Q==,type:str]
  #ENC[AES256_GCM,data:z003fCMASSh78IiNfaUYTqL78vejuxnwmMPQ+3hk9UO0qtC7Rb6+BEINJOQ2AYwvF0MCDaXDyvoxd8MsPzWh9kVILw==,iv:t25O5JfUmwy62Mn8sGOzBSc/IJ8cVl3XemBPVbjGzsE=,tag:dyjV8yAOrF7ClaiX/7f0Pw==,type:comment]
  #ENC[AES256_GCM,data:QPT0WwksKl2kIv0DCVyfgw2VorBE51eVHXiVGKaRWjU3,iv:2VDLjm1JFfyI1OdbDJ/fhRv7Ri80J6WOnTJWEfbmjhI=,tag:R+00HTUoSyWKfZPZXy1F0g==,type:comment]
  #ENC[AES256_GCM,data:3J9VzrYy/Ltp+WE4xEIHabQbshWzZSjX21+/CY4zsI/6MFwZkLetJ0Q=,iv:EWNKeBk8htBGoUIFIN+dSKNWu5NHym2CbrnBy54VlbQ=,tag:uTpjht1uSQBubOPE8lNMdw==,type:comment]
  #ENC[AES256_GCM,data:3McPjKTKpziV0Rop49md0Rd01bmHdGIBvIgc56S3tzHCUacKLMyjnEET+itGs4M5UPC3MyFOLM+rdQV8XAK6T9KTshOrd2ay6SYni+9I,iv:0jsJiomL8M5MU3IKz07gIjJ9j391FXZHHaa2wFTkVfA=,tag:e9AWDBYQShEgtZiF31lUCw==,type:comment]
  #ENC[AES256_GCM,data:zq1n/UCOR8Fi/ZK7Nv0fy37Y1jymU9SVpavV/kUeryy+83DZnQcVxVBtLb4Ci+rzvpW4jcoPS+ur3L0DE70FlGtirotWBHiK,iv:PozPjeo0t/S7vqtcXMe3POA4QISovZi6c8in084Yx7g=,tag:tFP728JaEIYBb1ltlKaKpg==,type:comment]
  #ENC[AES256_GCM,data:uHBFSXsFWaPs+SWLDVq0mEA+u5JeKKajM5n8dNXL3CtxMO5dmN3hs5BoWxAwtU5nUOXOWPxUTO92dw6y3KKL7sBtjXURR7whGmga,iv:tsvgQ242fDoA5DcL9l306VafA/mMO52Vjguqzo5sSZE=,tag:C5y4dFBkoHanHokqbmlacQ==,type:comment]
  #ENC[AES256_GCM,data:RqyyTqcGed50fBAuH6z2DWNEotqcV1YX3rF3OhB+gPkXHpfAm6UeDlX2pfntTlQiWfotOMXwGSsLBqfw7/RzYLskcGAcTeyKO5ggOw==,iv:9coO7LZoGd0qe7WcY+n/+agqi6nEn4u57Dr0ASea+Ds=,tag:hB4q6L6xUxmTP7ZDqmGJJQ==,type:comment]
  #ENC[AES256_GCM,data:k/J93ouQzLAIQjcP98ThgJq2BuFNDgrFJxb9mstT/hzYP5bkrziLUa9FR0YZ5hoByMTqJMXf/E7qxu9gX+jUGz6RqSo=,iv:XX2KgKBuRijPjQ3FF8bSAyjKCM4UCTgrV/bssnQScwE=,tag:6kn4qPzhV+FmJl2dbrSbCA==,type:comment]
  OPENID_CLIENT_ID: ENC[AES256_GCM,data:mbUKe9kjOtFQAFS74rurG/pTltNlN07Fdz+3g97Nfomhp4KHXSicDNb0bA==,iv:/aybRjBADyynoNFd0eOMFX4kbTtkVoIPppJEbv5CNf0=,tag:yFexaI0HPvhD9te03cAk4g==,type:str]
  OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:Bjz6KeONZ/PiE2PwDSzV5lqRVcJt+En953wBmVpjTo4L5J86JcQcXYfPECRul5sw25f7bV4t3844oRo1wjFeVV49VxIbM8zxx+eJ1ARdXcpCTPT07zoo98616+ydTpMnd+xo9qQ5Bp5VO63JodPWH92I4K2V2Xj80CE1mP/dDN0=,iv:KuceX1wD47IsIM2voQSyqkjE7dD0v/W1pDfXda+Vtq0=,tag:V6MGHC2cqPZKKIY4m/BBHw==,type:str]
  OPENID_SESSION_SECRET: ENC[AES256_GCM,data:ZEa4smuIDIfkTYWvjQnbef8HaEBxlBonbwKPDqmRDThnp2kn74j9mBIvyvryL548oHmocLuBKXwysoIgI5YlaA==,iv:ZBfb0d+rpgiDPqEMaqoRXgtq9OGfSlbSHVnwFNv+h3Y=,tag:4BofZSwfigmWSOk9w80VDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UW9KY0c1enFBa0pZY1c5
        QTlkZlFtT0plQ1kyaUJISjJnSWNvU3lYNDNrClpMeW53cUNKYXpMUlFheHRlZ0Mv
        ZUtzU1lnbWF0ME9aOThhSDEvQ0pWTW8KLS0tIGg0eUJaZlh3YS9GUFlML3oxd1c4
        MDRPa0J0djRndWRCZ285alN3YVU0N0EKZqIfL+z3Zr6wCFtwv8K0IdYm0KsbWoeK
        edmWC2g+oyY+oYUn5urrBF9zwHZDDLGSgEto9gLuQLgry1TUasFRUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T08:42:46Z"
  mac: ENC[AES256_GCM,data:ptiNCxXa8nBcYfJSeEz7PPLnZ1Ki/lzbx7gsoJp/jsB2uICYy/pvCSO+tp6BCH41I7xlU/KPUQHEeyOiabBtWeRksLgVEDHoEfbhK5AgXj1ChRGDHzp107mxbxIloWNJZY0WJlL33+bVlE8jvdT7opJlC3kD7dgXpcgfYSVx37Y=,iv:BboiGszR2xPlxl7tkbDE1AoC+r0G0IorBipaEx1VzIc=,tag:4lcQ6DGnxYlwlaSwAPkQ7Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
