apiVersion: v1
kind: ConfigMap
metadata:
  name: icloud-docker-mu-config
  namespace: backup
data:
  config.yaml: ENC[AES256_GCM,data:35LduBEnpsMxcAXMuNtZPQ/9uhnlc1c1IK2azvLJTksXDWZkh1Tt7rm8uwV5ECvqHmpdR19wWKeAA0mPC/HNWCcsxFv5ZP2W+8k0dT018Ja15urmSEHGLmUv0EH/QcKzJ47ycUIvBc1omWnnq+2lmn04xxrJVc4MojCiI0OLRb5OaTj1j1y7nc+iATT0dvMstQC+v0nolfW4Utd/Th9wMFyv6VoA3cSsWSaloZlHvKiIoB+ZrkVuTpAgRjyXZK0MXztpCXpHeRXlc6nJk1x+nZW/QFkS/2WSA5q0mb3ydOS5dpPYOVciU1+IC1XKP2AMurDGZCCHoeDjqL6vuWh0eXZfxN5nDHD5yO019dj6qfAJTImDkrxM8j7xJuX/gmNSSWiD5lYSe6j1CCwMSpE6z4AmGg++kg33uLeUcub8m7AlHKn9NguAm39oLkbBELryOyndNJ/BIzqa6sRJqfvinQk3mRqQK097zDwmQLcQLZvnDoSrvlw5gH1jo81mYsGoyC7BhRtzNreNqaigsFMt2j/FfyJFFw/7XcYUAPDa6BsRt/D5cBebVUGrpIiYcs1ARC4LmiS1A7en+7y9bvUK6eApx9jqglLCO9/Xg9ckDu2qc7eEOX5dNNL8Ae7/T13cPhkWBRDg7YkanWB0nAv5QNNzysc/wN9f4SvuFXKOy3pDnExpOEUXHgZpSNqzlJ6I6A==,iv:F1NHQ6lAz1msL4cfHDRv6BUUBJqGCifQCvXByt7gvDI=,tag:dM48xEv1zSJ193qVNwv5mA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYml3REVIUlg3ZDFUMjBD
        Nm85c1V3cHg3RnNTSVJZUGdpZHBsVDUyYlQ0CjRxR2xUZkF5UVBKdUFKc3VPMEFW
        b3R6RzdOVVJBb1hKOExZTm9TaW9lT00KLS0tIFVkYkRQOU9MZDl0ZU9hOWltOFpl
        K2diZlYzZkcvdHhPU284a2E3aW1SREEKb9YIQ74/COvugan2xN+TVxdixbqqmqP8
        juAGz9L1y/hkBn+sGdQXrNiWNqDwRsAeFqwZG8MJWkwGQz5V3Bhppg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T21:23:16Z"
  mac: ENC[AES256_GCM,data:lVPYhKLVrHA6/QTyYev39yr9mD9nhBwrHvtYZm/3BAlBiWkL1OVlsQ1atsduCe/aftzOM3bprHROkcrybk7GGiCtDCk75361uDpy+8Z3K9BhmTR1gEPOA2zYLMa4zmJWe/Ft5Fz/p2smyGtGXHh2yxgpqgCu7t5PHRSrPjaiMbU=,iv:bmcdxpdywMUqCuASdM3wdQpHNHzsp845y7B1UsHrlVE=,tag:ieK1KqMgIZv68NT7mwASRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
