apiVersion: v1
kind: Secret
metadata:
  name: trmnl-ha-secret
  namespace: home-automation
type: Opaque
stringData:
  ACCESS_TOKEN: ENC[AES256_GCM,data:z/mxlY1dG3iYv0lfU3r+7mw462iKjETqhyRlu+E8Ki22EvUJR41kKcWbUg9zQiteR2miB7u5/NbFrLBBCLsQRkCPMnYENbU6pQDrhCyNDAd833J721YI1wnL0QIUk5f1ev05eVgueca2+B4hRDk7vHe6Wb19OyPf1U3uO29eBNmGSVySarxzr9i5cCe+onrR34RJTUuluKF64+ahBSyw98zijLtuxjG9zRXBWnV+XZdEvLFVYpcR,iv:MstMiOW2rayyIDir84pjnKTDKI3yNT583V3fZmxC/00=,tag:bHUQBk86AamYiIo+Vkppeg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycERPUUx5ZlQzM1ZSRXpV
        ckJscEhENWNSN21zTjBYU0V5dGlXaDJDRkRJCjBiYnpyZ2ZNRnlxTFp5RXhFUzV0
        NFpmcHVkWkN5aTVtcFhlV1d2cDRKR3MKLS0tIGxpa3J0bGI2NkJORm05RU0yWG9O
        cnF6K3hEeFhsQzhSYjkzbFUrRit6aHMK1Sx+l77tcYLQnMhtVZlvvPBVSi1RZrgV
        MgaPMKwdLCygSRhV1k6c4g664T9yK2lJb6apSHmJ9McYDP/49k5B7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T22:00:37Z"
  mac: ENC[AES256_GCM,data:2KpUZ/l9KJ5VVLPsZk34ZMvYoC2NezA2BETsZC1pWgAmkirJr7/oPwlV1vaZdIt/wrxvUjuNRKPwRXrYQYRXav62f/ZwPFPqJWBs1S2RmpShu6b/6JHd5GkK+Go+i8zzT478VHD+WS1bSCR1bywbxVQgWJDjHKDMMU/ZYQA8A/s=,iv:mgHEkyi+H2d8HGhpNtX/YpHhyy71TFCwC9H6kWJelZQ=,tag:uppM9e+hFGivhvRBLoYc0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
