# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: gas-price-monitor
  namespace: my-software-production
type: Opaque
stringData:
  #ENC[AES256_GCM,data:kZYOSJxgAjMq4EwJ7idbCwVZctjMEtDzdBvqcKhPNKlu05xy9s9eWuqmj3P499v3L0stN0aCn1Ygn34PbFYL9nIomNufbvoo5VLAisPBK/XjQUwUwdgR,iv:ZG2zl37mgT8QtPE/IqHbzmzkoCAsspmO6v7QiQsQldw=,tag:tydr/WCmHPuyz+FnZgoJuw==,type:comment]
  #ENC[AES256_GCM,data:C56SUlEJkjib1BwJR3wfJREqv1z+NyvDZ38ZgEZCWWuSaDNajIfjjXQ2Snx/1Mk1VRV9qOfgqfCw1hDN2R0I0QcipaWBMR8mJqxoHxjpP/+wzA==,iv:SXNdKCUmO5K0hM9y+Z5lhaH7Nz+Wl3fCqUTXDuoPN8s=,tag:mjHK0KIvQvFpupBkYSj16w==,type:comment]
  #ENC[AES256_GCM,data:JfDPlTFLp23w6F57yFqauwGeLWR377NPENs8EF+GnpaFgxd8i7x1NMbx4o1JfFWdLgT3/lqFxd9AaQ==,iv:1asW8qClde3i1kWSASgk12pgepH7AyFRkxFSXIH3YCc=,tag:U/YydGyq843sGRafS7lqvg==,type:comment]
  TANKERKOENIG_API_KEY: ENC[AES256_GCM,data:A3CWGHb5bMcw0tfJqv/sWs+E7rz8vTVKZYFFn+dtdZKaowPT,iv:IUmNCcsC+juKRgI0GgPavptYoRuG0AId4GPasv9F0sY=,tag:JU8nBxBoU81O/z0pK/Jv8Q==,type:str]
  #ENC[AES256_GCM,data:olI0Et8UtVOLgAMUevk02gutYg7YO9t2ko5oH+0RkyKwYm5CeGz+orfN3FNOVrpvT62YcL4tHiriuY/nmZPI6XUcr/mkkwa8trHf5/A=,iv:zrSIa43KliBCoBPpq5auNLhmCJfjJpgmiUFRX4hkYrE=,tag:Wt3w4wpzYrSxpyBAzpUJxQ==,type:comment]
  #ENC[AES256_GCM,data:zXop7QGLpM7m6DT6FHyf8MUhIM+3ssaToJ8w0S2dwiQ22wa1KATWf0UGARoMJnNsrdJswpvlBCx9OJicfWmxS5pH+p51ZzKprAuXUFX/,iv:6nUJ8xKNpKcjLqetqtv9lJwoHRvpNyqR2X1X3XitwtM=,tag:AV71mrgVfsMLZlthwtqApw==,type:comment]
  #ENC[AES256_GCM,data:PZ70aUo2qZCUgEq45mwaAYneYRBqI6eBn6UUl9DPt/EZHthFs31JdzA6G+pSbfmqmHEzWhT4Wxsl4/PIPhCQEfKd3d5EqcJZSJ2AQo+kWZ56BA==,iv:GJ7FFcyhg3uEWO2Pl0JxHwaG/vf0MQjAuVIbFvruk6g=,tag:Z84nIhaux5tE6GGQj3RG8w==,type:comment]
  #ENC[AES256_GCM,data:3DDY8Aq0gGwhq5gSaCealK9axh9DoFS1KNr3nR+skAQ5OPO53jg7T5jdYPs37ibCvBgsRLjsBjwHyJBb4tzPBSTPzchk43R/aJxPLzNVKE98uyThkjar/A==,iv:6giEsxcSedrp6wMxoNOLEf3TaFjVDNkkGJOYp87R0EE=,tag:yPZvDwtbh/wY4Sqobkb7jA==,type:comment]
  #ENC[AES256_GCM,data:pUocYd3srGH4MaQcsvvNUfR10U7AoAj2L1I/eFlRsoKf4o/f5DU=,iv:3IXsFHqgX+ggRS5WmoHdaIgBFi3jSgJUF3s3xo4yt0o=,tag:jeap308RDn6uHzzpbqWmqQ==,type:comment]
  OSRM_USER_AGENT: ENC[AES256_GCM,data:c/7trIwEtiq84Yq0MwpLNbceHENvFkk/Imtwl12N0w5FZMrm,iv:XagKXoqm7NcuUKHGr7YSfUehBnUH79FYNs9Rk/zdU1U=,tag:UdEH+SqYebGr1mjlzokSqQ==,type:str]
  #ENC[AES256_GCM,data:2INifytpuHyjl9Ngv2YaPwoEE8QrA05ot+Y3IgYau2XHi1HfQUhj9mRmt3Hq4zoohY0M0WkRKCrMaL00kg/NBEkDIqstS0pQcg==,iv:wd+m6ytxGp0jNXZtVcCB+Mdz7BOP6kY37Q5FCK4jmPM=,tag:37yP9mJl/BlB9E+M71yJiA==,type:comment]
  #ENC[AES256_GCM,data:lEKDWgKyu0bfKpgKB4WJ+Tr9jFO/NLfuoGf2jJ7rp3dEHkeHIOWLyZd5tVMb937x8YmxH4K3lkjE2qx9zS8iReGl,iv:iav2irR26GOK+m5kgl3lC8SAVuvG8hdTiRYphmKxTYM=,tag:3zTLR31euNW3aTbyaiU/lA==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ1J3ZDdEQnNVUzUwUW5t
        cytSSXZodEROc0FPNW13L2tRWXlqbFFyMXdBClB3TkVQVitCWmE2NnlRMFQ3dGlM
        SXN0anFpOGxUNHBVQ2p1NTVaKzVaK1kKLS0tIFdvZlN3ZkFRWVpIL0F4aUhreUsz
        dkZ6TXNqTVpnVDVzYm5HV1d3Sjh6K3MKLN/hcdY150OLBszdPWORK/wrqiaGws63
        l+Vs/KaEnZJp5ZCC6rGg72fB5KhraP5h1M633YT2WdcDi/HBIRVGeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T23:32:05Z"
  mac: ENC[AES256_GCM,data:AZICmXS8HYqgngVGg+m81ZRb3OTaU1N/1NwBWzbr/q4YevAcOro0NNLayO7F0Es+mKUMecn/xf3Kw7bC8kCt/1yfscvNnYJuI/mCwu40Y7rGOP9nw0qbTfsT0REI/RsaOg+X55HXqc06wlqGqGpff9wcOIvAB8GNanCMw1F2cV8=,iv:l2L0iwMIj/o2xWA1ABLVGMQHjaV4U6TPHLn13Au2h0k=,tag:jrJl63j02tP7d4VHQiHPzQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
