# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: gas-price-monitor
  namespace: my-software-production
type: Opaque
stringData:
  #ENC[AES256_GCM,data:yM8gyOHGaAGXN3jwsQpwdsax6WAqeSO7hjftNE19kfHpzr6T4AAxeGZCLp20LdDqK+CNzpSrn3F/G480zemt7Xv1bNddu5H6OW7c8T2qLE52l0HwF19z,iv:KdLx6Dtwmsvi9lWri7cx572mWPP4pyqFA/CUrq4eTjQ=,tag:+tVjTz7M92UdHuHt9fynpw==,type:comment]
  #ENC[AES256_GCM,data:c45siN6hiVB+4QRyHnSfhs90yyB9YN72jNTnxUuAKQAyVisP0tEPfFC8Ecq1HFu2s/oIkNhAO53lKwXOPoURyCQjmZQNNvm7KUWuwvp8EI0AGg==,iv:3XjhkMiq+Vngcmziq2GBMtCOe5O+Qi5r/gf95aCVagQ=,tag:qc5IVJ6KqLgDEVKKVSE0Mw==,type:comment]
  #ENC[AES256_GCM,data:yHBGgT91sZTnudoUXCvJYbqNpdqMxmsXAbgHXPfjZKJQG5ALr7OET3m5nw6/FRD8u3/Jq2oQ3qwO/A==,iv:VatXHeiZvLvyrXZvFoiC6CGTke8mVflaRILjwx3wZPw=,tag:RoNxlSTvMfOpZ1aakL1Jjg==,type:comment]
  TANKERKOENIG_API_KEY: ENC[AES256_GCM,data:NhRtCxaxODslFsolZTNL+VOMz7uX3fhvdMP8YHl1JLq8rGsC,iv:Zn4NH8bnwmMA3l+aXU2Q5wN1s8DbPMbTxw1UQ1RLiLE=,tag:+53lr+CawyfQMMzFEtl7yQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN2hPdk9sVTgrVU12UHVX
        OWEvcGxUVDU0cXdVaDVWcHFQT000RW9UU0hNCkZsc2c4a28rZ3VFa0UrNmtNWXhn
        M0lLaVNOQ1FycEdEK1BTY1lMUUhVNTAKLS0tIGUxTFVMS0ROUFZpMzdwZWU3ZmIy
        ZmhxR0RrMkZ4Q3YvbWlPQTNvV0EzVkEKzyJarA7P2JDHKwcYIhJwhoirHi7BaUs5
        dNS9ZgEN6EQBVK7a/D2JK4O2w9NyDYlBChskyPM8WuDW7CHqRQNXPA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T21:04:16Z"
  mac: ENC[AES256_GCM,data:L/R46y3OxPt4Rqytxo/AC+ZoDfWJLRUn3dhWD5IV5XdHkEb2yOkh+RZrUE/FtR2pB+zz6EmUO87nsBEClKDo1rwYEC96R5gLGDp0ZI3aiCWfYIi4Zwk4ZLN9LLzKNz2uj0xUh0MPNsyxIRrUZnjpeyEoAu1HceUfjxYs66wJotU=,iv:EfoFCY41lf5lPIahIMW32GvcAQFuoMtfiNH35KpvRWs=,tag:9C9CZ252ibxCV1g2cvwsfg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
