apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
  namespace: office
type: Opaque
stringData:
  #ENC[AES256_GCM,data:PgYMPHuxXI+vXhVIAZQD2KFNa16ruey9/Dc86aDFZarlQgPuS7q+YhPE,iv:bsEq6lYTRzvdc6EeqHLxwnbBbTikP+w/aceljkZoTUY=,tag:CXMSYMnjOnpJVsLUNENRxQ==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:OwugKlLnUWUl0VNSvLdaqmNwQDwPrjIoun5GLIGZfPR4UdjvRfqjKhGO+yVnk51Ps14Az+t12xECQ93zuinGWI/vEEBwjtxZipz6F2S74rTZ4xnahhBf9kJYXZomYJ4yYW23upiJAuUa4zKSIgoeIXqkVgxM5sx2Rapnh/9V8zw=,iv:w18d5Qdpk9LPIayUnJuCJBHWCCzuqDhFK0mJPxRT7oc=,tag:p7BrwP758RGCbbQBOdcv7g==,type:str]
  #ENC[AES256_GCM,data:c1LZ7yRteTqKe8zV5X9l8+0UD8HAFmjPrSFcYJw6dDD74+UFu+JUZNrBYusksXcYJBRGZQ5A,iv:fln889FdvVZdKVB8L0jYIsKCEmrv4pXEyGhN5D7nQe0=,tag:ASHmjTzSI6w8hYykSBN5rQ==,type:comment]
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:bYxlIrLornou/G7qc8tM02hzwDMmh8QgCUekhwc0sfU=,iv:qVk32kyxzHwX32O5ms/6SxcJNXjinIGNhjyRzIfHTEc=,tag:LnZlYhRBVCgcVJ+SzGdl5g==,type:str]
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:EsO7lYussRYaDYjQCs5yCIeGWsUzNqO+8EgWZSCoB5A=,iv:KUTNYKEB/OhQoh7IHTNUMZjqjDYJ8e57iidI8PYSVlk=,tag:y6rK6+CjKyXBauwIKAl6XQ==,type:str]
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:mSZFG3DXKvNB6qjAWhsfKLBJBzKTfP1JQvoJtJR39a4=,iv:ytlFMvbE+Se2Gk1Sur9l1XF8d0JOBkzhUTXHEsp1Qac=,tag:qGOZiOW0BzPsvwQSlCGOng==,type:str]
  #ENC[AES256_GCM,data:adwUnTSWkKSHJAzLRagrmIGByyh8OCdf3aKr88F9aUiJeskqILueuGP7SZYA4eizz9JAjGqF7182x/XNnfx4/wPK18i6rqK3KlXzN++qceh8J2N3RXJT,iv:C1VBBNzbAxQQ7dEh/xyaBI6834LfvzDm/g6x1Nv2z38=,tag:T04OxSIVEyo3Vblxeg6lKQ==,type:comment]
  DB_USERNAME: ENC[AES256_GCM,data:tut7PA==,iv:YWnnCZ2zckVGGLtxRkrbXwGiJ3+z/skYs+QL+mJ+QE4=,tag:dxMs78azY8YIhesaGwb5kg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:dxVgHll0MfKi+aGLhUCj3ysA5ZZ5ZQcSDZVY7xr0jtc=,iv:k8onZlFsVBKya9//OQcZyP8DaqP7P0tmH1M6oqQxBmk=,tag:HT3QRN6fdHW/tTo2NB94Kw==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:iH79rw==,iv:XM6rxqPuFFFNtJGVgs95IzF8Silw3TZzQu5mb1GJQRc=,tag:FhWJ0rbHZwLtHE4GEBxK6w==,type:str]
  #ENC[AES256_GCM,data:f3e3STRojgKPP9iBIaLcGxeEZCZPWjBcyWQ0MA==,iv:2TfSLW9BP0DkT25MarPCTHDHycPKGEObB39rMYA8Ees=,tag:2GIQghLxpxbo2o6LvIW9xA==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:lJDagDyebkt3yt7jcDQo5UgovyUCQxnzV5z1SQDETSNpWUwISrGAZt2B5lvb4fmFmAJTk+zVc1ZYW+k0aN/WrqWsGes=,iv:brtCLXFEPQ4SbrLCKyl6aieWhHK4bItJNoPIdihm6AI=,tag:ySdKFImzJqxbbBtZxj9Xsg==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:+a7sXQBn84jnSpAfa4ivBM2W73mc9R8WaQ==,iv:EmG568cB1YzV357qW21+x5hbt46qaiYfFYqt44zShEw=,tag:tkFIBKdcw7A2PVOGV/8tHw==,type:str]
  #ENC[AES256_GCM,data:iQOZG0jBVqvCgARzaHpJ15hzY2EFG8GJejv2DQL6+bajkQdkFEgWghqv0qjzSy+r+ZeRynHK49q/JIppatrZLpBj26RviQKCec4=,iv:xxwVd63kP3j198L3dPbdb7fCe0VeMBELCdd7cZShpLs=,tag:jzxCN/k8TUp4Jp4qR/z/Dw==,type:comment]
  #ENC[AES256_GCM,data:vud7hMoqp2rzqDoQTL+MSKbxKovOswyBRBgAzcOYR6gi6+QLHr7cx6In2Lv6YNB3hMsCXN+bFDlBNTX4R8RTL94EKb4K2ZWTcV8Q,iv:58o6CAb86jkTPnsrL3bIKfCzBYDMs4x7hh0xiXejE3s=,tag:wu4UNNuT7il9JJPU4KD+pA==,type:comment]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:bY+cZbp+QZzlX1TC5Qv+JcBzFC92tW3bv0Jpp+bI7DsSbOKSaNjB0g==,iv:8chrPj3zk2O6vb1d2eNxowURrvJu8DMbzULY1F/ZntY=,tag:SqM1J3DfJLw/aM9KxoAEqg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:20NFXuiqXM3a1yjeYJkESBAfKXqKwUVuNpPJTL+xSkoziYpz9kibO8ULkm07rgsc18PS6igGbfuk32hNsalNwdn8J/kZSgTWHJqckwdHbgZVHroZweVhtKUKghElC6iT6Stozz+Xazmr83zXPcGWpa3GWRWH3N7LqufgZIgDOmM=,iv:fhJy7TudJSz7Z/O62NgVWqQjGJICxojgHxd0rjL4oyw=,tag:whLSmWj4moWRccINrsNmNw==,type:str]
  OIDC_ISSUER: ENC[AES256_GCM,data:AjVIdcVD2zvX9o7f/9b93JoaHb2AABczheLZaseCHiIe1h6HKjfndhs=,iv:ac8Vh6mmqhAFquyldPuIhCWK+aXtvvPAD3qvD7ZTH+E=,tag:JBDKoBclbILEjz1BlRYhxA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdlJjYThtUnVuUDJaZ2Y5
        WklkQnpGcE1td0NBM00xWDZvSUdQdE95YmdnClJtVHlldldRYkppOVZWdTJ0N2ZW
        VHpnU3loMzVYSCtRS0Z0cU5pZFcrbkEKLS0tIFZESXRrZTNEMS9heWNwT2lBTVI4
        NUZQOFVkZzhjOVdtclBXdW9jT3BXdVUKuMBF97azd2JfwP90c1TviY/Hj0CoWV+T
        5xnlXXgpQ0S2at4VshRLpTiB1vptDg3SYPN9271GWFjT/nXdHbvcAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T16:06:59Z"
  mac: ENC[AES256_GCM,data:m7ZDBcTiKVRIzOdU+aPEPl5E7+g0hQUWmEtTR1A4+adRJeYBVaH5SRleoUtLnychVA3qgSY/YKvfd9Df7ZZ3e+4CU5jmCeJp5NMmAVpzBMCYqqxirAN3R0a0ibZvZZkfzZs8Pb1Nx5BWPNQA6nJAQ4c6iw99M38YSWUy4tFIE4I=,iv:wle4GA8j1RG/7GumSwQsurP/weXDapmXPa6BaFZMkFk=,tag:sb8qo4z8HT0hBVkQB/ORCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
