apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
  namespace: office
type: Opaque
stringData:
  #ENC[AES256_GCM,data:NDCSAGkCSCBceSf3E/cUJIEB7o4bF+FjcmNivrcIXocww7dE/m4DTyWh,iv:+IxhBKaDuWKy6rMeB/P/i+iHGpj0AcoIlgtYUd0Ho4c=,tag:ciH+enn3u7QhdZzTojXNhQ==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:cDu2D2tCYIJeaOaQCfrBMon9u/D7rNKzk7KoqBNkV7SS+NEr2Cye0UAthOYrlKc1M1uU1K1CftD8m+LmNr5LcuzUJpkQJkEdg5ylqhwJOMHb3ifkzjjrNq4ygGFfJXUQ9OZBJdZZVlR1C9m7lhLfA1+iJ3plJSQCQDKYU95H8AA=,iv:nFKTsm+B9sw/VENDp7b74ypyGVmEwmJVofTzFWCGySk=,tag:V6Qve54RHEDZhIZqeK6faw==,type:str]
  #ENC[AES256_GCM,data:Mpu0G95tn1sMwKvbdXuXInexe0OpRjUUykGwTE6zc5CKPLWo33/uixLC9FbmYgveDfZGm9zT,iv:GjbLZBji6YOa/JSQrFA86Y1yYrUYQgE4G64CzGPeCXo=,tag:hfBIsuPDRm5MjeER2FMWvg==,type:comment]
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:WTt6B2ZoM6+aK4cDnXfh4qVZsjmc0beorOwyPtbRReo=,iv:MHMFQwGNE4kWxgIgbV323Jy4MD1f113uB7I1tbT8gHg=,tag:EEj0mNE72mWLcoYPym8HEg==,type:str]
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:SGRRpHTzcjjcq4dLDet37AFqs0yGiy+PIVhR589xPwU=,iv:MkxFNGMjn7V4WVBXcMaY8zTzAQl8/UnfEf031NJh3JQ=,tag:YaH/mc/04KdGQQ/5lnVzBg==,type:str]
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:e5pbmZaYFZqIjefUUfcuPkDJlggy4iMIvpjCBEt3QLA=,iv:x+C7TJMf0xS7DsX6dKwhuDdJSiOg8ruQ2Gijy/+D0L8=,tag:Ejotp2zm+GvhhssrWAmgyw==,type:str]
  #ENC[AES256_GCM,data:3aY2cj+6a5yWxgPg7QpB/4pRrSKrN12Mu1X5DzKFnBJD6+ovyin5Wi7VkmGg3VU9KGlpbHpuQi5g6e69DK95iBsmEjt9+QCf9u+lA6izlGFnhIcaZSw5,iv:aT+rA2Ywxqkh2Wzpgc8LiBgrwH1qVhrLCjL48GUAVc8=,tag:7LktmBeUb5Y/tu1tscftvw==,type:comment]
  DB_USERNAME: ENC[AES256_GCM,data:dKKUsg==,iv:u0Sh3IuBTeScvwvR9IsR/MpFlakwM7+W1e5QjK1NYok=,tag:LvvbvSRM1tXXKaut3o3aug==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:z1rgHRyZnDcjZvBFwqTCCSNrbewzIryRqIpIKCwud0A=,iv:vLnrWJHVTricRytczQ08ChzGJ/isvHxUS9IRF46ueO4=,tag:95iF6vUJvBWqBkZ8e2Y3/A==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:Gpn8VA==,iv:VS+RpJysspeSVraAEmY99TTz57f1I150dS5EYqb1JIE=,tag:I7UXUwL7yEdjLTjKP/0F/g==,type:str]
  #ENC[AES256_GCM,data:ANq5q1Xr2xs/sbp+cOzxC/48cl1NpxeCHnLYrA==,iv:nzEsCZMIrWokWVfInD1dS4G5l9XSEqzRUoJYvycE4i0=,tag:nArFqO1s8cs7GCfi4Cc2ng==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:Kc03x2ssApPIOzHvKZ8n1+2Yfzh9LKDcPFoSmsXc35EdG6yA025K7Fb6+oht/TneTi1LqbdeXPmX7VaQj8LQtomP9S4=,iv:Ck47hZgBZTanY6TrswMB7bhetBBMwobtF8W4Nl6uMvI=,tag:KT1t+o0+0nPjkPWixddKuA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:NV1VSkJrlpFtU5VhQigyJh9fHD4ejts8GA==,iv:FnOcVqebNwe0GM7Ab1lXDcI6t+MdJ5u7ok2cF84yAiw=,tag:dX7wsPMbPyMWLfuJE4Beaw==,type:str]
  #ENC[AES256_GCM,data:lCem8EAIhgTidEVgqxxRoJSRRgUz22j9SCHphvGgAJaHM9pHy+63TAs0Bf2dJRsyYtnpiVd5zHO7ZneK1rpZ0d++0BdnEu073Eg=,iv:561Odt42wECJoDse51YiIhRGBw4676qkDtVAsnbpnMw=,tag:rxpt3r32k/9M6VSF/Rr08w==,type:comment]
  #ENC[AES256_GCM,data:bnXO8MZzHNAggkoMFfrBW/QilY8o55pEinak938NaMpxcEL4y4foPZcTy78dJI8n4wzYMUhwjGw5p23XZjbK93+Mn7xsgI+WXJeE,iv:C/VTP+7g+ZRyZg3fl15IdWutj03zImmxwUUKBxZDfeE=,tag:PGgMXycBGDjUiF5EMmiLvA==,type:comment]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:0rCGsvy3iRa3MlpKMix2H4PiiyugkjXnSfBYxMAeA982xp9jFg3kpg==,iv:pc4X5cz39QSZ29OyWRij46Vbo2b9MR1hre8oIKX+xpg=,tag:N6dPcxNbCXntuW8acFSRqw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:kftoaxqtJXAzsPoR8KjUMYDbstUvXIyWdV+YpOYyPcYnZ3s/ACM+jEhMnVwh79n9srEDCuAMNtuxhn/tfz9X5b3EzQcFgJUwMwMyDu2jQzPkUKnzomP2IBfCPZD3IvYsBgijT//7bQmibIGyvKDlQlFof+iE5WZOBXC7sXxfcJ4=,iv:dx7Mn+RfeojmOgax+OAa+Ov1C22vOxZboK/dYChfEsY=,tag:XnHvbEjPRhoLDM+S/4JIaQ==,type:str]
  OIDC_ISSUER: ENC[AES256_GCM,data:10IGDIUzWJ0AN8AWoRpxROU7HyA7XCZ0jrR3aRpRzCFNbTNrpseUJyE=,iv:uKSrYwBy16NypenVW+rXOu+muAk6crJUOm2eJ2P5eEk=,tag:r1nQ2ZPIvRPsmzpaMtIHEA==,type:str]
  #ENC[AES256_GCM,data:v24nadGjTML1DY/nYGWVqpkCFi8L7x+liUJv2ZPgRG7eEZ2pf17roSgnZKyUFttSLkH5FVwD3pyMVfarVc8KLi3zAZs+i/p3SWWWv34edM7Ci9VvZYWqRgy7TAelDoN3ptfH,iv:JiD3C66wJUNoisaZhujO5BYE4+kfOhpB3xmUb2aHmV8=,tag:9np6D8UCe4sBkLm4Bd/cmg==,type:comment]
  OPENAI_ACCESS_TOKEN: ENC[AES256_GCM,data:TZ6VtVMaLcJh9UlO,iv:Eo/TfFWVmt2Y63YYz2iE3yR+F1Fexr52XkskagdH/Ig=,tag:H/X+XKAhrcOA5NmUppAgoA==,type:str]
  OPENAI_URI_BASE: ENC[AES256_GCM,data:jrFfbtMTQtBFhd6LcPOLs88JW/RTqka+8A4hdnLj,iv:JgEw8GvG/22UXuGgv1sdDZ3dZ+TCwUjMQSivmc0BJdA=,tag:gW1aZ9No09iYN4rcpKvdfQ==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:okircQQdNpvwfA==,iv:QbtBFS76B5AB92BBjUskK7OeRIMnI91ZWDqnd2iei44=,tag:FDU27wU12OHIKLgiqu3oRA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBendkZEJ6UkdUaGtLd01n
        TVA3U096MWNDTUVtQ0N2d0hlc3VxUm5GeVF3CjNwQ2JsRTdEcjJyazlQeGlEUGFs
        NmxzeGZSZDN4WStpdmpEcUhSVnQxNE0KLS0tIE5qM0ZmRlBFK0lpTXN4d05tZHdK
        OU51dTNMcFRkejNSVnBQTUNiYnZGbUEKOkry+orn/RqvJkpYIYL5IGQ+YYcxwdF7
        Y61NGyMp3UdTUkkNaiwlq7bZ7/MibDm7XQ62ov2gsKf7vJDMgt4oWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T18:32:53Z"
  mac: ENC[AES256_GCM,data:Bkk45PKWFrv587hQE21uuOuLWRVOR5Srsxv+n0IdaqglN7v9dBby1SisxZ1dcr2MrfOs/CzjyEJ1Sa1Drs9+kcuAOkI77xrxJ58FRzXAVp5WpCOitMMFLrD3sBwkB+Zo5iELjl9Qq0LJ6zz4HreOEXSikpkL9w0JuMcBhDJi3V8=,iv:FcRjVX2ZuWVBx46dkspwCl1Z4nRf411EyiacFKqT+qQ=,tag:GOgkN8ohRI7y/rZLcWbCPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
