apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin
  namespace: databases
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:MKRPldx+XA==,iv:qCOrs8F2QdE7CA6jWKj+OE/2KKMLKe/oLi+a6/XCFqU=,tag:OVtQRSKAgEnzeilLhpfqTQ==,type:str]
  PMA_USER_CONFIG_BASE64: ENC[AES256_GCM,data:ltRC0cNj9ddgz14GKFIaFvoJPiH/HLr0L80JfklL85S0JUkSQmMjZX2ZsU/lUW4f9ZV3Y99BXed5JbGCd3oj2q7zqdiu5i+iqDS2IdI9BRAdybM5uUVQtkQKjMU=,iv:Yy7iDzq2wHbQo4bQLhccTBHXv+r5U654mi0VAM4vFW4=,tag:sepQHcHvTGARzqixQiht4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRzZoTXVLRzNpalpZV1Rq
        Wm1XOTg3SHZ6cFd6Y01hbURSUVdBNlkwcVM0CllLZFcxN0hxZ0RGMGhEcVpsME42
        c3BpaitiRWF5S3RBUUR1amdRYVZuSU0KLS0tIGpIT1I1SUNQcDkvYmN6elVZSFkv
        RGlvM29LSmRqaFpZT1ByN0RXWElqQ3MKjRQ8DcN7WLRQ8Hpqhqz79SjurJOSDCcu
        xP6k0WHdmrLSxPieH1AHGGdVm6Bxp1hiqRMhBjf7McwUjuC7Evqmhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T12:48:39Z"
  mac: ENC[AES256_GCM,data:a/moDKqGJ6rrPCAWngUCpFAIt9A2G3oeSIUbrlyCzSra2ItcueWEg2aXRMF0traScH7WRFLW5zAy9v5ezRVly0lSrY9Jz2wzFmvyWuVCElf3rsrmSBVQL3gpqVZ856LOT6YwGxIKxiIkMB8/YnBtPdCEHdPyasjPaWlkR2iBu9s=,iv:S/2tulzJX+PPnOrk1xHGpIK54k407q/7ndjyixP/TrY=,tag:+a66XiLllJLPVAsE09wyyg==,type:str]
  mac_only_encrypted: true
  version: 3.9.4
