---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: edot-collector-queue
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  volumeName: edot-collector-queue
  resources:
    requests:
      storage: 10Gi
