---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edot-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: edot-collector
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
