apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: office
stringData:
  admin-token: ENC[AES256_GCM,data:ra+D0ctLGcesOvBYYSq68wBCi5CfBRRSG3mFxvAL4xgDWgl3lrNGtVXKbkrapqt8Nq1LzE7AUPcykLmowqEEubdL5b48a7by4ZjwdiWwzFKXxmIVHwilhAHdOqy7qJ0BzEdydvsN,iv:PQEczo7Ncb8mILlythhPZ5JqJkbtO+ySEkSz2gDGZc4=,tag:XQTz7V8GTrGQ0etl6SswZA==,type:str]
  smtp-username: ENC[AES256_GCM,data:Clm7fo265t00Os3MEvKT7KOPe9DM,iv:SJQaKRWADjJir+JEkX8KITtqr7UNfbg0N75ZuMb4sOQ=,tag:VAFO5KV/DeI3Kw2EV8py3g==,type:str]
  smtp-password: ENC[AES256_GCM,data:piSSxCrOIdY+s1K65Ogb98Z+ZFrWMtuHWw02qQ==,iv:fBecQrmjSba1bWvrrFP/YNdgvbXMc5A9NrSs3YTbC7E=,tag:EvXn7ItJcHpft+4VNaRiKg==,type:str]
  smtp-from: ENC[AES256_GCM,data:RRTLhS9toUR3FTtOj4AsVsHY1G7Q,iv:y1JT36BJFJMYCiMzLrgKYLn0Ub3zZd0U2S4l8bAKo9M=,tag:ivgNFKX76TzWvk2M0NPwsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUlYrL3lBU0QwYW54UlVZ
        N3gvUXZzTk4vQXA5TzdMako2M3RScVYwdVRRCmxSdlhHRlhBeEtTOWRhQW43UWpj
        N2VuK0JSYVFDem0xNmZzNk82aS8yQWMKLS0tIHozTWdNcCtNSmI1QkZkN09CckhP
        bzMwZnhHQkU3NVJEUVVrREdyaGNUNXMKN9d6WNkC3wNhq1uRh6fgKARZbBBBif2j
        si/Doo2pSbrtx/vSx1xkpidFo+0NUBJzIfq4yG46sjb/6AAuc8WV3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T12:33:39Z"
  mac: ENC[AES256_GCM,data:2KbYhsRMlY5J+iFXyBi8jK0i5JMGbH4Z+flyRX58isnOJmn9iYnc6QcHu7OKl32ARxH6H2vOVFtVma67wqdQ+GkawWOqEc/1F+MYpkTksOM9tW6WlEU7XBsvVOer/nNrmo8ngCSoREt5RbFtyKla8BJZTs05mAdMrvMvd2eKoWA=,iv:SaEX1jLZyb3Trvlz+fhQoNrooLCzPyj3r9FaRogMN3U=,tag:85YO+68qClzk8DcZvR7W3g==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
