apiVersion: v1
kind: Secret
metadata:
  name: ghcr-rainbow-rescue
  namespace: my-software-production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:G7WB0+ZJilaQ3czypNR9ogU7JgB8QXse4L7A+2GT4UuWLqTFbja0i1GxBPjwRnlMVWH/H5LIhLvMdgdhYc/yuBdug9u8SynrPSqaLvXN1/O7eCPDlztp6aSO/mwpt5IDv7awQc9nXAztNUsw9E9/T+/+7s8Fvu9cN8nYmhdr6qzB5WT/sI8hw/Yi0UM=,iv:OnYo+qrisCC/OFfTIe/j5ibKO1HCEQpFHjUTUeOBWVc=,tag:Q7eJo1y3grAXZltK9iVu4A==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUkpML0lGajIvUDB6czIy
        akZDME55YkZHYmRNY2JyeFhpMTZCT1lCd2dFClhUVEJoVTVVbU9HRlM0c3p1NEZB
        bXZ5bjcydjN0V3hVMVZOaDhlck9jN1UKLS0tIFNyb3BFTVdFT0pBQmxhMVl6a0Fz
        VGhyN28vS3FCZVFHZ1FmQ2hwQnM4bmMKRfTMasQUCWS4Sp/cxU9Kkcx+j05Qx3GH
        6nDtI82Dveie21JX4P4ue7EDQSPNwMIUyCT0UgERrUJJSwuqHJFEQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:02:11Z"
  mac: ENC[AES256_GCM,data:ROyNLj2mtov+niGIzzOkO6wMEL+mxBmGpWkmQVGqqO68Asgdd2MF/+I533M1YpHeWvbNBWvjDdfruw89etXX9v4f3GdRoO+jzpeU7xFN5VHgba41id4nxWyebvnIB3OXHoj4yQNVqpqXe33BLHabDB5kmkyRrlWhzZqXK7NeHEs=,iv:8hIUub/+j9oedabiAVYu/hsNH7vLa9Uf2btoBXHjKnA=,tag:aIvWihZMqC63OFQPNABqNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
