apiVersion: v1
kind: Secret
metadata:
  name: traccar-secret
  namespace: home-automation
type: Opaque
stringData:
  DATABASE_USER: ENC[AES256_GCM,data:2aa9yF4UOQ==,iv:jANy/4jz1h4NqsQApviF+k1fHBPTotYVpEreaEZt5VA=,tag:656ekHzwnpMRukWNtra8LA==,type:str]
  DATABASE_PASS: ENC[AES256_GCM,data:LBJkbgk58zTc4mYNpzAhr7fYq3C2cXO3pDiQyTe/knfVQlVdRFO1UY4xMwE=,iv:yp6AY9Px0dTx+Mr5jDlIv8LNeS6mPrmL+K3ESgpM1jE=,tag:TI8DEJ65qA54U8DBXLXXDA==,type:str]
  DATABASE_NAME: ENC[AES256_GCM,data:5i5vMjp2oA==,iv:j4T/VO1o4UyzH3Zth4geXaxQtXPwBSdizCIFQCq80HY=,tag:/nsmPac6HLRam/MHwaZmAA==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:kA/cJ+wVWf5vAiQH3iX1zFfQEA==,iv:2lirjdOpP5fIPdP8fQyreKCb67LTHEJbUuTwywjN9PU=,tag:HPD5SLGkzaIQZPxULZwLoA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:o90ZG1CBBDp39Fed9RKGpUQp+nNFbtc9AGU/QH5fTbQ=,iv:aPR9lTLb2iI2i3plC6isEGT+0h/vChpchL3nB8jbn9o=,tag:322XKpRFm+807jKQ+uUb2w==,type:str]
  traccar.xml: ENC[AES256_GCM,data:zdEyuxddlIjapKDtnsuaKEWC2rQJvHYmD9NCI1xzSc2E90yEp4vobCP3/E2+KYEci8xxPMdpwTsZ1HCo179WUVtiMYN0T5Yi/GvuJDF2v4l5mfoPltDuOcBKmrwk47fOOMBBQtAc8s6MpKwwlThslTzOrEbR9LRSjGC6CHxMv2zlFzWZgd4744YTLmKwE29T76wA3NRjBGEvASW0V8bonS5BkpasgVbOEyXsfHgeHum4hTk73+1ke5tFPppQk0OLnxZNmZf7YRwwjYJ+26k4EEIZqC0hoSyGf4imN+92yLYSkUVgLQ5zvK3XSXwxEZumJLDAPxoXhHdo9Agb/91VYXM/TZFaMpauk2+GBaKnD5jxuT+DGTLLPdb8SvoSO03/vCBvZEHt9MU91j+dGKmX69iUk5P23Ecnn/9w2Nknn8Ex8jYCEuAs8cdPI38HSPtNuNfxAv5ubcVzTPWrfoBDE2WjnIW/t2n8Zo9C2zIXV4px1Zx+FNSuDyfRgpJbRipCIUnNK06h/GU2uWwBfgtMWOIoVk1D8O8ni8S91twOe6IpeUwUSLgq3Rb/ubLFSYjNFvTv9LvypfvrY4z7jz0liOjMxB9EJus2ZWLxN7BCFvWHYJrMSC1yZ/KtUT25fewR0UDn7J0LQZC0Nn+byYkfhiE/40EjjsfhE8YQA3meUtSwAg+UTEEYTKlPKEo6MQ5FsL1nNHdUmEkrWCoLnstnZyIo6CiaReyGUPcg0xYH+vhtr8g/xnajwoKL5NaeqbtWiq14cB6jgw0/FRj9eMNRFtfz220rdushzSAtqCU68Wlo8iEgQua37UszxLC1b9IH00gUxWceIje0tNlgEKtM6T7yMNs2031z5UC66zLhiIfBrswcBwF9kXBfCj/zscolbK2y6idx+jBTp6WUsM2+yx4T4KAACOucXou7JsMbmgFZdvLI+lbugpmaSSZcv7DU/yEblxXN0q2ZX5JFetFRqszC0vg6f5rmU2+X4B3KW4tWOeeTSoZhPbyIwDb2Buxpj1CvMz4jeYhE8x5Na8iIKYvnev95ee7pydA5ECZODZB1lZVPZ51bOwqHcYSytFKHQCCNaSta0A66g3MyapTyLYGoiiLkL3ie2ShyO9slvyzfMKq8svsHUxNzybEW0gf4u+F92oxbtNK4hXrzMefWFlRG5p9hBfxlOZO27HlrIVG6z8unMBMTBjIfZlI=,iv:uWfDtDsmDU5rwo5ApIRwCaiN1tcCvBVscGDdAA4Tknk=,tag:jpb/F1gVZtVWRCGlnuMYeg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUUxjY09hRUdmWlhJdmFJ
        NWZzZC9udFZSd0FVWWYyamJFQXBvaklUcWc4CkZqa3hGUFJMd3Nib3dRNG1qRzM2
        Kzl1ZSs1TG4wc3hXaXJScUt4L1l3UDQKLS0tIGh6S25OVWZvajZIZFpEM0RGR2Z6
        c0VSUDZrL3pscVNOWTRhU0hiN0Q3SEEKJ8mORXY/QXetAGcjq2Ksu4p/1N6EEzgj
        lzZ6ySREi7GiFBrno/VtG6ZQtru5koMKYHxX7RYVPx9PwlEeOwRTcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T20:56:53Z"
  mac: ENC[AES256_GCM,data:BUpI9MTI9CGPTtYBTxYaAaydXAhQb8JyZlMBoOk0NTEeS7UcAgCiQXwa5oYnzLrGTHA15bDLYjAuTHdXZFSpDn33vgjlvPyQqgLcevKgzGBpqZ2gNJ7paT7V+VvhXORw+bsdw2ZSTY67r+YPy9LA1q+gOcDlfd2dZiEZD/pJqgs=,iv:xUOcfEKlp//2xcfFetUqufN2GmGnJ2XsIYedFuo6OkM=,tag:8kmDrw4yH57UmdmiIlWiEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
