---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mintplex-labs
  namespace: flux-system
spec:
  interval: 1h
  url: https://mintplex-labs.github.io/helm-charts
  timeout: 3m
