apiVersion: v1
kind: Secret
metadata:
  name: ninth-banner-feedback-db
  namespace: databases
type: Opaque
stringData:
  NINTH_BANNER_FEEDBACK_PASSWORD: ENC[AES256_GCM,data:/o38u5Vzub3p1hOe72vKpoNgw9t/Wot8CbtlbfrvQwnpEjM5rakCK/YOQ1YUTdm0,iv:scCdNzAzKfsjACBVQPWiZFrhnHWfBLBvSZOnSfoiHXc=,tag:Tsl1iRbXlLgH3NSpDEIPUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU2c2aTlFNE9xem5OajJy
        Z0VkY2tZNDk4S0lHQzZOWUpodmlFcDFrdjJFCjNrVHpLUkVtTlUwWVJXMm1jMUxv
        MC8zdnVMYlVaK3dOU0JUZlBZWWQ5b00KLS0tIFRJRjdFM1IvSUpURWViZ1phMDd3
        Uzk0U21JcVcxWnh4TDc2Q1cyUTEvZ00KcICUxT3PgQ9BdPW5vL8oa9NzAJohZmxo
        Wblg8pSsO73Yoxl2ka6j/i3lASbBFs0UifmlyFT6XdnGYWzDU17SDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T13:51:51Z"
  mac: ENC[AES256_GCM,data:ShuY9WSSXQb57Fiw70nRu1Tn0ZxqEkaSbipS7331Zj1ekwaGSue8E3p95lC9EjP1juvtU5MoFAFw5q7ins/GMKgY+2H/R3XFSbsJZdhN03tymGpvlHfhXlm2q/DoLkjn6JVYrnbyiSA4ru4Kfpf61aeuqxaowSg0/ERF/VmtvJo=,iv:QXfjxm5F8zr9hq85kySDLhs1lO44YM18GFXemKOCWzU=,tag:obOuzqlRE30NLjD/BgOF8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
