apiVersion: v1
kind: Secret
metadata:
  name: solarfocus-scraper-secret
  namespace: home-automation
type: Opaque
stringData:
  VNC_HOST: ENC[AES256_GCM,data:/u+5UnmZBk5PWFvJpyQ=,iv:WOEpO1cJq3SjrPh81FRI5XRhNHfAtBtZolMosRIOZPI=,tag:8RFpQwbMkGjbdf7P5Fw6SA==,type:str]
  VNC_PORT: ENC[AES256_GCM,data:5ovMfw==,iv:psMNtGB0jAhKLJXjU7gyHgXMLK1riIOdTcHbdciH9Pw=,tag:Izn0bSVW8xAiNnmRNpDUnA==,type:str]
  VNC_PASSWORD: ENC[AES256_GCM,data:/okzkCS0RwRP2A==,iv:BjOGwySL3nNsFze+vYef4lXIyRZDhTiTlD6anxOsVc8=,tag:BpIl5y0vdTwkBCBW+ZziPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN1g1V0tkT0djZGZUaDR2
        eEpWWjE2R3FtNDlsSmdicFJPWVhJWDM0aGpZCld3SU9ESHZlbXZ6SnB0aklaamlB
        S3c5c21zSUhBRUNXcDhYUy9pdFVXRTQKLS0tIGVCQ0NEcEFsNUN5WXR3TmZMakVK
        YlIyZWxZeWlqNnVneXF5QzRqQkRSTU0KG3UjJZLQKgKO+sNRqKHBnrkkD3bW7Hja
        rBX4KHbkOv+WlIW7pCuyAlUcgfXYAARFQIKpeN6KYgXldMm8qnzJSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T19:04:28Z"
  mac: ENC[AES256_GCM,data:tnrsz2G+SpmrP9G2pWWDA/mi/M1fCZGUO7qxY70dB34o7/WR4BOJSPEmXq5B6MEDWZd45afUhsvvr+pwI+ro3smTnSJ3S/mhsQEpZJPB5ApyVLBTkyufRro4bYGnRNipCVAUxYSwuMnVfUICSJ7Qv/HaaYFU/Sn7rc0SXwUSy9w=,iv:BFzYaLTspAyvflietpn3I9RGH3SsQFCKeNPELBaufC0=,tag:4fN+KkemAZ3Lm35drh7ytQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.1
