apiVersion: v1
kind: Secret
metadata:
  name: solarfocus-scraper-secret
  namespace: home-automation
type: Opaque
stringData:
  VNC_HOST: ENC[AES256_GCM,data:7DzHZDJTH+KFy/xBTJk=,iv:sb8mUAY3OUbW7oG3nrbb/orLwfEcpf/2tjElnqoUZiA=,tag:BEazYaKWzIiq4KEW+W0ANw==,type:str]
  VNC_PORT: ENC[AES256_GCM,data:5ovMfw==,iv:psMNtGB0jAhKLJXjU7gyHgXMLK1riIOdTcHbdciH9Pw=,tag:Izn0bSVW8xAiNnmRNpDUnA==,type:str]
  VNC_PASSWORD: ENC[AES256_GCM,data:/okzkCS0RwRP2A==,iv:BjOGwySL3nNsFze+vYef4lXIyRZDhTiTlD6anxOsVc8=,tag:BpIl5y0vdTwkBCBW+ZziPA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN1g1V0tkT0djZGZUaDR2
        eEpWWjE2R3FtNDlsSmdicFJPWVhJWDM0aGpZCld3SU9ESHZlbXZ6SnB0aklaamlB
        S3c5c21zSUhBRUNXcDhYUy9pdFVXRTQKLS0tIGVCQ0NEcEFsNUN5WXR3TmZMakVK
        YlIyZWxZeWlqNnVneXF5QzRqQkRSTU0KG3UjJZLQKgKO+sNRqKHBnrkkD3bW7Hja
        rBX4KHbkOv+WlIW7pCuyAlUcgfXYAARFQIKpeN6KYgXldMm8qnzJSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T04:19:25Z"
  mac: ENC[AES256_GCM,data:i3jIViWg48pwvcL0Jbwl+cO5QAwO85r82BzzVE/vSP3ijY2kSDS/LLOEGLMK6i5Vxzw3hr/N0OJBV+2uMXn9uel4RQDrslmJGMMsy1M7jj/7dwyo8kKFhTwjEsAZaZKLYBnrLXPLNfVAU8MSkqDm+LoskgmmS7os+1JAHgS1dBc=,iv:Bce0xM/GwF0fCf6fABgKQfWDBMmezmibPdRtigwHLo0=,tag:F/Am2zFd2VXgj+LgffsJJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
