apiVersion: v1
kind: Secret
metadata:
  name: ha-ai-harness-secret
  namespace: home-automation
stringData:
  auth_token: ENC[AES256_GCM,data:OaYAVPqgar6s8BT0WgFH3tzqzRVWDaU/osAcUcFR8qpWberVj5665z889CquvHAdGoJxDKI9D73ptAgbUXnX3A==,iv:IwhfNLyxRj4pxjky+d6UiShtNGL+Cv5DvD3GHmwNHuQ=,tag:MrG3VJrQ8fgcsR6+R6ndYQ==,type:str]
  admin_password: ENC[AES256_GCM,data:USmAPHiIr5Z29zWHEHRuGR6BH+WHcJU=,iv:s+m8zEcbnljx7wYwfJfFIv+6ztbQek7y0JyQXuKcArU=,tag:6tyaEttUrXdfi1haYsQCLQ==,type:str]
  secret_key: ENC[AES256_GCM,data:PGaWlS0ye8AHvc+Z3Iowv8k6D0iumL/56I7ZIVrvIK6LEOn7QcVY//RsAhbB9K9XYe28VNMk+YhV4LQzhG1yLw==,iv:aPPfj8XfkNoLXFJnyvnuK9/7j51NxIlRdsvz+EmTwJE=,tag:XyiEXLewjTu9Ow1Ge6cswA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc1FOZUlnamVabno5Q3pn
        RVpYRmNHL1B5ZWwwZTMrOEtBeDhBZmhMVnc0Ck5OelBnVTlEbHVoU254ME9URmdF
        a3VNclVrdXdFVWtyV1MwVitYeXFsRTgKLS0tIFRycVZMT3pOeFl4bkM3WS9qVXZp
        cU9yVmhhYVpZQjdXZlVzVHZuRFpoZ0UK5a66jZhDaGVWjYavjqAvqUP43fjUfcbO
        zG+LGikOcBuRfLnIsgWdkv961eZhgpOWv8Cd4XayPYWe4+sr1LpIEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T00:25:09Z"
  mac: ENC[AES256_GCM,data:cV4bhGd0TBHLX0RZKPJpRlQ3xg/3S/vfPm/4tQuXzdppGoPcB8Jjlvq3oWogWEeK7MQBcl9NuAII0loqnCUGSIeKltfalJtMgqnFb6rgSZwVYE1YpMx9+YCKKeuAi5M4STpLIMYv5SPb55d6y+YMSVqJFkjQULxS7Suj4YznOX8=,iv:23SIx0iKPbbQG4HorpdUG0gW/WPKwXbX64tuku0BRWM=,tag:4VFc3MzwYUBgmxK2un+Tiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
