apiVersion: v1
kind: Secret
metadata:
  name: ha-ai-harness-secret
  namespace: home-automation
stringData:
  auth_token: ENC[AES256_GCM,data:MCx8f3fpokPrIm2mNd5eTtGm1YOTdeprXPBk6hJDGz14n/oDVWJRQ4NSNBB+//gildMXGc7chQ96Mbtd1OCiSA==,iv:tKjn/+XDxmUi34ZsnnAvpColE/EjZ71lSDlVbDH15Xs=,tag:l7SFIjJPp/GK1Kvc7q9mkg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzckhtZ3FTY29iRkl1dmVW
        MGplTmszUGF6bytZd0x1Mk1zdGJ0czdNekVRClpRMFVxbEVndFgvVWR2dzFCRm01
        NlhZL0JBUWQ2MDlFeE0rSW5wdHNCTncKLS0tIG5GUTBXdVBsWWtiOG0xUURYL0th
        b0hITkQ0UnM3Q21ITzFxVWRzTndwU3cKDNDu9+nlvTpJ+drVc9hSAqBrYa6DFieT
        uOArfujFRSCfBDn2JVoK4RCi8bA1JNMzmB1MdZl1/yV4NPoffcaqcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T23:55:34Z"
  mac: ENC[AES256_GCM,data:VgmtKd/ZTFjQCbFJl5zPWNPtmc2cK4mDTf3h5qg3mXiMPlm4slQJ9ULw6FP4ACbdx8+VT1j+YuQpYoCCHF9GB+8IyoWopaclH63HjdwAvmQCLrV0n5Sh4C74WAj6Q+vE4sM8BWl0xMdoA4Rxg/9CwZXBBC2AGj1iePM5d6ryhSc=,iv:GlbNrs+th1dH6MEzPx3M8xJ0xquCitxskcbvXjIn2iw=,tag:g4OrAMBcJglAr/dX5U19qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
