apiVersion: v1
kind: Secret
metadata:
  name: ha-ai-harness-secret
  namespace: home-automation
stringData:
  auth_token: ENC[AES256_GCM,data:Q0gFqRUVYfMcV5h9HPuYuBxlwLNaRKFH2Cny0XIj4e1vaPY+Ogt135yw9e5/A52STOcCMhYgBPAnGwXDrcJYhQ==,iv:yuFq6kV8dSfMmY6MpjwtY6S37DxbGGPBtrAmgj/m9Ww=,tag:wv7Um9tVDz6uaGnS/J8wXg==,type:str]
  admin_password: ENC[AES256_GCM,data:U6ve2BCfhHrnKfNEu5ePFT0zf4ucym+d,iv:6It2dx/Bgjk48pNY0IjAXbLZepK1fzET2Uo8Sss+Ggg=,tag:ewSZ6OhT9UjBq9QozpO6bQ==,type:str]
  secret_key: ENC[AES256_GCM,data:CiSRaRfRXa8rYoPAAM++vq80Rtni4cy4t6xp7NSoO43/ir2CXQiK8fU+KOTEwri3+kYd0dWeVhMIoGSMZQbmdA==,iv:FAaFO2ytQi1P0Fj+KqlJVt+ZC8sw9kWLjDgVu5IWlDo=,tag:7wgiYDENQ2CKXCzRxJie/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dW9GVnJYQ2kwdjVmNEQ5
        V21vQ1BJRUhmRnBKZUdhSWR0Qnk4WHNDMDBrCk9BeDlpSU82MmlNZjc5NU1UTU8y
        Sk5wRU1LQXBpKzVEeUZSNlFOUTZkTGMKLS0tIEpQZlFEWE1uTlVPTHM0Zk41dWFa
        Y2NVNFVtTjVITnFFdy9NTlJwMWxJT2cKHoEzLH8+KnXwX/TX+TUJkO4eOg0oHS4g
        dtpbYt7YXj9RY/6gHkA6iZKOpVARXBz/ByaNCXiCKBFu6JslcbZ0Cw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T15:42:03Z"
  mac: ENC[AES256_GCM,data:8ac970ypUzf7jw5InZYzuT+56GgkL/5dRkLmT/ybRf+jcSia1vlV9gKJBuMZI5eguGjn8LKNA6MH3trJa8TIkjoCy9HyXc/MpBZnHuwCVIjjCl+mfKK77RfxbgHqh0sav6RNUBt0qr38e21r3roIxsiUtleViGvgyVbnxouz+88=,iv:3j2x5zPsveqm322fr+aGf1YLQERGv+cViVUIGbm/cWk=,tag:yGk6DM9TObfElGbuOgRFVw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
