apiVersion: v1
kind: Secret
metadata:
  name: sweep-collector
  namespace: monitoring
type: Opaque
stringData:
  #ENC[AES256_GCM,data:xv8D+oP4ItXMyu59LEbYLvrZcK0gcJxTY+dFAgfaVE4tSYUcV7qFWp+4KXC3tRnDv12jkdGKyE95US3EEXDzRY23UOSZjbAnOT/U,iv:lQ40OWX2QqZjXABA7xaqauU49k1LOH/gDJlRdsCFTeU=,tag:Fk4JgNhC56GEDg+o1KJfIw==,type:comment]
  #ENC[AES256_GCM,data:FpfOuJqWIjP/WKiiFydlyDsHsnaGas9y4QipqQhHn6BrY9HHhjONAcq7rpefwU4cnqRaVc6Z6yPr+I7hkTtBtZtr52PyRsmz,iv:X18zHeuZAExmxKRgBCtNv4s1/GQEayMMY3uOC2lNrjw=,tag:B5zjHtEaiCriUrOEugA7cQ==,type:comment]
  #ENC[AES256_GCM,data:htYYtlNDaHgp7F2CcUYh9zrru3Zyy5YVMX9nT4yGzbTU4MsTY93DgvaHjjTalveC2ROWog9JXliRdMuLyw==,iv:bfcBGhOV3NYkg7uir4AW+aLRzl6GLLJhNAn5PWKV0JE=,tag:IoWF0IdNFqLU1LMGgZFNAA==,type:comment]
  SWEEP_PG_DSN: ENC[AES256_GCM,data:jOtaMj9CS1sGpOnrfOQ3FJHIgsOrEFphd5C28cCD4X3Y1QpxBii3lf6Vc3nhd3YOUNIJISSCfIJJjPqb6NHUF4X/vqGQbOz0Ujju4ungJhsQQSUE5pVmIyJYntgl8GTsoK2ME2KN0iEpF4yroEOeKVWLheNE2hDJn1oxbQ==,iv:i+xFTOhNUHza5Wqx+OGX9OcvS4FiO3ggJoG2XYK9COY=,tag:ZJRnSKzI8gavyeRNoWsI8w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNzVSNDIwaVZDOU8yVGo2
        TVc4TzUwL2NRRjg1NUxKckN0STNmalNiZUdFCkJub1BxTDFUMGU2cWxiZTNmV2Fa
        QnNnR29MR3lDK29XTWV2c282Tm9jdlEKLS0tIDBSckpwU3N2aGxIZWhQblJRT2V6
        VzdoaFJRQmo4N2M0eFZrM1BFdGRVTGcKzqxAkriph/A+KH79kmAhgfQw2dqSkpjQ
        SAn4S53OPlzQzkSukevsMFoC25DMhqiwKUj6jpJgCQxxe1oClVlQsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T11:58:33Z"
  mac: ENC[AES256_GCM,data:/9d6AGlHhmWeF5AgQQOqeM+sSK0Hh26aqM71qoaW6EqVk06wU1gR2tK5Tk/KYr378d4RNp/X4qmg/xda7Ea5eanc9eWdcSyAFiCWvjlfhuOYL+1VmngVpn1IPvO/21E7S0/FSwM5Cr19037Wm9J6o8AC6jFTo007EDOvBp38i1s=,iv:XnAboVbWxTlgJFfVKcmd8FnC2NitOGHr7nwL4fPf5W8=,tag:qci0JYdzwg8/cubRPEpeNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
