#!/usr/bin/env python3
"""Emit /tmp/noise_allowlist.yaml from sweep_history.noise_suppressions.

Bridge for the bash health-check loader (which greps a YAML file).
Health-check.sh runs this at startup; the bash logic is otherwise
unchanged.

Output shape MUST match what `health-check.sh:_noise_tag()` greps for:
  - top-level keys = categories from the table
  - bare-string entries for flaky_zigbee_devices etc.
  - dict entries with one of {alertname, namespace, workload, pod,
    prefix, name, integration, service} as the key + optional
    `threshold_per_cycle: N` + `note: X`
"""
from __future__ import annotations

import os
import sys

OUT_PATH = "/tmp/noise_allowlist.yaml"

# Map DB match_key → YAML key. Most pass through unchanged; bare strings
# use match_key=None.
_KEY_KEYS = {"alertname", "namespace", "workload", "pod",
             "prefix", "name", "integration", "service"}


def _quote(s: str) -> str:
    """Emit a YAML string literal — double-quoted, escaping inner quotes."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(rows: list[dict]) -> str:
    """Group rows by category, emit in stable order."""
    by_cat: dict[str, list[dict]] = {}
    for r in rows:
        by_cat.setdefault(r["category"], []).append(r)

    lines = ["# Generated by runbooks/lib/dump_noise_yaml.py from",
             "# sweep_history.noise_suppressions. Do not hand-edit; use",
             "# `runbooks/policy-cli.py noise add/disable/delete` instead.",
             ""]
    for category in sorted(by_cat):
        lines.append(f"{category}:")
        for r in by_cat[category]:
            mk = r.get("match_key")
            mv = r.get("match_value")
            th = r.get("threshold")
            note = r.get("note")
            if mv is None:
                continue
            if mk is None or mk not in _KEY_KEYS:
                # Bare-string entry (zigbee devices etc.)
                lines.append(f"  - {_quote(str(mv))}")
                continue
            # Dict entry
            lines.append(f"  - {mk}: {_quote(str(mv))}")
            if th is not None:
                lines.append(f"    threshold_per_cycle: {int(th)}")
            if note:
                lines.append(f"    note: {_quote(str(note))}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    dsn = os.environ.get("SWEEP_PG_DSN")
    if not dsn:
        # Fail fast (caller is bash; non-zero exit prevents stale tmp file)
        print("dump_noise_yaml: SWEEP_PG_DSN not set", file=sys.stderr)
        return 2
    try:
        import psycopg
    except ImportError:
        print("dump_noise_yaml: psycopg not installed", file=sys.stderr)
        return 2
    try:
        with psycopg.connect(dsn) as conn, conn.cursor() as cur:
            cur.execute(
                "SELECT category, match_key, match_value, threshold, note "
                "FROM noise_suppressions WHERE enabled = true "
                "ORDER BY category, id"
            )
            rows = [
                {"category": r[0], "match_key": r[1], "match_value": r[2],
                 "threshold": r[3], "note": r[4]}
                for r in cur.fetchall()
            ]
    except Exception as e:
        print(f"dump_noise_yaml: DB read failed: {e}", file=sys.stderr)
        return 2

    out = argv[0] if argv else OUT_PATH
    with open(out, "w", encoding="utf-8") as f:
        f.write(render(rows))
    print(f"dump_noise_yaml: wrote {len(rows)} rows to {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
