apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-software-showcase

commonLabels:
  app: see-edv-ibspm
  version: v1

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - configmap.yaml

images:
  - name: see-edv-ibspm
    newTag: latest
