apiVersion: v1
kind: Secret
metadata:
  name: langfuse-s3-credentials
  namespace: ai
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Su3N0QpVgeb8ynf+T/Xreiq6x6E167NHkj92UQZiwPzWu1VpjLKmHA==,iv:6TPnna5P6Im+vqUjc+MbhYRc+k8Q+A/j+zsst6UrfzQ=,tag:NXxwlEgVHCboRCibmmb11A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AcieFb/fQ3tsBXdIYoBqkFSGD81YkzsAieEdJdQGUxqh2Dci/xbsdmyKENs=,iv:P4jAf8fltEtLG6kNl3V4mEhBe7mcmak7NYvbiwqBBYQ=,tag:BGsO39V/f9OFRcYRjA4X6Q==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a0NvODU2NnN4Tm9pSzhU
        YUFkWWlNSzVXQjZuTVlvbEduSkREVFFTVmx3CjcrZTduME10YURvZUU5ckhrYXd3
        cldzODY1akh1dzdmM3RvTmFpeTIyOWsKLS0tIEEzeVo1RzNZaFQyUHRtRW9GSnhL
        MWZ6c2RUUXNhZDFEdFoyNlI1NEU2YVkKTFYBsIZLimtNficmoMvxNNrS745IRfMt
        3EXtTJWUwQzI79NuZ8EQG6wzxC8EjpZ2z0D8U0eOYojRZVj2qampYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T22:55:34Z"
  mac: ENC[AES256_GCM,data:74c354jYqvR00QCVJMWMUWYXevSlMQ/33XVinGKhj3hIohZjO+HeIKEwGAu/q1RjBPbG2RGYaEwx7PYgKe4HnzukFRrarSIoqVX+lxb85Ci2cUceH0pk0PzhsI0Q4etMjjLPlp9apCLgvm8QuT722IHwlK2qr9ct8rgfLZm1hY0=,iv:lt956EL9xzSa4Fh+AkMOU7sEbC6XJdJHmtPy71TOsrA=,tag:pm98nWh3zfTWT14afaYrFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
