apiVersion: v1
kind: Secret
metadata:
  name: paperclip-secret
  namespace: ai
type: Opaque
stringData:
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:thMNYdy6Smzhp42415KYapGOE3Egl0qW59xK+BkHeMquxWlviCMNBjukooI=,iv:+iuE3KLAPKi7Di1EELxN32DjpKex6dMo2malexVNRI4=,tag:euBRglPn2ap+j+fEPIUGBQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:Sqqljdlwp+7PZOUIvswg8txRZr56MmzMDSoQgRfajzw=,iv:NPBtDoEiyD8c08ShCrgDO1o2pC4RYNKomx7YDumDiak=,tag:l3k503fUe+qj9yAAN/WFSQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:BQx490Mxb6JTU7U9GnPvd9gSmj5a9EN1Xryw+DuOed7W6084dYxG5kVrQLFHE3v00QClNq0rMgmLFlakFMUIhxjB+SshwUNGphxFVIopx8ncnanHwn+gpYL+vQ==,iv:Hxb/ZjoqnFC7RO56edBQKEpacdhHfz3g6Hz+eTs/JHg=,tag:AvFbgihqLUIvZuzyh/UWcA==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:cQVTkSNfflT4VPjO87yaxScmJsEbdXAXfijz6IRrMEoyvBEI2P+4MCoULOexywP7gl/9yZLa09yyqdMhkPzyUlBqCbB/b84w3bBjYE5ymEa+QbZe4xEZuKQPIKQn37wEBlmSw0AwHlXjCAoUAlecLeOu9tov72kt1lhXCnlv73r149e+jHWL0cjuNxZ2I6OpfUzjr69hTWUEBNsS8CLsnVtM0BY=,iv:d0lXFPmZSvR12akYJmIv0oiYz9UprSoImnVaa2HDCuk=,tag:kWT+oL90sjdH/oOolPHILg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YTlWeU5IdDhPVzdUUjJK
        Nnl2MlZINWtZY0p2U05SdDBUT3VEVDdmbjM0Ck5wTnptQjZLZllOL0ZIZ0JVZGNy
        K3VjTDhFeVBWUVIrbUMzWkRrV21uMDgKLS0tIGhIUVk3bnFDRWFESUtKTGhqM0Yw
        VEVRUTZLcCtFNFB3T0JQRSsyMVBtbXcKnOaQLMxyW1BA4p7vjWujh0oDfLLTZLpH
        vVdR6lkiHjxH2hqiu9tyL/RzkpA+b9QcTvvx3Bk8LJQxcuamt6fsSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T22:40:38Z"
  mac: ENC[AES256_GCM,data:s/OI4Dd2Nlfyhd/WRpoVnus3lG3swCuHO2jHnpNHk/muGtcg2Iiy+z5D1pp8L2qCTlprjvW4rZro7MyaPQOzEhF+/1053mZJNgI5ESKvPdArL7VRZOrI2HG3QaWSZdmC2B2ZTusUHxySwIFi7W9Z9fODovtnHi5r/QhS/L+s+6I=,iv:72jyJ/wj3wP2jxmdMppzPwADqbOxdL7VTpPLadkzJFU=,tag:m65tqYXeQR8qCZnxoooMDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
