apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram-secret
  namespace: storage
type: Opaque
stringData:
  bot-token: ENC[AES256_GCM,data:GRWaB9TeGHFchsHiGYLBN9KzFLeitAYwGLhlUGl4RVtUVwHHSbFFB/EZsqlxbA==,iv:02xEb7upId5PQCtXUO2gW6QFjMA/JZ8SY5CrV54QnXM=,tag:VmZhqFWy/HSkR0jbRR7fJQ==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ09JWnZ2T0NqU1pCODRK
        ZkhPZ0xmZnh1WjczcGpUK0xXZERtUnZxT3djCkVqUnB1azNKb0w1NE9UZ2YxNk5i
        UmM5Uk9kb1Z2SjZDQWsxMzJheTNmR0UKLS0tIHNNRERBOGQzSkFOdXAyVGFZMHZa
        MG1teUxwelNTT0s5NTUvZThrZUFONTQKG8F42gxO/TfEdUNjCfO4cTS2sJwZceCi
        a7F6lbTQSu+hk+t9fW3pWdjzZJHsJRQq6zyBQIVoetWvOHsT72Ctbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T20:31:52Z"
  mac: ENC[AES256_GCM,data:Z5WKFLghU+8pyiAl/0U4ebAZG2LmwNz6dCjz55Kb5dR7I7twlSt8B/Dw77iD5y6V8c6QaTbL1+6ziIN+XmWw8A13y9B494WdmKLiH9CATsOpYGsZ0iP3cw/VcvKfpzNGbvN0nHME3tP9nfUC3SilHlwB5nYYR7wWAOpJmMi/53U=,iv:2Is9kXjR8S8IkdeD1ksJMSy+w1Ht7BEAfDhjygQjTn0=,tag:1xAMXz09SDajLct86Pf0Ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
