apiVersion: v1
kind: Secret
metadata:
  name: icloud-docker-andrea-secrets
  namespace: backup
type: Opaque
stringData:
  #ENC[AES256_GCM,data:b/eVIOqxyn5OhfmJCTAER/9IKDl0uiOPIwjpmfudypgaYmoC2QXYv/0Hh7cvuxG7gw0xxR9evCVlKbfV0EMon8nH,iv:VgL7ToSnNOctp80DDyIpo1/VAkr1NAx0IxiQ5QnJJho=,tag:PBaCUlgtmTHJH8ZlwsygBw==,type:comment]
  #ENC[AES256_GCM,data:38DBahbROvwxQJ9+j46NEr7WzoQfhupnOZz3qjwrZEtzxH5MUOQKyOAuCyf2sXqg/V+zNuYTnCLVl/7xx2Ihs1H6QjCXtEFe4r6biCLE9Z8=,iv:HRwPV1/8/EuaFEtsBhIatwAz88wz9MVjTPcnBylvQRI=,tag:YidW3TdZxobhbfDaVGRmIg==,type:comment]
  #ENC[AES256_GCM,data:eGIJ1v0MYsYk5TSLuQeWtrBuWVYR/QrgfcydRXMF8WmQkEmdGQZ9miHHu33tSULL7vyF8Pg7Dl/YTrxhXgHmjdIsAidNfa81iQ==,iv:5nyoiWFRZ5ASdAcsalYghg9l9nRrgWDThjhsyYP5gUs=,tag:uTMs6Zse/yB4XeB4WmfnQw==,type:comment]
  #ENC[AES256_GCM,data:U4vrd2fvBcvdQ/zYkOAElr2goTsim4gjGmbSSonylQyFdFjWS8OIC9AKhw6MskfAXwDixHj32HkapTqB71jpZ7QkiA==,iv:1s4f+74rRvME26ynAgiqX39jxFdE9S6BVUCKt5MoPso=,tag:T898edxkpA7Em64hmmMlWg==,type:comment]
  SECRET_ICLOUD_USERNAME: ENC[AES256_GCM,data:quV11qK8wbVZFrzsfw+QLcvSOuAh,iv:mLBmuMFfuudUWoHUsX98iDMJjilsPp5c6oYMf1rIELQ=,tag:LRW3pDW7WbqnSK/IxeaS4w==,type:str]
  #ENC[AES256_GCM,data:3CoL+7BJKTxNG/9NT9n0065p6zmwrchNUgts4MO7dxhKpN36g11l6ASfxVwiZg==,iv:rS4jLDlXaIrmehqYrakA9REuVcZijxVWcCUY1i72psk=,tag:WlVe9ZdhXuB6KpBt9KRkRA==,type:comment]
  #ENC[AES256_GCM,data:8Sb7aaSHDVGEWdlWgsj+3V5X76Fqo/dvWpG//znhWrzvHMkRX6X5hyBJ6UUY0F18WLCWYRxeILB285UyryZDgirofVKV9W3p,iv:5GV1DZQfwA+ytUwnntJlUXHa9koG+W3s6dp2yiuczhY=,tag:71IubsuNHi+rZi2FfYKBwQ==,type:comment]
  SECRET_ICLOUD_PASSWORD: ENC[AES256_GCM,data:AO0S66b4FWhY5Az0ERO/1yh11w==,iv:JfhMgxOwKOzUDV9g4bX5NolVKyNxllilInwTpvL7RIg=,tag:RCmhkMUisKZB5KafPVqbfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL250V0FzaXdvRGxoVUdv
        bjQ2b2dNOFQ5Tlcyc3dtVkhScHBrR0dsdGdvCklKKytwYWZaM2oxZlVOMXpFNDVN
        N0dhaTc3RE9Tajl6Rm91aW8yTDNIU3MKLS0tIHlPTVhjMk9ZWldDRVBtVno2enNK
        UHpCNlpNOWpvQ3hDVlkvM2tLQWZFNmcK8o8HnR1WfSZUdmOSUuHBzUAKvOD5QaOw
        MwD7v+5SeoXK/PjPYMekDAur/IIpobn1WTUgd5If1QWo9+V6oKuhxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-08T10:54:44Z"
  mac: ENC[AES256_GCM,data:+zNgEMwJTWlk8kyA6RMV8NonV6bbwRvC/G4Hb4Xh44ZY90V3Q5IIkvXx6ybCu0EoU5edHE23XwxiI369+DjgoeHSbAEIF/Be27EYc8i3svtlxr7N6OS2h53w0EkKgLwIoZhuDnwKf5l4Nh1FYC8T3xHu+9W3prQFyErX7edTgKI=,iv:/Okqu7Xdj8zMpn0Xzmv2kHLL2+IVaWABpqDUHRb+jmY=,tag:6INovx7xzb343VZz2jwRZA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
