apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VlN08XJEiUQ=,iv:3GEeTS79EugfTfOAcTNbCgeocu2jnqdR3kdxNDLyv7M=,tag:O6o0/YoNEkLWvPb1V/r+TA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:D5fp/DvmgPEzLWYSGtNZCI2ZrkddD/qNllvC4YKGVeiwVY//,iv:L0E1vdLgEZhI3aa4LO6JKRIIX/arscNE/PtPq1b2JwM=,tag:v9w1i+R2bqBQbNuBMgIDDw==,type:str]
  NAS_HOSTNAME: ENC[AES256_GCM,data:nxKcsqY9VaamRMEEMNU=,iv:j5DNfkl5nQyHGAIrEyAfH2QVFet+hSjd6rG8wp+cspI=,tag:LtiORsCUJyusKrNrf6hMnw==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:dN3kh5SULYnlToA+mQ==,iv:8X1svvj3UtHLuLZ6KtwtsxdmwR5PlFoH1byE5vD2a8g=,tag:Cyd4QsG4P7sD3aLl0djjMw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eG9BQTlXV01CWHdLdWJw
        aWM1K2hjM2FuZUJOYm1OcGNnb2tpd1pxZlNVCnRkMzFKVXBhamtWaERGRzlYTnRa
        Z1VScGdNZzk1ajZ1bldGM2gyWjNHZjAKLS0tIFN2RWxUS1F1Slk2Unh6a3VydUpF
        emVGTlF3MG04Qk1KOFJlc2hPNWJCMjgKpfsSNI9kaQDitMmjKTl/kYUPC8LLJanb
        qrR+hZzJG+y0uWygzifMVhL744SnjrqaqRk4MXI5sxakRemGvNYxeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T16:32:02Z"
  mac: ENC[AES256_GCM,data:KvIzUF2WD0+mrzzAxXhoVdNoFFsJGeIZJh4vVIaa1JvrZ/Wapz1RkY7L8WDkq0VyubGhJ72NyzpXKZOYOxgwwkaXdwjRiJkilt6ajb/a1OPbFYQ0kUTlHZ+N+HFRmya1XMcLy9I9q9lKvEJAbc4EOXFpJnP6BHbyiqB3+wk1b78=,iv:MBmM9f70RVRi/YwcIbjw5VINcD3+HOT+zR1AQDMeVnU=,tag:7BGMnSZ4LafIfqnLwhQK2g==,type:str]
  mac_only_encrypted: true
  version: 3.9.4
