apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:fOtSiczPLMI=,iv:+x1hvmnfzRevMArmgdHzS+lXFRg3kbRk6qVTMnxfW7U=,tag:a2P6zw+VoOjlhnIWvvT4Ow==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:c4SLor7S7uyLxMloEvswcDf5bi3MLOiE+aJboFQ83++vVuJx,iv:nVuJgH8bdbywJXV5whwzqc8dI/orHYA7FxkgZOFm9PA=,tag:SjnBL9K8Nn6d+2ECr2dvgw==,type:str]
  NAS_HOSTNAME: ENC[AES256_GCM,data:Eg0CEGaTTus3efqqqjo=,iv:LMhdawgq+GE/5EmcfIaS9CgjEJRdwuF8o/hx0SEcNxs=,tag:9bRvT9gRLKSk/D+1PSy0RQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:F6/VhGoyh21FQ7XDVg==,iv:Kl5huodPcrwJICIpLikqhzOOz3C7AjreMxt+Au8dH1o=,tag:JHnDBmfDko1j1jjLBNK2kw==,type:str]
  INFLUXDB_BUCKET: ENC[AES256_GCM,data:GHlvbx62Qg==,iv:VFppq5sRvngHC6S+rwqUBbSbPTtX3P4lDl04DRpD33U=,tag:fFiZzlkdVz/bvHjU55rXjg==,type:str]
  INFLUXDB_ORG: ENC[AES256_GCM,data:qPREKiODztourQ==,iv:4b/Y4dWJVw93gPSq+TL3oVjNEdlL3EOrEXIZHWHNUyw=,tag:Kj0kWT9qfo4ylEo2wUg/Pg==,type:str]
  ADMIN_USERNAME: ENC[AES256_GCM,data:50c=,iv:UJF8hh82oB+QhcxOJmZAEf+f25qKVz8BErcdtkINUBw=,tag:yuMbc2GsJzyhLJ7u4AAUEA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:40hGm4G8Z78nlA==,iv:EHUdMuRu85+uOWQR2cNSFq+XjKT9HQmrClhT2fEyi0g=,tag:G0OYvstVc/+mlCENOaKl8g==,type:str]
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:iTShLNw4/xp+vN1wi26kKbYI0PuIK3nVVa9eg4Pfovlqqc3ZutpciZdVNg==,iv:+3RL+ZBttnQrYBcWZ39NmK8HTdlE5mRJYAsfcxEHrvY=,tag:K6MbCtvrRRKYKfu90BuI3w==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:gw40Jz6lbhT+cweEDL43ZDprqNKcVUy6YyinfheAFS2KZGichZiajw==,iv:2DSTm5VH2/jCubvRyTWNICFdbt4M8jWCFktydV08yqU=,tag:dKvyjTitIyMyAZ0W1BtnPA==,type:str]
  PAPERLESS_API_KEY: ENC[AES256_GCM,data:vQbhdTBjKwstnC3ZGWrI9OLId0+herbpwouPc901IBED+DE1P9Py8w==,iv:VXU+iBv3hz8o0A7Yc+05SIrVb0rqlrpPDZpkzeA7/JI=,tag:49VPyfyhgyWHiwlWCOpmLg==,type:str]
  MCPO_API_KEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRDR3WGJMQjBnZUtCY0gv
        aFBselBuUjg4aG1FOWZFcXIwUlJPUmUyRUhVClFXbWMrYnpMMGFZUXVxUW03UUxw
        RmpCSVZ3WGJxWVd0V01PcFlCN2Z6NFEKLS0tIFRON1pzbS9BNU5oR1BzUnlHbWZH
        L3pJZmdhNFowODlJMUhBNCtMOEI2UncK7P5/VFfTQCosuoyfdgB3kqpbATeCMbtk
        +irQJjCwWn+rAdAyQ0+DnfWzLLmskN2Zp6bZJxIYyuJvSmzKMxj2lA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T18:20:03Z"
  mac: ENC[AES256_GCM,data:haqYBLS5LhL9y5tUx2NUkUJ9JBbSftZ4B5G+6WRGa+IbBqvZoHUbE70FsnvT8pmEkYNqmJCtPlczlwuuTu/6Ct9+0hN12M0VYZ0Lstka4b0kWSNem8HJ9MCo6O3dYM9diDKgMyz9vmH0S/eZwjf7y3cb3hM6PhRb1cmBSH2XMHU=,iv:5oSnN9eaCZUpDlixrAiJTmQUrB4eMJZkJcElA66dmj0=,tag:ddaZ4KKGRAIt2rXcxePwoQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
