apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gT+kna1dJdY=,iv:PhFD6JXQMP/nr1Bd6esTNUAEsjY2w9NlztWAAON1HeA=,tag:86qITJMxWFCXzmi3VZSpmA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nkwhRjTypbITDRl++7+6osQh376turB+D4XmhDjmHneOJVgm,iv:3S3v+AhhnEaWeJq2IR6jxFxTuI7bG0KaAm3iJLHbinU=,tag:E6vpPfCKPzWzsAvBij9FWg==,type:str]
  NAS_HOSTNAME: ENC[AES256_GCM,data:TXtY0N11K/yhQ6a1vJM=,iv:3tmJsRG80Z/zfBBXBQKpQrBsZEsxYwqAgreHa3SS+R4=,tag:SjADY3l/EvzVDYocci2L2Q==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:2NPvONuXp52vhc9J6w==,iv:/SM2WL8teSd7RbACyqCRAmd9p70su5OBIk1sNaeEaoA=,tag:XkkFLgvdioDFVkxw8ZX0xQ==,type:str]
  INFLUXDB_BUCKET: ENC[AES256_GCM,data:tEUZ8uxvVg==,iv:UIscjnlN+WkZLzn4pAteLyBWsywt3Svd+51kybi4lN0=,tag:Orwh+vEfc4ZQOMSEhFYaPw==,type:str]
  INFLUXDB_ORG: ENC[AES256_GCM,data:E+oBmjK177dS8A==,iv:UpSp9s+9HoszMvhOXyiyV/+8Pr8kL/Ba8lxP3VVdzFY=,tag:ehCzYPFgbwM0L7eR/kj7Ug==,type:str]
  ADMIN_USERNAME: ENC[AES256_GCM,data:+qA=,iv:hGR7Ip0MCNb9Wk+kSr1+3ha4eG1DeX7qgurNWpKDW+0=,tag:0uZYDq1zerkiSGRzaOuoRA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:qAK6aXAbmE4kAA==,iv:i2wVxMSZ/+7vepr2MuDiB/++p/XIBzoWvkjvJqKnBM4=,tag:iVWz6rTC+wxzQFLDIsf9fQ==,type:str]
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:p3W2R0lRSLC4MOu8oW3N8EWTwsvrJa3sU07x5sLuKSS8ETKg8ljhgHoE8Q==,iv:zKL7cZZ4xLEWdmmpUhB3VKcH1KDYlo6jVVSDPCyqeg4=,tag:fZTSG494jpSufop4K75OBg==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:/cLWAEzJ1n697VKh1065MjQ1cbvnzpMaQJO15W9l+zVVSn20Z3Ubyw==,iv:o5zKAl/p1pBM9vDwVQytBI+QYcZY5SBKKpIHsUWiWPY=,tag:9PvYVWzcu9J0aw1luaaFDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbDFrbE5ESE1EMnhBVmlz
        U3hib0lJaWh6QTUvanZhYld0MGdtWjlBNkQ0CmRoWmpzbWJodFlGTFMrdzlwQUx0
        aW9ERnJQd1Q5NzB0a055YUd2QVNzOGMKLS0tIGhrWVdEbUxVaEM0Rkh1OVVEb3BX
        Mk5NZDVIN25veE01ZjRseHVKQUJEYlUKUslGKiZVTFoqXDnibdO37myCr5y6JRwA
        pMlQ61yZIFo/jY11q1uhB4TNJ8SQ9f7oB7NF0LX9I8Jo6mzX3al7MQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T12:25:20Z"
  mac: ENC[AES256_GCM,data:nZPqD4wspWHHZw8GcM4ZNWyUDPKwG0HiVtzM7emvCrcGpxRpQaVPONsOjBEl4417cFYy6+Mj8QnOl4KktZU1XfTp7n0NlBsyc1vjZfU+LYpP8olVbLewjXR/DqtoE3vJ54vHzEmMzEJpC05oiO5nMsUMQyQJQpVc7k494wv5Q1g=,iv:MjeY9F9hQVHGfK0Q3gpdd9TkupVRVs4kx+eVp2XvibI=,tag:FqGJfnpAicQUIX4YqwlTYg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
