apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: databases
type: Opaque
stringData:
  #ENC[AES256_GCM,data:kiO+XRwuUK3/cP+q/N4MAZF7MXXFu9vTg02m4JVsjsPdxxoZMrBIZP0XEaQu1RnXAhUb5xwQwg==,iv:AVbcp4yDFE6l5X5kKqUStcc2evJoSFCBEYJ2ZGwnPdM=,tag:h7kivNWf5JeEPBiciS91NA==,type:comment]
  SUPERSET_SECRET_KEY: ENC[AES256_GCM,data:a0pRFqVFDSL+OjqyvyiJ1BDAkKgIJekMLdPIeTGwEoZfcNkbckvUNJyxNlOEwsUqmM1/drLowQqcTMI+IIkNDQ==,iv:vzC1RQXafcj66C0PGetMK92SATQ+kooe9gzFfffbeKY=,tag:JGvbpx88jVkMPm1CaZ93Cw==,type:str]
  #ENC[AES256_GCM,data:okB4QwZiIVoeW7oGQQUVGu0hs/jH5NDKX65+20+HlQx2k/kWMcBk6WmykhDIdcx6dQZ9xYBg6t/U/XOKDoiq68a0f+M2axWFxdimvA==,iv:9SiAxOXApihAXswEjCodlDOGb3Yjs5X+86qZPwDVrzU=,tag:YWBLADZpTnoPHB4Pz03ODQ==,type:comment]
  #ENC[AES256_GCM,data:9W899GyjgJBkVKlnmkWkLYyUL/NGMqS8NnkE3GF6kuHd5D1FWXr0SR9UpTbYCqHUu+a7utlHkB7VX/PFBpkpfRovt1xmKD/T905j,iv:Fuw9sIXRISDeIzeoUSegOuPTcO6PVM0wYp4iW31/BSI=,tag:BQM4PO0LvXsmWUrM626NIg==,type:comment]
  #ENC[AES256_GCM,data:mUsJVyu3/GpLi7J3FNFWiTRLBCcFqp6U5zDkMn9V4MLcbKnIgmXeM6g7ErDXHEynKEixNJxjazDRwknev0dwZUpAz31K43gdoYrP,iv:BiyygIgGz/ky6cdUvpGboesETJqGUBWZ35DPVYghtJE=,tag:ZEIJtz8C+36q97cTWIKC5w==,type:comment]
  #ENC[AES256_GCM,data:s0ASSVJvFmPA7GVN6u9on4xQnX7c54AoSmOFaqZgvV70uYG9aC0wqdwPlJFaK9yvbywaUlSzajT9hW79n1EVVXHbM0ASGo3oGODm3qk=,iv:HONpPDDlRnB9GXU4bCd4eMzFLmzJEeY7tqkUNhafz40=,tag:zAdb6hui6bJlUd7NZ3Wrsg==,type:comment]
  #ENC[AES256_GCM,data:1Ju1IAPgZVjoX0vG9OcZHwqmG1BtmVNo5NUL8/glFdAwOe51Fkjc5vcwpXqOkKgKH6E0pom1hKn7JTdJAQJWXS2Fo6wU0eey7KHrjA==,iv:LxwxnzDIOqnNG/slVXUUTnImaBJoHWhG8yazBUSnuz4=,tag:muYZRX7d8KGKZ16VNgyzAg==,type:comment]
  #ENC[AES256_GCM,data:ndIQ2CnhfRFgupjNh3xcDls7KyhJPPVmFZUOGWLtAZoMGETB79G2J1EVuXLMJ9aBhaDZ6b3kF3rU1nIwFH4kk7+PSQpd+kHl9Go=,iv:XQmxcH8HGwPNPld5PR3mnLFtPWtrKzI/B5ur+r9XimQ=,tag:GPAHrWSbVvy8yMctC3tsRA==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:aRIVF6+fmDcRxKbM8NKftgp5WstEXLru6Z2u5kfl/rXvFVrjHScGDA==,iv:Y2/xmQi+ARSJ0DabbGJP7QJhzBVXMov1Gx9T9YvKhxI=,tag:F5lXg0JAPl0Et8sULYl22w==,type:str]
  #ENC[AES256_GCM,data:fQtIXL6H2MTm4SdeuxAd54FaouVlGfWkWCVjnUrDjXJ5GYa+BpDum/5T9IOqysUD2v3om9rbLp+hgdwkPTwjcLyYt3Qr0v3xllJyIqeWBQ==,iv:6rLRngR7gYE73MjMKnnZdwB1Rw68nW0lVZhqXYFvACM=,tag:lXCzCfJcjvtBwE1540VkMw==,type:comment]
  postgres-password: ENC[AES256_GCM,data:jkecXD+gLYwCt43RCro+zZ8WezID/aH5bi+k5rEX4y4=,iv:uzRvY1B3umn6q6y2MiqlrRXwe0zBOGrW61x9/dsUQmY=,tag:NDnTD5N+qGu53yQUlCKc1g==,type:str]
  postgresql-password: ENC[AES256_GCM,data:Gyo0TSGoM5WmIWDHnJzXkIJNHcxYpWALHyWrzJr/S6s=,iv:LD8y6vSMxOoPtfYJexHa1Tws2XSdo2aY/rW3myySazY=,tag:wSMA20LpaOct/h0l0WZmkg==,type:str]
  #ENC[AES256_GCM,data:EbsL7Y+5t3zs08txixxyLKMsc9EyL3RS88aUthJP,iv:ZsZCNUZoOpkbK3Z8SXZMdp7aliPjGRDtVkxkOkUV19A=,tag:BoWIHSbUSJXvmpN2y7qypw==,type:comment]
  redis-password: ENC[AES256_GCM,data:ZyaH1kSc0b3F12n9fUkMVtV6F4yc1P3+jgZbKVqJwPI=,iv:zPsyvbDSNDfhb2G2kqynHS/JYXdBw0kxvEnublq3ERA=,tag:+cF0kmvu6a6dmTrYNRoohg==,type:str]
  #ENC[AES256_GCM,data:DkU457UW1LoYw02z43IAzrHyGgPHmv8swG37h/p4CnxTdnQjTmXE/U34v4654OhzeKk/SR1l023Y+Wm3xaha/bX9feyrHj87FqA=,iv:hfaEFEX3cYXErFdrQGbWrZjN/8WprrzebDvVcp1fuwc=,tag:jkWacJxTR6Sqj1tLktO6ag==,type:comment]
  #ENC[AES256_GCM,data:WfogazZ8+MlWsXQ14kZ4bw97ru2rAyIukUzpiODSgV3VIi+FIa8SMRxYa/ehFCxFyjIUakU=,iv:ppFbFPN9DBJYRZeUvmRFl19Aoox6d2amqAak784hYMo=,tag:4q+9gkRRMAvi1K2K1lrOoQ==,type:comment]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:iVYdtIGBXopaYKM5lc8LgV0MVG4xl62MJGyPjPv52JkOAqG2IxEpDw==,iv:I6hkqUl7Odg0ecOZBgGo2JJv2DWicI0Rs/8PLy1zdOY=,tag:7RfE9KFBwS8ONOSSRMvCnQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:m3qui994s4LDmdQEO0bDM7bqkJLB1j+jmdjA3F4+j/MSFKEkbB/81vwPzDsI/ItkbHvQ5Wk8imGxeG2bLA7pSnADoDmFoA2oshQVeTpulKRmOhYr7LUsLOd2gM10Cmg4MASTUOPE73hA8lXEjArk875SVndpBRiB7PZNr34zl64=,iv:CQp8NKaYuTucKwlcJidQhIhtbUiBZMonJJ00BpJKkV0=,tag:9c9HuL52gWSmUm6iwp7ikA==,type:str]
  #ENC[AES256_GCM,data:nm6BbPH1IoaHZ1UN3ORaMIvThJGbv49qkomSfnIsErq2XFSLabS6z+Q7HfprUk2UPcjlLLC0OyLmf0AFq8cTr8cCr+6CeBJoAyCIRhN7sb84erln,iv:/kqsuq+u1stQTjq0RMpAU5TurWS9Hz/yyQS/jgCTxYQ=,tag:Re32x+zE6yakKkkC0c1rEw==,type:comment]
  DB_HOST: ENC[AES256_GCM,data:CPdvnICCGO0yLzMAqw==,iv:hX+1pJeza+cybgwOpmxpf9IZIpkJgyGTcXW+fbiJfYE=,tag:CyCT2Ypoqvc/jDUvt9y7Lw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:68bc5w==,iv:AqZI8zpfAg6hAPo9b7FPZLIo2475crE6duvmk81C1Os=,tag:dXhGzJHZdSinFzOD3VeINA==,type:str]
  DB_USER: ENC[AES256_GCM,data:TYvmPAumvsM=,iv:QRQtgJ7xGjhh3imO9cVZY+LAn1x/qJHQAiFD6S7mC4c=,tag:QCoHRzin+kqS7w6gEH5Iyg==,type:str]
  DB_PASS: ENC[AES256_GCM,data:meuyAjjOs+d+qsRLNpCngHPPrgsu4D8XXWwituJRV/Q=,iv:lViaWsMURNNLyPXM1xK3q7lgIqs6hPrMhVKw7aPVxvw=,tag:AsUj8rvjpZz8WKacX8vwSA==,type:str]
  DB_NAME: ENC[AES256_GCM,data:Kp3HWivvuNI=,iv:riEh7yoI8zy1kTsa1yKtXrvv8O0DgnNBt7kFFxcJFnM=,tag:KpJK/Dqr3GnwFjzhdvmNmg==,type:str]
  REDIS_HOST: ENC[AES256_GCM,data:9xyz4iJrQB1ApCMstS68b5wl2Aovkkg=,iv:+xbgU0Y8LqYwUs6dfdVqlCg30BH8Ti2kmFQJkMT4AX8=,tag:UPNB3IcjvnPls/1ziRrQew==,type:str]
  REDIS_PORT: ENC[AES256_GCM,data:K8D55A==,iv:oxwqLSqWc6gsuxRj6IBp+/59dPftJtaoVwZrdVxA61k=,tag:Z+xgg+Z5KP/70lVoN8oORA==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:PL/oiUch/2fk1U7WkgozzaaZ8qc6JNKusot9D6DpBBk=,iv:DnGYgu3J8ZBnjA/zjgEtkl2bKSTesfpEaMOuV/gURuI=,tag:i4yKgZCSPi39BooJ2VTvew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdXR0Qlc4MHlBamhLczNZ
        MlprTzQrN2NqWWFTS21vTTFzR0g0S2pLdDJrCldpZzEwTTZWSGRPclBzMFVVK01B
        MTdMcEZnSU83YVRzZlkrU2xxMDBGVFkKLS0tIHVaOFdFSkF5d0dGc2p2TkNNWk1t
        OXVYNStzZHFjcHZ3eEFaUE5qOW1hdHMKfiM6Jk/Utf5XQAeYxYl+35Ix95TxiZGx
        ktLlksZrjort6F1r9r8NnikNkn3HR81Z/WGAjgMcjhjuocRRr1sTFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T08:22:47Z"
  mac: ENC[AES256_GCM,data:TOVhMo894yO/itLl1AyziNf0Rdq79bwFWzCIZZvcZpOrXohqx4o4gF/hXR0cYf82bsb+afo/xreBzyRktZjedP5QabeF5Ff4+f06P1aivdb4kts54wdlvEIn8Dju5GuSSq/RfIv7sId6qiURaBZXGvtJ4nVY0MjcBcrnGnJ86bU=,iv:iV+kosro/LNXt/kZLXTqkwjfzxaIhxNJAfGiAoUCNaU=,tag:scKW8UkuMWxD2XNDNhFRhQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
