apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: databases
type: Opaque
stringData:
  #ENC[AES256_GCM,data:CkCW9dXOb7ApMo5j8pQt3+s/8IVTksLW4mL+SrZUocTjb7lUJ4DUHly+Y4w7Y+bgqELdgh4QVw==,iv:IKZaXQ6hGIu7sFLyZ4l3ax8cL9iOXPySdZw63nTcaEE=,tag:e3EgmgNVG2/B/Chz8u7R2g==,type:comment]
  SUPERSET_SECRET_KEY: ENC[AES256_GCM,data:QGdCtnBlFAJrFDQwtYACEo4OwO0tKIejwHnGR+ZF/hml7N1mD7kpq1VK8sN+7bpROrZJh+ZHRwvA/aq6oHE4aw==,iv:9JmqZJAqI9FTV5ylDwuSyvPyhOe+EzrXVjpSm5+hs9M=,tag:abas1u14wl0kHPfWFb+EcQ==,type:str]
  #ENC[AES256_GCM,data:XHvzc0H1oBEQ1KJnPVXqGM0rFTzpR/7zPqcFdwTkmdR8j2z+84zvjeEBdVMyDVUqZNGUweOU3Z5H7dadvPzMWjPF0cwihId3,iv:Lz2vYW4mZwYG58GIDAGHS2vHn/wdY4Nbn+Y3BN8mmuU=,tag:i/19N+fLHSM2qf65g38JfA==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:lKDJoPtd6lrpbLW4iNpaR4xYTkvzPFbdqytxC+qm+y8=,iv:/TSseDrUwS6eDRP+2ztUTUY1wFdUZ86wIIUzGP3nBHo=,tag:iBu2os37eoriOJ5BEMkZFg==,type:str]
  #ENC[AES256_GCM,data:QHJIcfyHnRbMvOlVNuFzq627WCfE0XT3iXKimUK+bKo0Lyoi5HwfLDQUqbx5G6kPqSiWSKRMn1n1h6YTK2lM/FNF1p6LtGf5QWDsDPddhQ==,iv:qKQJFWy54/luxnLFVeHy8aVNXvAz5grfoNjloVJkP4Y=,tag:liKRrF7ncNVwRBSSLmU9Tw==,type:comment]
  postgres-password: ENC[AES256_GCM,data:ezMy63GarkZ657HfVEgvpi2DrMwmigmDZRvscdcAdbg=,iv:hifNIBtpuN9RQqDIbXaraQtg2YxBrmDk+HmeZdm5JK8=,tag:cTb645z1U+YOPAxNFmypIg==,type:str]
  postgresql-password: ENC[AES256_GCM,data:XK71sQB0EA3AcoZPWmClD/JNDWa8mRB6ZO+YZeh4+xU=,iv:NDoXToLI/vrL3VZrvVEQ1QRamV0GM3OEQS9Sm/oce6s=,tag:5NyvrwqiMuUdiXjWdNHr7Q==,type:str]
  #ENC[AES256_GCM,data:F+avzGP0EKZ/fu8UfBPPIWrqjrfHdUIMYKNNxSCj,iv:kxCdbCyD6vE1KFSXAfOiEYO7DiSx3hWkkHApZni5vK8=,tag:5ewlg7yUhDzOP1K5SSZzAg==,type:comment]
  redis-password: ENC[AES256_GCM,data:31M+0p2sZrv1JZj5tgXtp6cf8OPWD5S8+hPi9BWJFfg=,iv:GnZBrxlsjjoymhOuA4rFCi+n4TFxZfve5KZ4AAzAQVI=,tag:K0PXE0/BquAmXNSzBwWSzQ==,type:str]
  #ENC[AES256_GCM,data:MU+4QDuNcJmJCdWIDbL1Rdj7FkQkSjAzg4l8M+Wlgzb8u3zysHW86sisZw4ej4mq8CpusNRS9lg7U+/KGQN52Z93edjxTNKJ8JE=,iv:q4F8Sfug4SrRWeZACwQfWwyYKRHgTYIwOITV1E1Fq7A=,tag:n7olo+/5c1fgz/lT9uLUig==,type:comment]
  #ENC[AES256_GCM,data:SeeDOzyTI3R3cyS8q9AxmkDAH2ZvxHIA6KDWgYwUkUjjiDN8bokPsb+3ylxmYAZEsHD25DE=,iv:rt2qEGMtlVoOHz6zcaYYrexZjHE8L3FqIUoA3+pqavU=,tag:UyYGjcsRnoshYmpZp6Kbyw==,type:comment]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:NUMwUFCjuahDYsL3TWQb0qyOH2yicBD6,iv:5sxin2/r4N9cG6LGP0fpesyLCzKgMhlTSyv40yKHIVM=,tag:D70pfg4PttComnWI6ltC0w==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Tev2E5feUCi/vm6AVT5qVKnDO8IjDwoA,iv:fFuZctKviTugMFtFIoo3V9TEMRuhyW0IKXDBV1hYYvI=,tag:FJhnAz1DzEPK0jMUutd14A==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMazltT1JxN3pRWlhUSjJT
        UnZNZUdoQ0dTd0lta3FJc3Y4R0FZRDdoWWhZClpmQ0NrS2h2WHJmOERZTm5MQ1Br
        bmNxaHBsR3BsL0w0N1RHcTdMbENIOGsKLS0tIFVpVDA0ZnNtRVNzK0QxTTFGOUFZ
        MHdjMUJiRG53dGY3M0tHZW0rNUxxQXcKjn1WcXlGFC14zg8FnKBbmLCZZc1Xp9wY
        2GzlzPn3Ejf79qTNCmMZ+/bBc6+NyNaKIePcMYI4uOETDvJyZUl2Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T06:59:49Z"
  mac: ENC[AES256_GCM,data:kWDtGf08AlQ0hJAjt7HJuws2erzf2JH1dAbqTaekloid85G/vL08wnvel/HL5reOzuH1UkuCbY5IeCLXCHTduEbhpxdIuLZePsOznsyBxN/ul+Y5dgdATo6pAv2eBDX22AADXnfGcSWcHJYxTyu7gCHpoHMWq8X14juhDjNSMwg=,iv:SOmg0rCUifsAVCuSBGq+NksMWbx9h2G+x3Ex24aMv48=,tag:Q/eFLWFRm7IxavYOHkX1uA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
