apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: databases
type: Opaque
stringData:
  #ENC[AES256_GCM,data:7Wou7rkixJq5aDhT6h+XLTAO2YD+V8XlmdtnxA15Q4cKIpMO9Bo+sEuvrP7XbDSC/wrl3teiTQ==,iv:JQumonYRrb11ooSAIG9tfjPWOupiq437NxQywD80Ymw=,tag:ASR7wXV3gCZc9f6lhkzYAw==,type:comment]
  SUPERSET_SECRET_KEY: ENC[AES256_GCM,data:fzw/w6y+jG69g1i1SldsA9051SIaB6D9lF9TQSWGmi13H7GS+lJyYHL9ArUwwYmY7wn5aE4ZE3RpOCzmzPPezw==,iv:ygxp6rMxmWWEyhd4XpBf0NmQtUKlKqr80QqnDXfjEMo=,tag:adIMlEFxNVwP3ljv0QYSSw==,type:str]
  #ENC[AES256_GCM,data:LdeT9VJsOUKqeirnX4ahaWosORYbT3yGiwBvxTPIZbBJIvaiwOS1wjOLX9QNCamu+y5AROlCKWik+PldiHxmZNxRlX03E387,iv:KG8JeHoAOWkEYBy8eiaYif6THtwSpSEXeoxrbj6HW8Y=,tag:XuaNyA0eJaZxaMFcqC+T6A==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:bQeZG7OROm1Hv9zcXKcEa4+ND+0kelJJJHxbThVl3Ds=,iv:4BMysGTZuVzcLYz5AKeFR1hP1PR0gGpvacpNkGF3bAM=,tag:zgHxWy9ygz3lTSwHVzcBYw==,type:str]
  #ENC[AES256_GCM,data:eOQgTHhRbpNFWItUAjErC7qItQo7mCrpUV6LbihpTHWdwAoWjJIrPEoQGIRnogK74kAXOe1SsUu8GwRV/cdKhXbNJVLKk3shPmMvOPCDTg==,iv:OuSkoNvs6GB8DCtP+CueNLWnc9oEpqRUMXqwGWsjRnY=,tag:/OWjMJnXMPPtMy6hZk4ghg==,type:comment]
  postgres-password: ENC[AES256_GCM,data:7nqRG+8PR9ER0SqXIPSzsOfy4aggMUTWB/UwmhM8oEw=,iv:udCjUJYePXYLvucwDwt0iuujOTQnL8Ye2xGMfqNWoUo=,tag:ih8kX8HhAPFslI1OH/ITRA==,type:str]
  postgresql-password: ENC[AES256_GCM,data:dXBVsl7sDLNB+GQa1YHBinMlm/hH6MPIVc4ZA//ZyQw=,iv:kUQXIwrPbsQpXv+52nAShnAH59SQdWOb9qUkuc6b9iU=,tag:B0eGrFS8IF4h341IH2R2+A==,type:str]
  #ENC[AES256_GCM,data:zTIcR8UNMxGGTSLsKBvP/2W+qxpEc2af880wNd0s,iv:X6apbpvPQqChG+qTduDlh+1L8r376DpSLaPfIqZ8CBI=,tag:PX9V921cXekkrkBvXKmuJA==,type:comment]
  redis-password: ENC[AES256_GCM,data:mAG5ojqNxj7czBP8RVBbcIOCxcIlieC+BDKbvZp5noY=,iv:8LGIRrTxCXh/Mi26XMvV6Plm2Hzvh33huOdNVXdL9fM=,tag:6e5QyZt1PChzi3BzuyLcAw==,type:str]
  #ENC[AES256_GCM,data:uiaj0Mbp0F7doqIWGRewoE0oZOW0NUERjcnsX5fHumVfChn7yOivStQgY3ddOKhnXTvQhrGGuRUmFpCK44DwiNRmqci89dyx8Bg=,iv:KZPImDS+gRjZ6NeoIPIXyVWSpsIv4mG5r5dsd7wEhZI=,tag:bowwf40MnEDUljtZigQOLQ==,type:comment]
  #ENC[AES256_GCM,data:K2oMlvp6OLEn8qHlPo+eIwEhByrDjavCnxE7oKlfkhNvulZ1Nfsvh4l+gqqPEht6E/55tOE=,iv:/38rk0oAI63E56OeUz12+EWIhNfY124q7RvkmZwbBgM=,tag:DQvVPtFn6a5Yns6QxjvfzA==,type:comment]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:TWeNzQV5iG/5KeOUZqlNIyK2S/qW4CTaU64Dh/4gdAK8+Q9AE/eGzA==,iv:Tf8CNmHXUmgP5G+ZwIQ52M539wG8xWN57IP1zaCUkwA=,tag:Qbq8F6/fBL9Fug9MMj48QQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:RoEZvWRWwV3Ah/vm6/jVDvwsZYOfLp/2jI9OnRkasMw/X3F+SJG96J/RCWLuEdDvVJ/6k9hQP8qBM+jJDeNHdTBfQUBxhmtaN7LMVNYttGyU1kG3VoohPRZKuSg5lQvjJOGwdjNVFroNIYryLjOIlHRM05CyUzGcn1UpLZndcGU=,iv:bayi2vT04dv6DjI4cer9uqx3Y1zQ68VQIXcPJqDD6lY=,tag:h9M1zJIVc3xrAZkfMawrMg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTnFhdzR3eDRPbzJzc1dn
        eXZpYTFtMWVHejJ3UXhqVWlCQk9QNm93UmlvCjljdktkUDFlQTl6Lzc4Uzh0TGJG
        TkFUeEpPZ005S0hQZUZjT3RqUi9TU1kKLS0tIFZWbDN6b1MyYUhPU25yTVYyUkh6
        NmtlaFVCSVltZXJXQmdZVzZKRmZxalkKTtzrsfcboAm1y3qQKt0tbQQ95t/AJxVM
        nqCfdUcw5XrxvzxDnLEoukHeMu9hnj0bYDO8/R2VXzqUMh0ROtXpUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T07:37:35Z"
  mac: ENC[AES256_GCM,data:Tn4cijR+G/sPoqGkcjXQs14Gv/cCBYqjxfmnoOdd4Z/1bmdWMq79r9NMaW0++nHfl5KkEvFX3pKS4k8R5m5AyTefXbCtcfw1hrJtmAHI7nO9Gt+Tu8YF2uUYE8I3GbD2zAkiGvsyFRGrA3aufTsxvu4dKYuXWYzveIyYqe7KITo=,iv:fcjirM1Q+vD7icQ79PPkyaBGP9vXJMe0PNgl9P5IUOw=,tag:XbgMA/PG4+f/18OGWaKPBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
