apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-secret
  namespace: office
stringData:
  PAPERLESS_KEY: ENC[AES256_GCM,data:Fc8WVk7EydIcXp8UWzc9R1Y9y/PCAmDBzY7XTViRCTg1MhlvR+J5SeE/Ftml,iv:D5B4yuFTpTZ0/hHbXqwjmz1779WKFOqZj9Jt0mvGEVM=,tag:UT6I5sHkIeQH2jMc+rI1Yg==,type:str]
  PAPERLESS_EMAIL_USERNAME: ENC[AES256_GCM,data:rmnLpppDb8dR3QByl6stliVFRBAs0g==,iv:1Dgzz76SAS3MGB9vREKNaaH7zWAOQ2YmJl0ELrdOL0o=,tag:ayXGLLzrvNAiRHcc8p8VhQ==,type:str]
  PAPERLESS_EMAIL_PASSWORD: ENC[AES256_GCM,data:5nV8rr+IlxQOz7zN4yIBnCh0IWA=,iv:iTFTh84Ky/HC7VeB/a+Bv+HRrxcN/xnRiE49i8Z1yhI=,tag:ja3VYuOOMQYGlGWnKL7daw==,type:str]
  redis-password: ENC[AES256_GCM,data:l0Wq+XVjAPaqiMgGki/6/uCjCKmh2l5AYHrf8WK/7ykvLMw3DWM8VA==,iv:mfK9TUX5LQ3wkgoVESwD/iDRSIWU4TkNP+n5WkWhb5w=,tag:bNVPDBco2P2SKEMrDDwJgA==,type:str]
  mariadb-password: ENC[AES256_GCM,data:Dz26/dUJeEBqoOIR5My8Bf1tUWCzALuKnduizn54AkRp9+Qk1s0zN5Z3Ce1qgyke,iv:syhYYdOcN+SmU50HhfSJXjgKBppXF53u4s2IwY+DRy4=,tag:AB4xHh2viN2+H+UbtqWevA==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:bc637/IS8M4ldAr7rPD99S8AD6OZI8MKMeLh49+NcLnyfpZITpiSWg==,iv:rmCySM2ueDYxE3omJrMd+elN7PSaeTtfe3w7enzfPa0=,tag:ke+jy6dZ9MdJpq1RDqFqOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbURRbW1CVjArWWhtOWVW
        UjBXY2VwSDl6N0Jud2ZFMXl2dVFkUlJ3K2hrCjRuVnAwbkFnMGpkSm1kM2llYkN1
        d205dE1NQUZGOWM4WmZzVjlham5FTWcKLS0tIGUrdnFoUVk3TUtNSWJEKzFMTktu
        TkNtZWFhcUIvdFBmYm9UK3lYZEZiZUEK7sbXkKm0x5XDDfcwyO6cJzSV6YXt7pnI
        IHsr8bjqj3ORBINDWZG+kaAP57tyZ7Kupo8lW3allVdiGoYP24GcMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T10:23:38Z"
  mac: ENC[AES256_GCM,data:LDqsrgcpTQD3DVauH9xJImXF0UiQG7b0FbNrVGkyN5uxRc+6ycilLrxYMhNZsht/8BBsIfcoYotzRJx617SAzXTvHNxuafq6X7OywpM1C3G5lTqDkvyLeuUzzB2yWj34PzDA0KJGivx6bKjE7OCkuWeVOtR8tAcihvTbdVLs8Yo=,iv:C2Zn7/Hg2MVhpiMwAj+uH8TcMWbHvflwOfs1wrKN/GQ=,tag:5Fl1mDeqkq0QqM/F9bNfrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
