apiVersion: v1
kind: Secret
metadata:
  name: mangold-smarthomeadvisor-secrets
  namespace: my-software-showcase
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:ENCRYPTED_DATABASE_URL,iv:INITIALIZATION_VECTOR,tag:TAG,type:str]
  DB_HOST: ENC[AES256_GCM,data:ENCRYPTED_HOST,iv:INITIALIZATION_VECTOR,tag:TAG,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:ENCRYPTED_USERNAME,iv:INITIALIZATION_VECTOR,tag:TAG,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:ENCRYPTED_PASSWORD,iv:INITIALIZATION_VECTOR,tag:TAG,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:showcase_mangold_smarthomeadvisor_prod,iv:INITIALIZATION_VECTOR,tag:TAG,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:ENCRYPTED_SECRET_KEY_BASE,iv:INITIALIZATION_VECTOR,tag:TAG,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        ENCRYPTED_AGE_KEY
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T17:30:00Z"
  mac: ENC[AES256_GCM,data:ENCRYPTED_MAC,iv:INITIALIZATION_VECTOR,tag:TAG,type:str]
  mac_only_encrypted: true
  version: 3.13.0
