apiVersion: v1
kind: Secret
metadata:
  name: open-webui-tts-secret
  namespace: ai
type: Opaque
stringData:
  AUDIO_TTS_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:0Ok1mjnO3H/WzETlpR3f+OS98UIp+kcCvOVtEvM=,iv:nUerliRoFEo156EPi5xJLlnFme8M4hR3O/xgecRD+X0=,tag:pC9kYjgDpBw90SB9kydHMQ==,type:str]
  AUDIO_TTS_OPENAI_API_KEY: ENC[AES256_GCM,data:lmaJ0Og=,iv:5n9EXaAD/IvCSDzyvtm3laSnlZAWPkEild/qAk9vYrk=,tag:5t2BePN/eVmcRoGvzFFpWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS1M5R01abUVUVVkzR0lm
        M2lWY3FBQWhtemlaQ2pNOXVibHFqVUxDN0ZRCjA4Qm0yOTMyV3A0Mm9zazlDT2p4
        b0NkemptZ2pNdmJHNkt2K3h3eTVuZEkKLS0tIGFoTjcvMWpoNWpGQm9CMUN5dDhC
        Ny85a2RFaExNUjMvS0YxVVVVb3kwR2sKdXH/JS9to6Ld3qrUEE9lQy2Gjln1Uy3P
        RlKvpAUbbNk8Kn3oyjZUSKGw04SACjhm6xmEqd0aVdN/Ocgoqt+4ig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T20:37:29Z"
  mac: ENC[AES256_GCM,data:LZIck84eTlPB6GHqaX5/LLPST8kJcYaCp1ImmMbRxjxRBMkpUGJfZ1Bf7EGjiXkIh2WK9YEDWzPLN+yrgeh6FJur/fO1SfsOAN4jTRJtkwtQsjBl/k2jRj1Wh+bpgmcAvpVhJNTy08/ML+wVZhrejmbSc2pAOPQhOJEwBWXfi24=,iv:FFW3HpWrkiSpMfFf1akZiM3DqIAllXGqQNhegIBgrRE=,tag:UZ8x0086iqMrVafedThcpA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
